add_message_files(
  FILES
  AckermannVelocitySetpoint.msg
  ActionRequest.msg
  ActuatorArmed.msg
  ActuatorControlsStatus.msg
  ActuatorMotors.msg
  ActuatorOutputs.msg
  ActuatorServos.msg
  ActuatorServosTrim.msg
  ActuatorTest.msg
  AdcReport.msg
  Airspeed.msg
  AirspeedValidated.msg
  AirspeedWind.msg
  ArmingCheckReply.msg
  ArmingCheckRequest.msg
  AutotuneAttitudeControlStatus.msg
  BatteryStatus.msg
  ButtonEvent.msg
  CameraCapture.msg
  CameraStatus.msg
  CameraTrigger.msg
  CanInterfaceStatus.msg
  CellularStatus.msg
  CollisionConstraints.msg
  ConfigOverrides.msg
  ControlAllocatorStatus.msg
  Cpuload.msg
  DatamanRequest.msg
  DatamanResponse.msg
  DebugArray.msg
  DebugKeyValue.msg
  DebugValue.msg
  DebugVect.msg
  DifferentialPressure.msg
  DifferentialVelocitySetpoint.msg
  DistanceSensorModeChangeRequest.msg
  DistanceSensor.msg
  Ekf2Timestamps.msg
  EscReport.msg
  EscStatus.msg
  EstimatorAidSource1d.msg
  EstimatorAidSource2d.msg
  EstimatorAidSource3d.msg
  EstimatorBias3d.msg
  EstimatorBias.msg
  EstimatorEventFlags.msg
  EstimatorGpsStatus.msg
  EstimatorInnovations.msg
  EstimatorSelectorStatus.msg
  EstimatorSensorBias.msg
  EstimatorStates.msg
  EstimatorStatusFlags.msg
  EstimatorStatus.msg
  Event.msg
  FailsafeFlags.msg
  FailureDetectorStatus.msg
  FigureEightStatus.msg
  FlightPhaseEstimation.msg
  FollowTargetEstimator.msg
  FollowTarget.msg
  FollowTargetStatus.msg
  FuelTankStatus.msg
  GeneratorStatus.msg
  GeofenceResult.msg
  GeofenceStatus.msg
  GimbalControls.msg
  GimbalDeviceAttitudeStatus.msg
  GimbalDeviceInformation.msg
  GimbalDeviceSetAttitude.msg
  GimbalManagerInformation.msg
  GimbalManagerSetAttitude.msg
  GimbalManagerSetManualControl.msg
  GimbalManagerStatus.msg
  GotoSetpoint.msg
  GpioConfig.msg
  GpioIn.msg
  GpioOut.msg
  GpioRequest.msg
  GpsDump.msg
  GpsInjectData.msg
  Gripper.msg
  HealthReport.msg
  HeaterStatus.msg
  HomePosition.msg
  HoverThrustEstimate.msg
  InputRc.msg
  InternalCombustionEngineControl.msg
  InternalCombustionEngineStatus.msg
  IridiumsbdStatus.msg
  IrlockReport.msg
  LandingGear.msg
  LandingGearWheel.msg
  LandingTargetInnovations.msg
  LandingTargetPose.msg
  LaunchDetectionStatus.msg
  LedControl.msg
  LoggerStatus.msg
  LogMessage.msg
  MagnetometerBiasEstimate.msg
  MagWorkerData.msg
  ManualControlSetpoint.msg
  ManualControlSwitches.msg
  MavlinkLog.msg
  MavlinkTunnel.msg
  MessageFormatRequest.msg
  MessageFormatResponse.msg
  Mission.msg
  MissionResult.msg
  ModeCompleted.msg
  MountOrientation.msg
  NavigatorMissionItem.msg
  NavigatorStatus.msg
  NormalizedUnsignedSetpoint.msg
  NpfgStatus.msg
  ObstacleDistance.msg
  OffboardControlMode.msg
  OnboardComputerStatus.msg
  OpenDroneIdArmStatus.msg
  OpenDroneIdOperatorId.msg
  OpenDroneIdSelfId.msg
  OpenDroneIdSystem.msg
  OrbitStatus.msg
  OrbTestLarge.msg
  OrbTestMedium.msg
  OrbTest.msg
  ParameterResetRequest.msg
  ParameterSetUsedRequest.msg
  ParameterSetValueRequest.msg
  ParameterSetValueResponse.msg
  ParameterUpdate.msg
  Ping.msg
  PositionControllerLandingStatus.msg
  PositionControllerStatus.msg
  PositionSetpoint.msg
  PositionSetpointTriplet.msg
  PowerButtonState.msg
  PowerMonitor.msg
  PpsCapture.msg
  PurePursuitStatus.msg
  PwmInput.msg
  Px4ioStatus.msg
  QshellReq.msg
  QshellRetval.msg
  RadioStatus.msg
  RateCtrlStatus.msg
  RcChannels.msg
  RcParameterMap.msg
  RegisterExtComponentReply.msg
  RegisterExtComponentRequest.msg
  RoverAttitudeSetpoint.msg
  RoverAttitudeStatus.msg
  RoverPositionSetpoint.msg
  RoverRateSetpoint.msg
  RoverRateStatus.msg
  RoverSteeringSetpoint.msg
  RoverThrottleSetpoint.msg
  RoverVelocityStatus.msg
  Rpm.msg
  RtlStatus.msg
  RtlTimeEstimate.msg
  SatelliteInfo.msg
  SensorAccelFifo.msg
  SensorAccel.msg
  SensorAirflow.msg
  SensorBaro.msg
  SensorCombined.msg
  SensorCorrection.msg
  SensorGnssRelative.msg
  SensorGps.msg
  SensorGyroFft.msg
  SensorGyroFifo.msg
  SensorGyro.msg
  SensorHygrometer.msg
  SensorMag.msg
  SensorOpticalFlow.msg
  SensorPreflightMag.msg
  SensorSelection.msg
  SensorsStatusImu.msg
  SensorsStatus.msg
  SensorUwb.msg
  SystemPower.msg
  TakeoffStatus.msg
  TaskStackInfo.msg
  TecsStatus.msg
  TelemetryStatus.msg
  TiltrotorExtraControls.msg
  TimesyncStatus.msg
  TrajectorySetpoint6dof.msg
  TrajectorySetpoint.msg
  TransponderReport.msg
  TuneControl.msg
  UavcanParameterRequest.msg
  UavcanParameterValue.msg
  UlogStreamAck.msg
  UlogStream.msg
  UnregisterExtComponent.msg
  VehicleAcceleration.msg
  VehicleAirData.msg
  VehicleAngularAccelerationSetpoint.msg
  VehicleAngularVelocity.msg
  VehicleAttitude.msg
  VehicleAttitudeSetpoint.msg
  VehicleCommandAck.msg
  VehicleCommand.msg
  VehicleConstraints.msg
  VehicleControlMode.msg
  VehicleGlobalPosition.msg
  VehicleImu.msg
  VehicleImuStatus.msg
  VehicleLandDetected.msg
  VehicleLocalPosition.msg
  VehicleLocalPositionSetpoint.msg
  VehicleMagnetometer.msg
  VehicleOdometry.msg
  VehicleOpticalFlow.msg
  VehicleOpticalFlowVel.msg
  VehicleRatesSetpoint.msg
  VehicleRoi.msg
  VehicleStatus.msg
  VehicleThrustSetpoint.msg
  VehicleTorqueSetpoint.msg
  VelocityLimits.msg
  VtolVehicleStatus.msg
  WheelEncoders.msg
  Wind.msg
  YawEstimatorStatus.msg
)
