(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          R-VAL
          R
          BUTTONS-VAL
          BUTTONS
          BUTTONS2-VAL
          BUTTONS2
          ENABLED_EXTENSIONS-VAL
          ENABLED_EXTENSIONS
          S-VAL
          S
          T-VAL
          T
          AUX1-VAL
          AUX1
          AUX2-VAL
          AUX2
          AUX3-VAL
          AUX3
          AUX4-VAL
          AUX4
          AUX5-VAL
          AUX5
          AUX6-VAL
          AUX6
))