(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VENDOR_NAME-VAL
          VENDOR_NAME
          MODEL_NAME-VAL
          MODEL_NAME
          CUSTOM_NAME-VAL
          CUSTOM_NAME
          FIRMWARE_VERSION-VAL
          FIRMWARE_VERSION
          HARDWARE_VERSION-VAL
          HARDWARE_VERSION
          UID-VAL
          UID
          CAP_FLAGS-VAL
          CAP_FLAGS
          CUSTOM_CAP_FLAGS-VAL
          CUSTOM_CAP_FLAGS
          ROLL_MIN-VAL
          ROLL_MIN
          ROLL_MAX-VAL
          ROLL_MAX
          PITCH_MIN-VAL
          PITCH_MIN
          PITCH_MAX-VAL
          PITCH_MAX
          YAW_MIN-VAL
          YAW_MIN
          YAW_MAX-VAL
          YAW_MAX
))