(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          REPORT-VAL
          REPORT
          CONFIDENCE-VAL
          CONFIDENCE
          COMPASS_ID-VAL
          COMPASS_ID
          CAL_MASK-VAL
          CAL_MASK
          CAL_STATUS-VAL
          CAL_STATUS
          AUTOSAVED-VAL
          AUTOSAVED
          FITNESS-VAL
          FITNESS
          OFS_X-VAL
          OFS_X
          OFS_Y-VAL
          OFS_Y
          OFS_Z-VAL
          OFS_Z
          DIAG_X-VAL
          DIAG_X
          DIAG_Y-VAL
          DIAG_Y
          DIAG_Z-VAL
          DIAG_Z
          OFFDIAG_X-VAL
          OFFDIAG_X
          OFFDIAG_Y-VAL
          OFFDIAG_Y
          OFFDIAG_Z-VAL
          OFFDIAG_Z
          ORIENTATION_CONFIDENCE-VAL
          ORIENTATION_CONFIDENCE
          OLD_ORIENTATION-VAL
          OLD_ORIENTATION
          NEW_ORIENTATION-VAL
          NEW_ORIENTATION
          SCALE_FACTOR-VAL
          SCALE_FACTOR
))