(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          FLAGS-VAL
          FLAGS
          GIMBAL_DEVICE_ID-VAL
          GIMBAL_DEVICE_ID
          PRIMARY_CONTROL_SYSID-VAL
          PRIMARY_CONTROL_SYSID
          PRIMARY_CONTROL_COMPID-VAL
          PRIMARY_CONTROL_COMPID
          SECONDARY_CONTROL_SYSID-VAL
          SECONDARY_CONTROL_SYSID
          SECONDARY_CONTROL_COMPID-VAL
          SECONDARY_CONTROL_COMPID
))