(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          PARAM1-VAL
          PARAM1
          PARAM2-VAL
          PARAM2
          PARAM3-VAL
          PARAM3
          PARAM4-VAL
          PARAM4
          PARAM5-VAL
          PARAM5
          PARAM6-VAL
          PARAM6
          PARAM7-VAL
          PARAM7
          COMMAND-VAL
          COMMAND
          TARGET_SYSTEM-VAL
          TARGET_SYSTEM
          TARGET_COMPONENT-VAL
          TARGET_COMPONENT
          SOURCE_SYSTEM-VAL
          SOURCE_SYSTEM
          SOURCE_COMPONENT-VAL
          SOURCE_COMPONENT
          CONFIRMATION-VAL
          CONFIRMATION
          FROM_EXTERNAL-VAL
          FROM_EXTERNAL
))