(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          GYRO_RAD-VAL
          GYRO_RAD
          GYRO_INTEGRAL_DT-VAL
          GYRO_INTEGRAL_DT
          ACCELEROMETER_TIMESTAMP_RELATIVE-VAL
          ACCELEROMETER_TIMESTAMP_RELATIVE
          ACCELEROMETER_M_S2-VAL
          ACCELEROMETER_M_S2
          ACCELEROMETER_INTEGRAL_DT-VAL
          ACCELEROMETER_INTEGRAL_DT
          ACCELEROMETER_CLIPPING-VAL
          ACCELEROMETER_CLIPPING
))