(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          MODE_SLOT-VAL
          MODE_SLOT
          ARM_SWITCH-VAL
          ARM_SWITCH
          RETURN_SWITCH-VAL
          RETURN_SWITCH
          LOITER_SWITCH-VAL
          LOITER_SWITCH
          OFFBOARD_SWITCH-VAL
          OFFBOARD_SWITCH
          KILL_SWITCH-VAL
          KILL_SWITCH
          GEAR_SWITCH-VAL
          GEAR_SWITCH
          TRANSITION_SWITCH-VAL
          TRANSITION_SWITCH
          MODE_SWITCH-VAL
          MODE_SWITCH
          MAN_SWITCH-VAL
          MAN_SWITCH
          ACRO_SWITCH-VAL
          ACRO_SWITCH
          STAB_SWITCH-VAL
          STAB_SWITCH
          POSCTL_SWITCH-VAL
          POSCTL_SWITCH
          SWITCH_CHANGES-VAL
          SWITCH_CHANGES
))