(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          STATUS-VAL
          STATUS
          BATTERY_CURRENT-VAL
          BATTERY_CURRENT
          LOAD_CURRENT-VAL
          LOAD_CURRENT
          POWER_GENERATED-VAL
          POWER_GENERATED
          BUS_VOLTAGE-VAL
          BUS_VOLTAGE
          BAT_CURRENT_SETPOINT-VAL
          BAT_CURRENT_SETPOINT
          RUNTIME-VAL
          RUNTIME
          TIME_UNTIL_MAINTENANCE-VAL
          TIME_UNTIL_MAINTENANCE
          GENERATOR_SPEED-VAL
          GENERATOR_SPEED
          RECTIFIER_TEMPERATURE-VAL
          RECTIFIER_TEMPERATURE
          GENERATOR_TEMPERATURE-VAL
          GENERATOR_TEMPERATURE
))