(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          AIRSPEED_TIMESTAMP_REL-VAL
          AIRSPEED_TIMESTAMP_REL
          DISTANCE_SENSOR_TIMESTAMP_REL-VAL
          DISTANCE_SENSOR_TIMESTAMP_REL
          OPTICAL_FLOW_TIMESTAMP_REL-VAL
          OPTICAL_FLOW_TIMESTAMP_REL
          VEHICLE_AIR_DATA_TIMESTAMP_REL-VAL
          VEHICLE_AIR_DATA_TIMESTAMP_REL
          VEHICLE_MAGNETOMETER_TIMESTAMP_REL-VAL
          VEHICLE_MAGNETOMETER_TIMESTAMP_REL
          VISUAL_ODOMETRY_TIMESTAMP_REL-VAL
          VISUAL_ODOMETRY_TIMESTAMP_REL
))