(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          INSTANCE_COUNT-VAL
          INSTANCE_COUNT
          SEQUENCE_CURRENT-VAL
          SEQUENCE_CURRENT
          NAV_CMD-VAL
          NAV_CMD
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          TIME_INSIDE-VAL
          TIME_INSIDE
          ACCEPTANCE_RADIUS-VAL
          ACCEPTANCE_RADIUS
          LOITER_RADIUS-VAL
          LOITER_RADIUS
          YAW-VAL
          YAW
          ALTITUDE-VAL
          ALTITUDE
          FRAME-VAL
          FRAME
          ORIGIN-VAL
          ORIGIN
          LOITER_EXIT_XTRACK-VAL
          LOITER_EXIT_XTRACK
          FORCE_HEADING-VAL
          FORCE_HEADING
          ALTITUDE_IS_RELATIVE-VAL
          ALTITUDE_IS_RELATIVE
          AUTOCONTINUE-VAL
          AUTOCONTINUE
          VTOL_BACK_TRANSITION-VAL
          VTOL_BACK_TRANSITION
))