(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          ALT_ELLIPSOID-VAL
          ALT_ELLIPSOID
          DELTA_ALT-VAL
          DELTA_ALT
          LAT_LON_RESET_COUNTER-VAL
          LAT_LON_RESET_COUNTER
          ALT_RESET_COUNTER-VAL
          ALT_RESET_COUNTER
          EPH-VAL
          EPH
          EPV-VAL
          EPV
          TERRAIN_ALT-VAL
          TERRAIN_ALT
          TERRAIN_ALT_VALID-VAL
          TERRAIN_ALT_VALID
          DEAD_RECKONING-VAL
          DEAD_RECKONING
))