(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          ICAO_ADDRESS-VAL
          ICAO_ADDRESS
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALTITUDE_TYPE-VAL
          ALTITUDE_TYPE
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          HOR_VELOCITY-VAL
          HOR_VELOCITY
          VER_VELOCITY-VAL
          VER_VELOCITY
          CALLSIGN-VAL
          CALLSIGN
          EMITTER_TYPE-VAL
          EMITTER_TYPE
          TSLC-VAL
          TSLC
          FLAGS-VAL
          FLAGS
          SQUAWK-VAL
          SQUAWK
          UAS_ID-VAL
          UAS_ID
))