(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          GYRO_DEVICE_ID-VAL
          GYRO_DEVICE_ID
          GYRO_BIAS-VAL
          GYRO_BIAS
          GYRO_BIAS_LIMIT-VAL
          GYRO_BIAS_LIMIT
          GYRO_BIAS_VARIANCE-VAL
          GYRO_BIAS_VARIANCE
          GYRO_BIAS_VALID-VAL
          GYRO_BIAS_VALID
          ACCEL_DEVICE_ID-VAL
          ACCEL_DEVICE_ID
          ACCEL_BIAS-VAL
          ACCEL_BIAS
          ACCEL_BIAS_LIMIT-VAL
          ACCEL_BIAS_LIMIT
          ACCEL_BIAS_VARIANCE-VAL
          ACCEL_BIAS_VARIANCE
          ACCEL_BIAS_VALID-VAL
          ACCEL_BIAS_VALID
          MAG_DEVICE_ID-VAL
          MAG_DEVICE_ID
          MAG_BIAS-VAL
          MAG_BIAS
          MAG_BIAS_LIMIT-VAL
          MAG_BIAS_LIMIT
          MAG_BIAS_VARIANCE-VAL
          MAG_BIAS_VARIANCE
          MAG_BIAS_VALID-VAL
          MAG_BIAS_VALID
))