(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          DEVICE_ID-VAL
          DEVICE_ID
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          ALT_ELLIPSOID-VAL
          ALT_ELLIPSOID
          S_VARIANCE_M_S-VAL
          S_VARIANCE_M_S
          C_VARIANCE_RAD-VAL
          C_VARIANCE_RAD
          FIX_TYPE-VAL
          FIX_TYPE
          EPH-VAL
          EPH
          EPV-VAL
          EPV
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          NOISE_PER_MS-VAL
          NOISE_PER_MS
          AUTOMATIC_GAIN_CONTROL-VAL
          AUTOMATIC_GAIN_CONTROL
          JAMMING_INDICATOR-VAL
          JAMMING_INDICATOR
          JAMMING_STATE-VAL
          JAMMING_STATE
          VEL_M_S-VAL
          VEL_M_S
          VEL_N_M_S-VAL
          VEL_N_M_S
          VEL_E_M_S-VAL
          VEL_E_M_S
          VEL_D_M_S-VAL
          VEL_D_M_S
          COG_RAD-VAL
          COG_RAD
          VEL_NED_VALID-VAL
          VEL_NED_VALID
          TIMESTAMP_TIME_RELATIVE-VAL
          TIMESTAMP_TIME_RELATIVE
          TIME_UTC_USEC-VAL
          TIME_UTC_USEC
          SATELLITES_USED-VAL
          SATELLITES_USED
          HEADING-VAL
          HEADING
          HEADING_OFFSET-VAL
          HEADING_OFFSET
))