(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TORQUE_SETPOINT_ACHIEVED-VAL
          TORQUE_SETPOINT_ACHIEVED
          ALLOCATED_TORQUE-VAL
          ALLOCATED_TORQUE
          UNALLOCATED_TORQUE-VAL
          UNALLOCATED_TORQUE
          THRUST_SETPOINT_ACHIEVED-VAL
          THRUST_SETPOINT_ACHIEVED
          ALLOCATED_THRUST-VAL
          ALLOCATED_THRUST
          UNALLOCATED_THRUST-VAL
          UNALLOCATED_THRUST
          ACTUATOR_SATURATION-VAL
          ACTUATOR_SATURATION
))