(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          ACCEL_DEVICE_ID_PRIMARY-VAL
          ACCEL_DEVICE_ID_PRIMARY
          ACCEL_DEVICE_IDS-VAL
          ACCEL_DEVICE_IDS
          ACCEL_INCONSISTENCY_M_S_S-VAL
          ACCEL_INCONSISTENCY_M_S_S
          ACCEL_HEALTHY-VAL
          ACCEL_HEALTHY
          ACCEL_PRIORITY-VAL
          ACCEL_PRIORITY
          GYRO_DEVICE_ID_PRIMARY-VAL
          GYRO_DEVICE_ID_PRIMARY
          GYRO_DEVICE_IDS-VAL
          GYRO_DEVICE_IDS
          GYRO_INCONSISTENCY_RAD_S-VAL
          GYRO_INCONSISTENCY_RAD_S
          GYRO_HEALTHY-VAL
          GYRO_HEALTHY
          GYRO_PRIORITY-VAL
          GYRO_PRIORITY
))