(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          GYRO_DEVICE_IDS-VAL
          GYRO_DEVICE_IDS
          GYRO_TEMPERATURE-VAL
          GYRO_TEMPERATURE
          GYRO_OFFSET_0-VAL
          GYRO_OFFSET_0
          GYRO_OFFSET_1-VAL
          GYRO_OFFSET_1
          GYRO_OFFSET_2-VAL
          GYRO_OFFSET_2
          GYRO_OFFSET_3-VAL
          GYRO_OFFSET_3
          ACCEL_DEVICE_IDS-VAL
          ACCEL_DEVICE_IDS
          ACCEL_TEMPERATURE-VAL
          ACCEL_TEMPERATURE
          ACCEL_OFFSET_0-VAL
          ACCEL_OFFSET_0
          ACCEL_OFFSET_1-VAL
          ACCEL_OFFSET_1
          ACCEL_OFFSET_2-VAL
          ACCEL_OFFSET_2
          ACCEL_OFFSET_3-VAL
          ACCEL_OFFSET_3
          BARO_DEVICE_IDS-VAL
          BARO_DEVICE_IDS
          BARO_TEMPERATURE-VAL
          BARO_TEMPERATURE
          BARO_OFFSET_0-VAL
          BARO_OFFSET_0
          BARO_OFFSET_1-VAL
          BARO_OFFSET_1
          BARO_OFFSET_2-VAL
          BARO_OFFSET_2
          BARO_OFFSET_3-VAL
          BARO_OFFSET_3
))