(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          IS_STATIC-VAL
          IS_STATIC
          REL_POS_VALID-VAL
          REL_POS_VALID
          REL_VEL_VALID-VAL
          REL_VEL_VALID
          X_REL-VAL
          X_REL
          Y_REL-VAL
          Y_REL
          Z_REL-VAL
          Z_REL
          VX_REL-VAL
          VX_REL
          VY_REL-VAL
          VY_REL
          COV_X_REL-VAL
          COV_X_REL
          COV_Y_REL-VAL
          COV_Y_REL
          COV_VX_REL-VAL
          COV_VX_REL
          COV_VY_REL-VAL
          COV_VY_REL
          ABS_POS_VALID-VAL
          ABS_POS_VALID
          X_ABS-VAL
          X_ABS
          Y_ABS-VAL
          Y_ABS
          Z_ABS-VAL
          Z_ABS
))