(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          LOCAL_FRAME-VAL
          LOCAL_FRAME
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          Q-VAL
          Q
          Q_OFFSET-VAL
          Q_OFFSET
          POSE_COVARIANCE-VAL
          POSE_COVARIANCE
          VELOCITY_FRAME-VAL
          VELOCITY_FRAME
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          ROLLSPEED-VAL
          ROLLSPEED
          PITCHSPEED-VAL
          PITCHSPEED
          YAWSPEED-VAL
          YAWSPEED
          VELOCITY_COVARIANCE-VAL
          VELOCITY_COVARIANCE
))