(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          GPS_HVEL-VAL
          GPS_HVEL
          GPS_VVEL-VAL
          GPS_VVEL
          GPS_HPOS-VAL
          GPS_HPOS
          GPS_VPOS-VAL
          GPS_VPOS
          EV_HVEL-VAL
          EV_HVEL
          EV_VVEL-VAL
          EV_VVEL
          EV_HPOS-VAL
          EV_HPOS
          EV_VPOS-VAL
          EV_VPOS
          RNG_VPOS-VAL
          RNG_VPOS
          BARO_VPOS-VAL
          BARO_VPOS
          AUX_HVEL-VAL
          AUX_HVEL
          AUX_VVEL-VAL
          AUX_VVEL
          FLOW-VAL
          FLOW
          HEADING-VAL
          HEADING
          MAG_FIELD-VAL
          MAG_FIELD
          DRAG-VAL
          DRAG
          AIRSPEED-VAL
          AIRSPEED
          BETA-VAL
          BETA
          HAGL-VAL
          HAGL
))