(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          INSTANCE_COUNT-VAL
          INSTANCE_COUNT
          SEQ_REACHED-VAL
          SEQ_REACHED
          SEQ_CURRENT-VAL
          SEQ_CURRENT
          SEQ_TOTAL-VAL
          SEQ_TOTAL
          VALID-VAL
          VALID
          WARNING-VAL
          WARNING
          FINISHED-VAL
          FINISHED
          FAILURE-VAL
          FAILURE
          STAY_IN_FAILSAFE-VAL
          STAY_IN_FAILSAFE
          FLIGHT_TERMINATION-VAL
          FLIGHT_TERMINATION
          ITEM_DO_JUMP_CHANGED-VAL
          ITEM_DO_JUMP_CHANGED
          ITEM_CHANGED_INDEX-VAL
          ITEM_CHANGED_INDEX
          ITEM_DO_JUMP_REMAINING-VAL
          ITEM_DO_JUMP_REMAINING
          EXECUTION_MODE-VAL
          EXECUTION_MODE
))