(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          DATA_SOURCE-VAL
          DATA_SOURCE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          R-VAL
          R
          FLAPS-VAL
          FLAPS
          AUX1-VAL
          AUX1
          AUX2-VAL
          AUX2
          AUX3-VAL
          AUX3
          AUX4-VAL
          AUX4
          AUX5-VAL
          AUX5
          AUX6-VAL
          AUX6
))