(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          INDICATED_AIRSPEED_M_S-VAL
          INDICATED_AIRSPEED_M_S
          CALIBRATED_AIRSPEED_M_S-VAL
          CALIBRATED_AIRSPEED_M_S
          TRUE_AIRSPEED_M_S-VAL
          TRUE_AIRSPEED_M_S
          CALIBRATED_GROUND_MINUS_WIND_M_S-VAL
          CALIBRATED_GROUND_MINUS_WIND_M_S
          TRUE_GROUND_MINUS_WIND_M_S-VAL
          TRUE_GROUND_MINUS_WIND_M_S
          AIRSPEED_SENSOR_MEASUREMENT_VALID-VAL
          AIRSPEED_SENSOR_MEASUREMENT_VALID
          SELECTED_AIRSPEED_INDEX-VAL
          SELECTED_AIRSPEED_INDEX
))