(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          XY_VALID-VAL
          XY_VALID
          Z_VALID-VAL
          Z_VALID
          V_XY_VALID-VAL
          V_XY_VALID
          V_Z_VALID-VAL
          V_Z_VALID
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          DELTA_XY-VAL
          DELTA_XY
          XY_RESET_COUNTER-VAL
          XY_RESET_COUNTER
          DELTA_Z-VAL
          DELTA_Z
          Z_RESET_COUNTER-VAL
          Z_RESET_COUNTER
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          Z_DERIV-VAL
          Z_DERIV
          DELTA_VXY-VAL
          DELTA_VXY
          VXY_RESET_COUNTER-VAL
          VXY_RESET_COUNTER
          DELTA_VZ-VAL
          DELTA_VZ
          VZ_RESET_COUNTER-VAL
          VZ_RESET_COUNTER
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          HEADING-VAL
          HEADING
          DELTA_HEADING-VAL
          DELTA_HEADING
          HEADING_RESET_COUNTER-VAL
          HEADING_RESET_COUNTER
          XY_GLOBAL-VAL
          XY_GLOBAL
          Z_GLOBAL-VAL
          Z_GLOBAL
          REF_TIMESTAMP-VAL
          REF_TIMESTAMP
          REF_LAT-VAL
          REF_LAT
          REF_LON-VAL
          REF_LON
          REF_ALT-VAL
          REF_ALT
          DIST_BOTTOM-VAL
          DIST_BOTTOM
          DIST_BOTTOM_VALID-VAL
          DIST_BOTTOM_VALID
          DIST_BOTTOM_SENSOR_BITFIELD-VAL
          DIST_BOTTOM_SENSOR_BITFIELD
          EPH-VAL
          EPH
          EPV-VAL
          EPV
          EVH-VAL
          EVH
          EVV-VAL
          EVV
          VXY_MAX-VAL
          VXY_MAX
          VZ_MAX-VAL
          VZ_MAX
          HAGL_MIN-VAL
          HAGL_MIN
          HAGL_MAX-VAL
          HAGL_MAX
))