(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          VALID-VAL
          VALID
          TYPE-VAL
          TYPE
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          VELOCITY_VALID-VAL
          VELOCITY_VALID
          VELOCITY_FRAME-VAL
          VELOCITY_FRAME
          ALT_VALID-VAL
          ALT_VALID
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          YAW-VAL
          YAW
          YAW_VALID-VAL
          YAW_VALID
          YAWSPEED-VAL
          YAWSPEED
          YAWSPEED_VALID-VAL
          YAWSPEED_VALID
          LANDING_GEAR-VAL
          LANDING_GEAR
          LOITER_RADIUS-VAL
          LOITER_RADIUS
          LOITER_DIRECTION-VAL
          LOITER_DIRECTION
          ACCEPTANCE_RADIUS-VAL
          ACCEPTANCE_RADIUS
          CRUISING_SPEED-VAL
          CRUISING_SPEED
          CRUISING_THROTTLE-VAL
          CRUISING_THROTTLE
          DISABLE_WEATHER_VANE-VAL
          DISABLE_WEATHER_VANE
))