(cl:in-package px4_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          TIMESTAMP_SAMPLE-VAL
          TIMESTAMP_SAMPLE
          CONTROL_STATUS_CHANGES-VAL
          CONTROL_STATUS_CHANGES
          CS_TILT_ALIGN-VAL
          CS_TILT_ALIGN
          CS_YAW_ALIGN-VAL
          CS_YAW_ALIGN
          CS_GPS-VAL
          CS_GPS
          CS_OPT_FLOW-VAL
          CS_OPT_FLOW
          CS_MAG_HDG-VAL
          CS_MAG_HDG
          CS_MAG_3D-VAL
          CS_MAG_3D
          CS_MAG_DEC-VAL
          CS_MAG_DEC
          CS_IN_AIR-VAL
          CS_IN_AIR
          CS_WIND-VAL
          CS_WIND
          CS_BARO_HGT-VAL
          CS_BARO_HGT
          CS_RNG_HGT-VAL
          CS_RNG_HGT
          CS_GPS_HGT-VAL
          CS_GPS_HGT
          CS_EV_POS-VAL
          CS_EV_POS
          CS_EV_YAW-VAL
          CS_EV_YAW
          CS_EV_HGT-VAL
          CS_EV_HGT
          CS_FUSE_BETA-VAL
          CS_FUSE_BETA
          CS_MAG_FIELD_DISTURBED-VAL
          CS_MAG_FIELD_DISTURBED
          CS_FIXED_WING-VAL
          CS_FIXED_WING
          CS_MAG_FAULT-VAL
          CS_MAG_FAULT
          CS_FUSE_ASPD-VAL
          CS_FUSE_ASPD
          CS_GND_EFFECT-VAL
          CS_GND_EFFECT
          CS_RNG_STUCK-VAL
          CS_RNG_STUCK
          CS_GPS_YAW-VAL
          CS_GPS_YAW
          CS_MAG_ALIGNED_IN_FLIGHT-VAL
          CS_MAG_ALIGNED_IN_FLIGHT
          CS_EV_VEL-VAL
          CS_EV_VEL
          CS_SYNTHETIC_MAG_Z-VAL
          CS_SYNTHETIC_MAG_Z
          CS_VEHICLE_AT_REST-VAL
          CS_VEHICLE_AT_REST
          CS_GPS_YAW_FAULT-VAL
          CS_GPS_YAW_FAULT
          FAULT_STATUS_CHANGES-VAL
          FAULT_STATUS_CHANGES
          FS_BAD_MAG_X-VAL
          FS_BAD_MAG_X
          FS_BAD_MAG_Y-VAL
          FS_BAD_MAG_Y
          FS_BAD_MAG_Z-VAL
          FS_BAD_MAG_Z
          FS_BAD_HDG-VAL
          FS_BAD_HDG
          FS_BAD_MAG_DECL-VAL
          FS_BAD_MAG_DECL
          FS_BAD_AIRSPEED-VAL
          FS_BAD_AIRSPEED
          FS_BAD_SIDESLIP-VAL
          FS_BAD_SIDESLIP
          FS_BAD_OPTFLOW_X-VAL
          FS_BAD_OPTFLOW_X
          FS_BAD_OPTFLOW_Y-VAL
          FS_BAD_OPTFLOW_Y
          FS_BAD_VEL_N-VAL
          FS_BAD_VEL_N
          FS_BAD_VEL_E-VAL
          FS_BAD_VEL_E
          FS_BAD_VEL_D-VAL
          FS_BAD_VEL_D
          FS_BAD_POS_N-VAL
          FS_BAD_POS_N
          FS_BAD_POS_E-VAL
          FS_BAD_POS_E
          FS_BAD_POS_D-VAL
          FS_BAD_POS_D
          FS_BAD_ACC_BIAS-VAL
          FS_BAD_ACC_BIAS
          FS_BAD_ACC_VERTICAL-VAL
          FS_BAD_ACC_VERTICAL
          FS_BAD_ACC_CLIPPING-VAL
          FS_BAD_ACC_CLIPPING
          INNOVATION_FAULT_STATUS_CHANGES-VAL
          INNOVATION_FAULT_STATUS_CHANGES
          REJECT_HOR_VEL-VAL
          REJECT_HOR_VEL
          REJECT_VER_VEL-VAL
          REJECT_VER_VEL
          REJECT_HOR_POS-VAL
          REJECT_HOR_POS
          REJECT_VER_POS-VAL
          REJECT_VER_POS
          REJECT_MAG_X-VAL
          REJECT_MAG_X
          REJECT_MAG_Y-VAL
          REJECT_MAG_Y
          REJECT_MAG_Z-VAL
          REJECT_MAG_Z
          REJECT_YAW-VAL
          REJECT_YAW
          REJECT_AIRSPEED-VAL
          REJECT_AIRSPEED
          REJECT_SIDESLIP-VAL
          REJECT_SIDESLIP
          REJECT_HAGL-VAL
          REJECT_HAGL
          REJECT_OPTFLOW_X-VAL
          REJECT_OPTFLOW_X
          REJECT_OPTFLOW_Y-VAL
          REJECT_OPTFLOW_Y
))