// Generated by gencpp from file px4_msgs/AirspeedValidated.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_AIRSPEEDVALIDATED_H
#define PX4_MSGS_MESSAGE_AIRSPEEDVALIDATED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct AirspeedValidated_
{
  typedef AirspeedValidated_<ContainerAllocator> Type;

  AirspeedValidated_()
    : timestamp(0)
    , indicated_airspeed_m_s(0.0)
    , calibrated_airspeed_m_s(0.0)
    , true_airspeed_m_s(0.0)
    , calibrated_ground_minus_wind_m_s(0.0)
    , true_ground_minus_wind_m_s(0.0)
    , airspeed_sensor_measurement_valid(false)
    , selected_airspeed_index(0)  {
    }
  AirspeedValidated_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , indicated_airspeed_m_s(0.0)
    , calibrated_airspeed_m_s(0.0)
    , true_airspeed_m_s(0.0)
    , calibrated_ground_minus_wind_m_s(0.0)
    , true_ground_minus_wind_m_s(0.0)
    , airspeed_sensor_measurement_valid(false)
    , selected_airspeed_index(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef float _indicated_airspeed_m_s_type;
  _indicated_airspeed_m_s_type indicated_airspeed_m_s;

   typedef float _calibrated_airspeed_m_s_type;
  _calibrated_airspeed_m_s_type calibrated_airspeed_m_s;

   typedef float _true_airspeed_m_s_type;
  _true_airspeed_m_s_type true_airspeed_m_s;

   typedef float _calibrated_ground_minus_wind_m_s_type;
  _calibrated_ground_minus_wind_m_s_type calibrated_ground_minus_wind_m_s;

   typedef float _true_ground_minus_wind_m_s_type;
  _true_ground_minus_wind_m_s_type true_ground_minus_wind_m_s;

   typedef uint8_t _airspeed_sensor_measurement_valid_type;
  _airspeed_sensor_measurement_valid_type airspeed_sensor_measurement_valid;

   typedef int8_t _selected_airspeed_index_type;
  _selected_airspeed_index_type selected_airspeed_index;





  typedef boost::shared_ptr< ::px4_msgs::AirspeedValidated_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::AirspeedValidated_<ContainerAllocator> const> ConstPtr;

}; // struct AirspeedValidated_

typedef ::px4_msgs::AirspeedValidated_<std::allocator<void> > AirspeedValidated;

typedef boost::shared_ptr< ::px4_msgs::AirspeedValidated > AirspeedValidatedPtr;
typedef boost::shared_ptr< ::px4_msgs::AirspeedValidated const> AirspeedValidatedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::AirspeedValidated_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::AirspeedValidated_<ContainerAllocator1> & lhs, const ::px4_msgs::AirspeedValidated_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.indicated_airspeed_m_s == rhs.indicated_airspeed_m_s &&
    lhs.calibrated_airspeed_m_s == rhs.calibrated_airspeed_m_s &&
    lhs.true_airspeed_m_s == rhs.true_airspeed_m_s &&
    lhs.calibrated_ground_minus_wind_m_s == rhs.calibrated_ground_minus_wind_m_s &&
    lhs.true_ground_minus_wind_m_s == rhs.true_ground_minus_wind_m_s &&
    lhs.airspeed_sensor_measurement_valid == rhs.airspeed_sensor_measurement_valid &&
    lhs.selected_airspeed_index == rhs.selected_airspeed_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::AirspeedValidated_<ContainerAllocator1> & lhs, const ::px4_msgs::AirspeedValidated_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::AirspeedValidated_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::AirspeedValidated_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::AirspeedValidated_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b8193ce69103723d66200e22d278e03";
  }

  static const char* value(const ::px4_msgs::AirspeedValidated_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b8193ce69103723ULL;
  static const uint64_t static_value2 = 0xd66200e22d278e03ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/AirspeedValidated";
  }

  static const char* value(const ::px4_msgs::AirspeedValidated_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp				# time since system start (microseconds)\n"
"\n"
"float32 indicated_airspeed_m_s			# indicated airspeed in m/s (IAS), set to NAN if invalid\n"
"float32 calibrated_airspeed_m_s     		# calibrated airspeed in m/s (CAS, accounts for instrumentation errors), set to NAN if invalid\n"
"float32 true_airspeed_m_s			# true filtered airspeed in m/s (TAS), set to NAN if invalid\n"
"\n"
"float32 calibrated_ground_minus_wind_m_s 	# CAS calculated from groundspeed - windspeed, where windspeed is estimated based on a zero-sideslip assumption, set to NAN if invalid\n"
"float32 true_ground_minus_wind_m_s 		# TAS calculated from groundspeed - windspeed, where windspeed is estimated based on a zero-sideslip assumption, set to NAN if invalid\n"
"\n"
"bool airspeed_sensor_measurement_valid 		# True if data from at least one airspeed sensor is declared valid.\n"
"\n"
"int8 selected_airspeed_index 			# 1-3: airspeed sensor index, 0: groundspeed-windspeed, -1: airspeed invalid\n"
;
  }

  static const char* value(const ::px4_msgs::AirspeedValidated_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.indicated_airspeed_m_s);
      stream.next(m.calibrated_airspeed_m_s);
      stream.next(m.true_airspeed_m_s);
      stream.next(m.calibrated_ground_minus_wind_m_s);
      stream.next(m.true_ground_minus_wind_m_s);
      stream.next(m.airspeed_sensor_measurement_valid);
      stream.next(m.selected_airspeed_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AirspeedValidated_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::AirspeedValidated_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::AirspeedValidated_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indicated_airspeed_m_s: ";
    Printer<float>::stream(s, indent + "  ", v.indicated_airspeed_m_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "calibrated_airspeed_m_s: ";
    Printer<float>::stream(s, indent + "  ", v.calibrated_airspeed_m_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "true_airspeed_m_s: ";
    Printer<float>::stream(s, indent + "  ", v.true_airspeed_m_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "calibrated_ground_minus_wind_m_s: ";
    Printer<float>::stream(s, indent + "  ", v.calibrated_ground_minus_wind_m_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "true_ground_minus_wind_m_s: ";
    Printer<float>::stream(s, indent + "  ", v.true_ground_minus_wind_m_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "airspeed_sensor_measurement_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.airspeed_sensor_measurement_valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "selected_airspeed_index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.selected_airspeed_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_AIRSPEEDVALIDATED_H
