// Generated by gencpp from file px4_msgs/CollisionReport.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_COLLISIONREPORT_H
#define PX4_MSGS_MESSAGE_COLLISIONREPORT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct CollisionReport_
{
  typedef CollisionReport_<ContainerAllocator> Type;

  CollisionReport_()
    : timestamp(0)
    , src(0)
    , id(0)
    , action(0)
    , threat_level(0)
    , time_to_minimum_delta(0.0)
    , altitude_minimum_delta(0.0)
    , horizontal_minimum_delta(0.0)  {
    }
  CollisionReport_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , src(0)
    , id(0)
    , action(0)
    , threat_level(0)
    , time_to_minimum_delta(0.0)
    , altitude_minimum_delta(0.0)
    , horizontal_minimum_delta(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _src_type;
  _src_type src;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _action_type;
  _action_type action;

   typedef uint8_t _threat_level_type;
  _threat_level_type threat_level;

   typedef float _time_to_minimum_delta_type;
  _time_to_minimum_delta_type time_to_minimum_delta;

   typedef float _altitude_minimum_delta_type;
  _altitude_minimum_delta_type altitude_minimum_delta;

   typedef float _horizontal_minimum_delta_type;
  _horizontal_minimum_delta_type horizontal_minimum_delta;





  typedef boost::shared_ptr< ::px4_msgs::CollisionReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::CollisionReport_<ContainerAllocator> const> ConstPtr;

}; // struct CollisionReport_

typedef ::px4_msgs::CollisionReport_<std::allocator<void> > CollisionReport;

typedef boost::shared_ptr< ::px4_msgs::CollisionReport > CollisionReportPtr;
typedef boost::shared_ptr< ::px4_msgs::CollisionReport const> CollisionReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::CollisionReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::CollisionReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::CollisionReport_<ContainerAllocator1> & lhs, const ::px4_msgs::CollisionReport_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.src == rhs.src &&
    lhs.id == rhs.id &&
    lhs.action == rhs.action &&
    lhs.threat_level == rhs.threat_level &&
    lhs.time_to_minimum_delta == rhs.time_to_minimum_delta &&
    lhs.altitude_minimum_delta == rhs.altitude_minimum_delta &&
    lhs.horizontal_minimum_delta == rhs.horizontal_minimum_delta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::CollisionReport_<ContainerAllocator1> & lhs, const ::px4_msgs::CollisionReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::CollisionReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::CollisionReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::CollisionReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::CollisionReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::CollisionReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::CollisionReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::CollisionReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff0c24f7a226902f10ab6bf34f6413c5";
  }

  static const char* value(const ::px4_msgs::CollisionReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff0c24f7a226902fULL;
  static const uint64_t static_value2 = 0x10ab6bf34f6413c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::CollisionReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/CollisionReport";
  }

  static const char* value(const ::px4_msgs::CollisionReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::CollisionReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"uint8 src\n"
"uint32 id\n"
"uint8 action\n"
"uint8 threat_level\n"
"float32 time_to_minimum_delta\n"
"float32 altitude_minimum_delta\n"
"float32 horizontal_minimum_delta\n"
;
  }

  static const char* value(const ::px4_msgs::CollisionReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::CollisionReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.src);
      stream.next(m.id);
      stream.next(m.action);
      stream.next(m.threat_level);
      stream.next(m.time_to_minimum_delta);
      stream.next(m.altitude_minimum_delta);
      stream.next(m.horizontal_minimum_delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisionReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::CollisionReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::CollisionReport_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "src: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.src);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "threat_level: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.threat_level);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time_to_minimum_delta: ";
    Printer<float>::stream(s, indent + "  ", v.time_to_minimum_delta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude_minimum_delta: ";
    Printer<float>::stream(s, indent + "  ", v.altitude_minimum_delta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "horizontal_minimum_delta: ";
    Printer<float>::stream(s, indent + "  ", v.horizontal_minimum_delta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_COLLISIONREPORT_H
