// Generated by gencpp from file px4_msgs/Ekf2Timestamps.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_EKF2TIMESTAMPS_H
#define PX4_MSGS_MESSAGE_EKF2TIMESTAMPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct Ekf2Timestamps_
{
  typedef Ekf2Timestamps_<ContainerAllocator> Type;

  Ekf2Timestamps_()
    : timestamp(0)
    , airspeed_timestamp_rel(0)
    , distance_sensor_timestamp_rel(0)
    , optical_flow_timestamp_rel(0)
    , vehicle_air_data_timestamp_rel(0)
    , vehicle_magnetometer_timestamp_rel(0)
    , visual_odometry_timestamp_rel(0)  {
    }
  Ekf2Timestamps_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , airspeed_timestamp_rel(0)
    , distance_sensor_timestamp_rel(0)
    , optical_flow_timestamp_rel(0)
    , vehicle_air_data_timestamp_rel(0)
    , vehicle_magnetometer_timestamp_rel(0)
    , visual_odometry_timestamp_rel(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef int16_t _airspeed_timestamp_rel_type;
  _airspeed_timestamp_rel_type airspeed_timestamp_rel;

   typedef int16_t _distance_sensor_timestamp_rel_type;
  _distance_sensor_timestamp_rel_type distance_sensor_timestamp_rel;

   typedef int16_t _optical_flow_timestamp_rel_type;
  _optical_flow_timestamp_rel_type optical_flow_timestamp_rel;

   typedef int16_t _vehicle_air_data_timestamp_rel_type;
  _vehicle_air_data_timestamp_rel_type vehicle_air_data_timestamp_rel;

   typedef int16_t _vehicle_magnetometer_timestamp_rel_type;
  _vehicle_magnetometer_timestamp_rel_type vehicle_magnetometer_timestamp_rel;

   typedef int16_t _visual_odometry_timestamp_rel_type;
  _visual_odometry_timestamp_rel_type visual_odometry_timestamp_rel;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RELATIVE_TIMESTAMP_INVALID)
  #undef RELATIVE_TIMESTAMP_INVALID
#endif

  enum {
    RELATIVE_TIMESTAMP_INVALID = 32767,
  };


  typedef boost::shared_ptr< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> const> ConstPtr;

}; // struct Ekf2Timestamps_

typedef ::px4_msgs::Ekf2Timestamps_<std::allocator<void> > Ekf2Timestamps;

typedef boost::shared_ptr< ::px4_msgs::Ekf2Timestamps > Ekf2TimestampsPtr;
typedef boost::shared_ptr< ::px4_msgs::Ekf2Timestamps const> Ekf2TimestampsConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator1> & lhs, const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.airspeed_timestamp_rel == rhs.airspeed_timestamp_rel &&
    lhs.distance_sensor_timestamp_rel == rhs.distance_sensor_timestamp_rel &&
    lhs.optical_flow_timestamp_rel == rhs.optical_flow_timestamp_rel &&
    lhs.vehicle_air_data_timestamp_rel == rhs.vehicle_air_data_timestamp_rel &&
    lhs.vehicle_magnetometer_timestamp_rel == rhs.vehicle_magnetometer_timestamp_rel &&
    lhs.visual_odometry_timestamp_rel == rhs.visual_odometry_timestamp_rel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator1> & lhs, const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7df9725b0ad4e23ac0f31ddd76ee48e";
  }

  static const char* value(const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7df9725b0ad4e23ULL;
  static const uint64_t static_value2 = 0xac0f31ddd76ee48eULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/Ekf2Timestamps";
  }

  static const char* value(const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# this message contains the (relative) timestamps of the sensor inputs used by EKF2.\n"
"# It can be used for reproducible replay.\n"
"\n"
"# the timestamp field is the ekf2 reference time and matches the timestamp of\n"
"# the sensor_combined topic.\n"
"\n"
"uint64 timestamp			 # time since system start (microseconds)\n"
"\n"
"int16 RELATIVE_TIMESTAMP_INVALID = 32767 # (0x7fff) If one of the relative timestamps\n"
"                                         # is set to this value, it means the associated sensor values did not update\n"
"\n"
"# timestamps are relative to the main timestamp and are in 0.1 ms (timestamp +\n"
"# *_timestamp_rel = absolute timestamp). For int16, this allows a maximum\n"
"# difference of +-3.2s to the sensor_combined topic.\n"
"\n"
"int16 airspeed_timestamp_rel\n"
"int16 distance_sensor_timestamp_rel\n"
"int16 optical_flow_timestamp_rel\n"
"int16 vehicle_air_data_timestamp_rel\n"
"int16 vehicle_magnetometer_timestamp_rel\n"
"int16 visual_odometry_timestamp_rel\n"
"\n"
"# Note: this is a high-rate logged topic, so it needs to be as small as possible\n"
;
  }

  static const char* value(const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.airspeed_timestamp_rel);
      stream.next(m.distance_sensor_timestamp_rel);
      stream.next(m.optical_flow_timestamp_rel);
      stream.next(m.vehicle_air_data_timestamp_rel);
      stream.next(m.vehicle_magnetometer_timestamp_rel);
      stream.next(m.visual_odometry_timestamp_rel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ekf2Timestamps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::Ekf2Timestamps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::Ekf2Timestamps_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "airspeed_timestamp_rel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.airspeed_timestamp_rel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance_sensor_timestamp_rel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.distance_sensor_timestamp_rel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "optical_flow_timestamp_rel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.optical_flow_timestamp_rel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vehicle_air_data_timestamp_rel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vehicle_air_data_timestamp_rel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vehicle_magnetometer_timestamp_rel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vehicle_magnetometer_timestamp_rel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "visual_odometry_timestamp_rel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.visual_odometry_timestamp_rel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_EKF2TIMESTAMPS_H
