// Generated by gencpp from file px4_msgs/EstimatorInnovationVariances.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_ESTIMATORINNOVATIONVARIANCES_H
#define PX4_MSGS_MESSAGE_ESTIMATORINNOVATIONVARIANCES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct EstimatorInnovationVariances_
{
  typedef EstimatorInnovationVariances_<ContainerAllocator> Type;

  EstimatorInnovationVariances_()
    : timestamp(0)
    , timestamp_sample(0)
    , gps_hvel()
    , gps_vvel(0.0)
    , gps_hpos()
    , gps_vpos(0.0)
    , ev_hvel()
    , ev_vvel(0.0)
    , ev_hpos()
    , ev_vpos(0.0)
    , rng_vpos(0.0)
    , baro_vpos(0.0)
    , aux_hvel()
    , aux_vvel(0.0)
    , flow()
    , heading(0.0)
    , mag_field()
    , drag()
    , airspeed(0.0)
    , beta(0.0)
    , hagl(0.0)  {
      gps_hvel.assign(0.0);

      gps_hpos.assign(0.0);

      ev_hvel.assign(0.0);

      ev_hpos.assign(0.0);

      aux_hvel.assign(0.0);

      flow.assign(0.0);

      mag_field.assign(0.0);

      drag.assign(0.0);
  }
  EstimatorInnovationVariances_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , timestamp_sample(0)
    , gps_hvel()
    , gps_vvel(0.0)
    , gps_hpos()
    , gps_vpos(0.0)
    , ev_hvel()
    , ev_vvel(0.0)
    , ev_hpos()
    , ev_vpos(0.0)
    , rng_vpos(0.0)
    , baro_vpos(0.0)
    , aux_hvel()
    , aux_vvel(0.0)
    , flow()
    , heading(0.0)
    , mag_field()
    , drag()
    , airspeed(0.0)
    , beta(0.0)
    , hagl(0.0)  {
  (void)_alloc;
      gps_hvel.assign(0.0);

      gps_hpos.assign(0.0);

      ev_hvel.assign(0.0);

      ev_hpos.assign(0.0);

      aux_hvel.assign(0.0);

      flow.assign(0.0);

      mag_field.assign(0.0);

      drag.assign(0.0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _timestamp_sample_type;
  _timestamp_sample_type timestamp_sample;

   typedef boost::array<float, 2>  _gps_hvel_type;
  _gps_hvel_type gps_hvel;

   typedef float _gps_vvel_type;
  _gps_vvel_type gps_vvel;

   typedef boost::array<float, 2>  _gps_hpos_type;
  _gps_hpos_type gps_hpos;

   typedef float _gps_vpos_type;
  _gps_vpos_type gps_vpos;

   typedef boost::array<float, 2>  _ev_hvel_type;
  _ev_hvel_type ev_hvel;

   typedef float _ev_vvel_type;
  _ev_vvel_type ev_vvel;

   typedef boost::array<float, 2>  _ev_hpos_type;
  _ev_hpos_type ev_hpos;

   typedef float _ev_vpos_type;
  _ev_vpos_type ev_vpos;

   typedef float _rng_vpos_type;
  _rng_vpos_type rng_vpos;

   typedef float _baro_vpos_type;
  _baro_vpos_type baro_vpos;

   typedef boost::array<float, 2>  _aux_hvel_type;
  _aux_hvel_type aux_hvel;

   typedef float _aux_vvel_type;
  _aux_vvel_type aux_vvel;

   typedef boost::array<float, 2>  _flow_type;
  _flow_type flow;

   typedef float _heading_type;
  _heading_type heading;

   typedef boost::array<float, 3>  _mag_field_type;
  _mag_field_type mag_field;

   typedef boost::array<float, 2>  _drag_type;
  _drag_type drag;

   typedef float _airspeed_type;
  _airspeed_type airspeed;

   typedef float _beta_type;
  _beta_type beta;

   typedef float _hagl_type;
  _hagl_type hagl;





  typedef boost::shared_ptr< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> const> ConstPtr;

}; // struct EstimatorInnovationVariances_

typedef ::px4_msgs::EstimatorInnovationVariances_<std::allocator<void> > EstimatorInnovationVariances;

typedef boost::shared_ptr< ::px4_msgs::EstimatorInnovationVariances > EstimatorInnovationVariancesPtr;
typedef boost::shared_ptr< ::px4_msgs::EstimatorInnovationVariances const> EstimatorInnovationVariancesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator1> & lhs, const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.timestamp_sample == rhs.timestamp_sample &&
    lhs.gps_hvel == rhs.gps_hvel &&
    lhs.gps_vvel == rhs.gps_vvel &&
    lhs.gps_hpos == rhs.gps_hpos &&
    lhs.gps_vpos == rhs.gps_vpos &&
    lhs.ev_hvel == rhs.ev_hvel &&
    lhs.ev_vvel == rhs.ev_vvel &&
    lhs.ev_hpos == rhs.ev_hpos &&
    lhs.ev_vpos == rhs.ev_vpos &&
    lhs.rng_vpos == rhs.rng_vpos &&
    lhs.baro_vpos == rhs.baro_vpos &&
    lhs.aux_hvel == rhs.aux_hvel &&
    lhs.aux_vvel == rhs.aux_vvel &&
    lhs.flow == rhs.flow &&
    lhs.heading == rhs.heading &&
    lhs.mag_field == rhs.mag_field &&
    lhs.drag == rhs.drag &&
    lhs.airspeed == rhs.airspeed &&
    lhs.beta == rhs.beta &&
    lhs.hagl == rhs.hagl;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator1> & lhs, const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b9b2ca46042fb55c24b069a381dbf48";
  }

  static const char* value(const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b9b2ca46042fb55ULL;
  static const uint64_t static_value2 = 0xc24b069a381dbf48ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/EstimatorInnovationVariances";
  }

  static const char* value(const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"uint64 timestamp_sample         # the timestamp of the raw data (microseconds)\n"
"\n"
"# GPS\n"
"float32[2] gps_hvel	# horizontal GPS velocity innovation (m/sec) and innovation variance ((m/sec)**2)\n"
"float32    gps_vvel	# vertical GPS velocity innovation (m/sec) and innovation variance ((m/sec)**2)\n"
"float32[2] gps_hpos	# horizontal GPS position innovation (m) and innovation variance (m**2)\n"
"float32    gps_vpos	# vertical GPS position innovation (m) and innovation variance (m**2)\n"
"\n"
"# External Vision\n"
"float32[2] ev_hvel	# horizontal external vision velocity innovation (m/sec) and innovation variance ((m/sec)**2)\n"
"float32    ev_vvel	# vertical external vision velocity innovation (m/sec) and innovation variance ((m/sec)**2)\n"
"float32[2] ev_hpos	# horizontal external vision position innovation (m) and innovation variance (m**2)\n"
"float32    ev_vpos	# vertical external vision position innovation (m) and innovation variance (m**2)\n"
"\n"
"# Height sensors\n"
"float32 rng_vpos	# range sensor height innovation (m) and innovation variance (m**2)\n"
"float32 baro_vpos	# barometer height innovation (m) and innovation variance (m**2)\n"
"\n"
"# Auxiliary velocity\n"
"float32[2] aux_hvel	# horizontal auxiliar velocity innovation from landing target measurement (m/sec) and innovation variance ((m/sec)**2)\n"
"float32    aux_vvel	# vertical auxiliar velocity innovation from landing target measurement (m/sec) and innovation variance ((m/sec)**2)\n"
"\n"
"# Optical flow\n"
"float32[2] flow		# flow innvoation (rad/sec) and innovation variance ((rad/sec)**2)\n"
"\n"
"# Various\n"
"float32 heading		# heading innovation (rad) and innovation variance (rad**2)\n"
"float32[3] mag_field	# earth magnetic field innovation (Gauss) and innovation variance (Gauss**2)\n"
"float32[2] drag		# drag specific force innovation (m/sec**2) and innovation variance ((m/sec)**2)\n"
"float32 airspeed	# airspeed innovation (m/sec) and innovation variance ((m/sec)**2)\n"
"float32 beta		# synthetic sideslip innovation (rad) and innovation variance (rad**2)\n"
"float32 hagl		# height of ground innovation (m) and innovation variance (m**2)\n"
"\n"
"# The innovation test ratios are scalar values. In case the field is a vector,\n"
"# the test ratio will be put in the first component of the vector.\n"
"\n"
;
  }

  static const char* value(const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.timestamp_sample);
      stream.next(m.gps_hvel);
      stream.next(m.gps_vvel);
      stream.next(m.gps_hpos);
      stream.next(m.gps_vpos);
      stream.next(m.ev_hvel);
      stream.next(m.ev_vvel);
      stream.next(m.ev_hpos);
      stream.next(m.ev_vpos);
      stream.next(m.rng_vpos);
      stream.next(m.baro_vpos);
      stream.next(m.aux_hvel);
      stream.next(m.aux_vvel);
      stream.next(m.flow);
      stream.next(m.heading);
      stream.next(m.mag_field);
      stream.next(m.drag);
      stream.next(m.airspeed);
      stream.next(m.beta);
      stream.next(m.hagl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstimatorInnovationVariances_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::EstimatorInnovationVariances_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_hvel: ";
    if (v.gps_hvel.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.gps_hvel.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.gps_hvel[i]);
    }
    if (v.gps_hvel.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_vvel: ";
    Printer<float>::stream(s, indent + "  ", v.gps_vvel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_hpos: ";
    if (v.gps_hpos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.gps_hpos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.gps_hpos[i]);
    }
    if (v.gps_hpos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_vpos: ";
    Printer<float>::stream(s, indent + "  ", v.gps_vpos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ev_hvel: ";
    if (v.ev_hvel.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ev_hvel.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.ev_hvel[i]);
    }
    if (v.ev_hvel.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ev_vvel: ";
    Printer<float>::stream(s, indent + "  ", v.ev_vvel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ev_hpos: ";
    if (v.ev_hpos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ev_hpos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.ev_hpos[i]);
    }
    if (v.ev_hpos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ev_vpos: ";
    Printer<float>::stream(s, indent + "  ", v.ev_vpos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rng_vpos: ";
    Printer<float>::stream(s, indent + "  ", v.rng_vpos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baro_vpos: ";
    Printer<float>::stream(s, indent + "  ", v.baro_vpos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aux_hvel: ";
    if (v.aux_hvel.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.aux_hvel.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.aux_hvel[i]);
    }
    if (v.aux_hvel.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aux_vvel: ";
    Printer<float>::stream(s, indent + "  ", v.aux_vvel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flow: ";
    if (v.flow.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.flow.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.flow[i]);
    }
    if (v.flow.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_field: ";
    if (v.mag_field.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mag_field.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.mag_field[i]);
    }
    if (v.mag_field.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drag: ";
    if (v.drag.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drag.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.drag[i]);
    }
    if (v.drag.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "airspeed: ";
    Printer<float>::stream(s, indent + "  ", v.airspeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "beta: ";
    Printer<float>::stream(s, indent + "  ", v.beta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hagl: ";
    Printer<float>::stream(s, indent + "  ", v.hagl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_ESTIMATORINNOVATIONVARIANCES_H
