// Generated by gencpp from file px4_msgs/EstimatorSelectorStatus.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_ESTIMATORSELECTORSTATUS_H
#define PX4_MSGS_MESSAGE_ESTIMATORSELECTORSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct EstimatorSelectorStatus_
{
  typedef EstimatorSelectorStatus_<ContainerAllocator> Type;

  EstimatorSelectorStatus_()
    : timestamp(0)
    , primary_instance(0)
    , instances_available(0)
    , instance_changed_count(0)
    , last_instance_change(0)
    , accel_device_id(0)
    , baro_device_id(0)
    , gyro_device_id(0)
    , mag_device_id(0)
    , combined_test_ratio()
    , relative_test_ratio()
    , healthy()
    , accumulated_gyro_error()
    , accumulated_accel_error()
    , gyro_fault_detected(false)
    , accel_fault_detected(false)  {
      combined_test_ratio.assign(0.0);

      relative_test_ratio.assign(0.0);

      healthy.assign(false);

      accumulated_gyro_error.assign(0.0);

      accumulated_accel_error.assign(0.0);
  }
  EstimatorSelectorStatus_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , primary_instance(0)
    , instances_available(0)
    , instance_changed_count(0)
    , last_instance_change(0)
    , accel_device_id(0)
    , baro_device_id(0)
    , gyro_device_id(0)
    , mag_device_id(0)
    , combined_test_ratio()
    , relative_test_ratio()
    , healthy()
    , accumulated_gyro_error()
    , accumulated_accel_error()
    , gyro_fault_detected(false)
    , accel_fault_detected(false)  {
  (void)_alloc;
      combined_test_ratio.assign(0.0);

      relative_test_ratio.assign(0.0);

      healthy.assign(false);

      accumulated_gyro_error.assign(0.0);

      accumulated_accel_error.assign(0.0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _primary_instance_type;
  _primary_instance_type primary_instance;

   typedef uint8_t _instances_available_type;
  _instances_available_type instances_available;

   typedef uint32_t _instance_changed_count_type;
  _instance_changed_count_type instance_changed_count;

   typedef uint64_t _last_instance_change_type;
  _last_instance_change_type last_instance_change;

   typedef uint32_t _accel_device_id_type;
  _accel_device_id_type accel_device_id;

   typedef uint32_t _baro_device_id_type;
  _baro_device_id_type baro_device_id;

   typedef uint32_t _gyro_device_id_type;
  _gyro_device_id_type gyro_device_id;

   typedef uint32_t _mag_device_id_type;
  _mag_device_id_type mag_device_id;

   typedef boost::array<float, 9>  _combined_test_ratio_type;
  _combined_test_ratio_type combined_test_ratio;

   typedef boost::array<float, 9>  _relative_test_ratio_type;
  _relative_test_ratio_type relative_test_ratio;

   typedef boost::array<uint8_t, 9>  _healthy_type;
  _healthy_type healthy;

   typedef boost::array<float, 4>  _accumulated_gyro_error_type;
  _accumulated_gyro_error_type accumulated_gyro_error;

   typedef boost::array<float, 4>  _accumulated_accel_error_type;
  _accumulated_accel_error_type accumulated_accel_error;

   typedef uint8_t _gyro_fault_detected_type;
  _gyro_fault_detected_type gyro_fault_detected;

   typedef uint8_t _accel_fault_detected_type;
  _accel_fault_detected_type accel_fault_detected;





  typedef boost::shared_ptr< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> const> ConstPtr;

}; // struct EstimatorSelectorStatus_

typedef ::px4_msgs::EstimatorSelectorStatus_<std::allocator<void> > EstimatorSelectorStatus;

typedef boost::shared_ptr< ::px4_msgs::EstimatorSelectorStatus > EstimatorSelectorStatusPtr;
typedef boost::shared_ptr< ::px4_msgs::EstimatorSelectorStatus const> EstimatorSelectorStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator1> & lhs, const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.primary_instance == rhs.primary_instance &&
    lhs.instances_available == rhs.instances_available &&
    lhs.instance_changed_count == rhs.instance_changed_count &&
    lhs.last_instance_change == rhs.last_instance_change &&
    lhs.accel_device_id == rhs.accel_device_id &&
    lhs.baro_device_id == rhs.baro_device_id &&
    lhs.gyro_device_id == rhs.gyro_device_id &&
    lhs.mag_device_id == rhs.mag_device_id &&
    lhs.combined_test_ratio == rhs.combined_test_ratio &&
    lhs.relative_test_ratio == rhs.relative_test_ratio &&
    lhs.healthy == rhs.healthy &&
    lhs.accumulated_gyro_error == rhs.accumulated_gyro_error &&
    lhs.accumulated_accel_error == rhs.accumulated_accel_error &&
    lhs.gyro_fault_detected == rhs.gyro_fault_detected &&
    lhs.accel_fault_detected == rhs.accel_fault_detected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator1> & lhs, const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ae088bea6d5216063c38185b1806568";
  }

  static const char* value(const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ae088bea6d52160ULL;
  static const uint64_t static_value2 = 0x63c38185b1806568ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/EstimatorSelectorStatus";
  }

  static const char* value(const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"\n"
"uint8 primary_instance\n"
"\n"
"uint8 instances_available\n"
"\n"
"uint32 instance_changed_count\n"
"uint64 last_instance_change\n"
"\n"
"uint32 accel_device_id\n"
"uint32 baro_device_id\n"
"uint32 gyro_device_id\n"
"uint32 mag_device_id\n"
"\n"
"float32[9] combined_test_ratio\n"
"float32[9] relative_test_ratio\n"
"bool[9] healthy\n"
"\n"
"float32[4] accumulated_gyro_error\n"
"float32[4] accumulated_accel_error\n"
"bool gyro_fault_detected\n"
"bool accel_fault_detected\n"
;
  }

  static const char* value(const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.primary_instance);
      stream.next(m.instances_available);
      stream.next(m.instance_changed_count);
      stream.next(m.last_instance_change);
      stream.next(m.accel_device_id);
      stream.next(m.baro_device_id);
      stream.next(m.gyro_device_id);
      stream.next(m.mag_device_id);
      stream.next(m.combined_test_ratio);
      stream.next(m.relative_test_ratio);
      stream.next(m.healthy);
      stream.next(m.accumulated_gyro_error);
      stream.next(m.accumulated_accel_error);
      stream.next(m.gyro_fault_detected);
      stream.next(m.accel_fault_detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstimatorSelectorStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::EstimatorSelectorStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "primary_instance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.primary_instance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "instances_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.instances_available);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "instance_changed_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.instance_changed_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "last_instance_change: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.last_instance_change);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel_device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.accel_device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baro_device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.baro_device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyro_device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gyro_device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mag_device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mag_device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "combined_test_ratio: ";
    if (v.combined_test_ratio.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.combined_test_ratio.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.combined_test_ratio[i]);
    }
    if (v.combined_test_ratio.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "relative_test_ratio: ";
    if (v.relative_test_ratio.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.relative_test_ratio.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.relative_test_ratio[i]);
    }
    if (v.relative_test_ratio.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "healthy: ";
    if (v.healthy.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.healthy.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.healthy[i]);
    }
    if (v.healthy.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accumulated_gyro_error: ";
    if (v.accumulated_gyro_error.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.accumulated_gyro_error.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.accumulated_gyro_error[i]);
    }
    if (v.accumulated_gyro_error.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accumulated_accel_error: ";
    if (v.accumulated_accel_error.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.accumulated_accel_error.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.accumulated_accel_error[i]);
    }
    if (v.accumulated_accel_error.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyro_fault_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gyro_fault_detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel_fault_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accel_fault_detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_ESTIMATORSELECTORSTATUS_H
