// Generated by gencpp from file px4_msgs/GimbalManagerStatus.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_GIMBALMANAGERSTATUS_H
#define PX4_MSGS_MESSAGE_GIMBALMANAGERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct GimbalManagerStatus_
{
  typedef GimbalManagerStatus_<ContainerAllocator> Type;

  GimbalManagerStatus_()
    : timestamp(0)
    , flags(0)
    , gimbal_device_id(0)
    , primary_control_sysid(0)
    , primary_control_compid(0)
    , secondary_control_sysid(0)
    , secondary_control_compid(0)  {
    }
  GimbalManagerStatus_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , flags(0)
    , gimbal_device_id(0)
    , primary_control_sysid(0)
    , primary_control_compid(0)
    , secondary_control_sysid(0)
    , secondary_control_compid(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _flags_type;
  _flags_type flags;

   typedef uint8_t _gimbal_device_id_type;
  _gimbal_device_id_type gimbal_device_id;

   typedef uint8_t _primary_control_sysid_type;
  _primary_control_sysid_type primary_control_sysid;

   typedef uint8_t _primary_control_compid_type;
  _primary_control_compid_type primary_control_compid;

   typedef uint8_t _secondary_control_sysid_type;
  _secondary_control_sysid_type secondary_control_sysid;

   typedef uint8_t _secondary_control_compid_type;
  _secondary_control_compid_type secondary_control_compid;





  typedef boost::shared_ptr< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalManagerStatus_

typedef ::px4_msgs::GimbalManagerStatus_<std::allocator<void> > GimbalManagerStatus;

typedef boost::shared_ptr< ::px4_msgs::GimbalManagerStatus > GimbalManagerStatusPtr;
typedef boost::shared_ptr< ::px4_msgs::GimbalManagerStatus const> GimbalManagerStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator1> & lhs, const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.flags == rhs.flags &&
    lhs.gimbal_device_id == rhs.gimbal_device_id &&
    lhs.primary_control_sysid == rhs.primary_control_sysid &&
    lhs.primary_control_compid == rhs.primary_control_compid &&
    lhs.secondary_control_sysid == rhs.secondary_control_sysid &&
    lhs.secondary_control_compid == rhs.secondary_control_compid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator1> & lhs, const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2f006395e0a42a367d2a8426e7c3302";
  }

  static const char* value(const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2f006395e0a42a3ULL;
  static const uint64_t static_value2 = 0x67d2a8426e7c3302ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/GimbalManagerStatus";
  }

  static const char* value(const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"\n"
"uint32 flags\n"
"uint8 gimbal_device_id\n"
"uint8 primary_control_sysid\n"
"uint8 primary_control_compid\n"
"uint8 secondary_control_sysid\n"
"uint8 secondary_control_compid\n"
;
  }

  static const char* value(const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.flags);
      stream.next(m.gimbal_device_id);
      stream.next(m.primary_control_sysid);
      stream.next(m.primary_control_compid);
      stream.next(m.secondary_control_sysid);
      stream.next(m.secondary_control_compid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalManagerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::GimbalManagerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::GimbalManagerStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flags: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.flags);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gimbal_device_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gimbal_device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "primary_control_sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.primary_control_sysid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "primary_control_compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.primary_control_compid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "secondary_control_sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.secondary_control_sysid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "secondary_control_compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.secondary_control_compid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_GIMBALMANAGERSTATUS_H
