// Generated by gencpp from file px4_msgs/GpsDump.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_GPSDUMP_H
#define PX4_MSGS_MESSAGE_GPSDUMP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct GpsDump_
{
  typedef GpsDump_<ContainerAllocator> Type;

  GpsDump_()
    : timestamp(0)
    , instance(0)
    , len(0)
    , data()  {
      data.assign(0);
  }
  GpsDump_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , instance(0)
    , len(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _instance_type;
  _instance_type instance;

   typedef uint8_t _len_type;
  _len_type len;

   typedef boost::array<uint8_t, 79>  _data_type;
  _data_type data;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ORB_QUEUE_LENGTH)
  #undef ORB_QUEUE_LENGTH
#endif

  enum {
    ORB_QUEUE_LENGTH = 8u,
  };


  typedef boost::shared_ptr< ::px4_msgs::GpsDump_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::GpsDump_<ContainerAllocator> const> ConstPtr;

}; // struct GpsDump_

typedef ::px4_msgs::GpsDump_<std::allocator<void> > GpsDump;

typedef boost::shared_ptr< ::px4_msgs::GpsDump > GpsDumpPtr;
typedef boost::shared_ptr< ::px4_msgs::GpsDump const> GpsDumpConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::GpsDump_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::GpsDump_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::GpsDump_<ContainerAllocator1> & lhs, const ::px4_msgs::GpsDump_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.instance == rhs.instance &&
    lhs.len == rhs.len &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::GpsDump_<ContainerAllocator1> & lhs, const ::px4_msgs::GpsDump_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::GpsDump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::GpsDump_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::GpsDump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::GpsDump_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::GpsDump_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::GpsDump_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::GpsDump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccc555c521e9bd182480557af92fcb23";
  }

  static const char* value(const ::px4_msgs::GpsDump_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccc555c521e9bd18ULL;
  static const uint64_t static_value2 = 0x2480557af92fcb23ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::GpsDump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/GpsDump";
  }

  static const char* value(const ::px4_msgs::GpsDump_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::GpsDump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message is used to dump the raw gps communication to the log.\n"
"# Set the parameter GPS_DUMP_COMM to 1 to use this.\n"
"\n"
"uint64 timestamp		# time since system start (microseconds)\n"
"\n"
"uint8 instance 		# Instance of GNSS reciever\n"
"\n"
"uint8 len			# length of data, MSB bit set = message to the gps device,\n"
"				# clear = message from the device\n"
"uint8[79] data		# data to write to the log\n"
"\n"
"uint8 ORB_QUEUE_LENGTH = 8\n"
;
  }

  static const char* value(const ::px4_msgs::GpsDump_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::GpsDump_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.instance);
      stream.next(m.len);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsDump_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::GpsDump_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::GpsDump_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "instance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.instance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_GPSDUMP_H
