// Generated by gencpp from file px4_msgs/GpsInjectData.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_GPSINJECTDATA_H
#define PX4_MSGS_MESSAGE_GPSINJECTDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct GpsInjectData_
{
  typedef GpsInjectData_<ContainerAllocator> Type;

  GpsInjectData_()
    : timestamp(0)
    , len(0)
    , flags(0)
    , data()  {
      data.assign(0);
  }
  GpsInjectData_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , len(0)
    , flags(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _len_type;
  _len_type len;

   typedef uint8_t _flags_type;
  _flags_type flags;

   typedef boost::array<uint8_t, 182>  _data_type;
  _data_type data;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ORB_QUEUE_LENGTH)
  #undef ORB_QUEUE_LENGTH
#endif

  enum {
    ORB_QUEUE_LENGTH = 8u,
  };


  typedef boost::shared_ptr< ::px4_msgs::GpsInjectData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::GpsInjectData_<ContainerAllocator> const> ConstPtr;

}; // struct GpsInjectData_

typedef ::px4_msgs::GpsInjectData_<std::allocator<void> > GpsInjectData;

typedef boost::shared_ptr< ::px4_msgs::GpsInjectData > GpsInjectDataPtr;
typedef boost::shared_ptr< ::px4_msgs::GpsInjectData const> GpsInjectDataConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::GpsInjectData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::GpsInjectData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::GpsInjectData_<ContainerAllocator1> & lhs, const ::px4_msgs::GpsInjectData_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.len == rhs.len &&
    lhs.flags == rhs.flags &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::GpsInjectData_<ContainerAllocator1> & lhs, const ::px4_msgs::GpsInjectData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::GpsInjectData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::GpsInjectData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::GpsInjectData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e30b94213a1a8192ae98147ac355fce";
  }

  static const char* value(const ::px4_msgs::GpsInjectData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e30b94213a1a819ULL;
  static const uint64_t static_value2 = 0x2ae98147ac355fceULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/GpsInjectData";
  }

  static const char* value(const ::px4_msgs::GpsInjectData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"uint8 len			# length of data\n"
"uint8 flags         		# LSB: 1=fragmented\n"
"uint8[182] data		# data to write to GPS device (RTCM message)\n"
"\n"
"uint8 ORB_QUEUE_LENGTH = 8\n"
;
  }

  static const char* value(const ::px4_msgs::GpsInjectData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.len);
      stream.next(m.flags);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsInjectData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::GpsInjectData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::GpsInjectData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_GPSINJECTDATA_H
