// Generated by gencpp from file px4_msgs/InternalCombustionEngineStatus.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_INTERNALCOMBUSTIONENGINESTATUS_H
#define PX4_MSGS_MESSAGE_INTERNALCOMBUSTIONENGINESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct InternalCombustionEngineStatus_
{
  typedef InternalCombustionEngineStatus_<ContainerAllocator> Type;

  InternalCombustionEngineStatus_()
    : timestamp(0)
    , state(0)
    , flags(0)
    , engine_load_percent(0)
    , engine_speed_rpm(0)
    , spark_dwell_time_ms(0.0)
    , atmospheric_pressure_kpa(0.0)
    , intake_manifold_pressure_kpa(0.0)
    , intake_manifold_temperature(0.0)
    , coolant_temperature(0.0)
    , oil_pressure(0.0)
    , oil_temperature(0.0)
    , fuel_pressure(0.0)
    , fuel_consumption_rate_cm3pm(0.0)
    , estimated_consumed_fuel_volume_cm3(0.0)
    , throttle_position_percent(0)
    , ecu_index(0)
    , spark_plug_usage(0)
    , ignition_timing_deg(0.0)
    , injection_time_ms(0.0)
    , cylinder_head_temperature(0.0)
    , exhaust_gas_temperature(0.0)
    , lambda_coefficient(0.0)  {
    }
  InternalCombustionEngineStatus_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , state(0)
    , flags(0)
    , engine_load_percent(0)
    , engine_speed_rpm(0)
    , spark_dwell_time_ms(0.0)
    , atmospheric_pressure_kpa(0.0)
    , intake_manifold_pressure_kpa(0.0)
    , intake_manifold_temperature(0.0)
    , coolant_temperature(0.0)
    , oil_pressure(0.0)
    , oil_temperature(0.0)
    , fuel_pressure(0.0)
    , fuel_consumption_rate_cm3pm(0.0)
    , estimated_consumed_fuel_volume_cm3(0.0)
    , throttle_position_percent(0)
    , ecu_index(0)
    , spark_plug_usage(0)
    , ignition_timing_deg(0.0)
    , injection_time_ms(0.0)
    , cylinder_head_temperature(0.0)
    , exhaust_gas_temperature(0.0)
    , lambda_coefficient(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint32_t _flags_type;
  _flags_type flags;

   typedef uint8_t _engine_load_percent_type;
  _engine_load_percent_type engine_load_percent;

   typedef uint32_t _engine_speed_rpm_type;
  _engine_speed_rpm_type engine_speed_rpm;

   typedef float _spark_dwell_time_ms_type;
  _spark_dwell_time_ms_type spark_dwell_time_ms;

   typedef float _atmospheric_pressure_kpa_type;
  _atmospheric_pressure_kpa_type atmospheric_pressure_kpa;

   typedef float _intake_manifold_pressure_kpa_type;
  _intake_manifold_pressure_kpa_type intake_manifold_pressure_kpa;

   typedef float _intake_manifold_temperature_type;
  _intake_manifold_temperature_type intake_manifold_temperature;

   typedef float _coolant_temperature_type;
  _coolant_temperature_type coolant_temperature;

   typedef float _oil_pressure_type;
  _oil_pressure_type oil_pressure;

   typedef float _oil_temperature_type;
  _oil_temperature_type oil_temperature;

   typedef float _fuel_pressure_type;
  _fuel_pressure_type fuel_pressure;

   typedef float _fuel_consumption_rate_cm3pm_type;
  _fuel_consumption_rate_cm3pm_type fuel_consumption_rate_cm3pm;

   typedef float _estimated_consumed_fuel_volume_cm3_type;
  _estimated_consumed_fuel_volume_cm3_type estimated_consumed_fuel_volume_cm3;

   typedef uint8_t _throttle_position_percent_type;
  _throttle_position_percent_type throttle_position_percent;

   typedef uint8_t _ecu_index_type;
  _ecu_index_type ecu_index;

   typedef uint8_t _spark_plug_usage_type;
  _spark_plug_usage_type spark_plug_usage;

   typedef float _ignition_timing_deg_type;
  _ignition_timing_deg_type ignition_timing_deg;

   typedef float _injection_time_ms_type;
  _injection_time_ms_type injection_time_ms;

   typedef float _cylinder_head_temperature_type;
  _cylinder_head_temperature_type cylinder_head_temperature;

   typedef float _exhaust_gas_temperature_type;
  _exhaust_gas_temperature_type exhaust_gas_temperature;

   typedef float _lambda_coefficient_type;
  _lambda_coefficient_type lambda_coefficient;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_STOPPED)
  #undef STATE_STOPPED
#endif
#if defined(_WIN32) && defined(STATE_STARTING)
  #undef STATE_STARTING
#endif
#if defined(_WIN32) && defined(STATE_RUNNING)
  #undef STATE_RUNNING
#endif
#if defined(_WIN32) && defined(STATE_FAULT)
  #undef STATE_FAULT
#endif
#if defined(_WIN32) && defined(FLAG_GENERAL_ERROR)
  #undef FLAG_GENERAL_ERROR
#endif
#if defined(_WIN32) && defined(FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED)
  #undef FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_CRANKSHAFT_SENSOR_ERROR)
  #undef FLAG_CRANKSHAFT_SENSOR_ERROR
#endif
#if defined(_WIN32) && defined(FLAG_TEMPERATURE_SUPPORTED)
  #undef FLAG_TEMPERATURE_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_TEMPERATURE_BELOW_NOMINAL)
  #undef FLAG_TEMPERATURE_BELOW_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_TEMPERATURE_ABOVE_NOMINAL)
  #undef FLAG_TEMPERATURE_ABOVE_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_TEMPERATURE_OVERHEATING)
  #undef FLAG_TEMPERATURE_OVERHEATING
#endif
#if defined(_WIN32) && defined(FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL)
  #undef FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_FUEL_PRESSURE_SUPPORTED)
  #undef FLAG_FUEL_PRESSURE_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_FUEL_PRESSURE_BELOW_NOMINAL)
  #undef FLAG_FUEL_PRESSURE_BELOW_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_FUEL_PRESSURE_ABOVE_NOMINAL)
  #undef FLAG_FUEL_PRESSURE_ABOVE_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_DETONATION_SUPPORTED)
  #undef FLAG_DETONATION_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_DETONATION_OBSERVED)
  #undef FLAG_DETONATION_OBSERVED
#endif
#if defined(_WIN32) && defined(FLAG_MISFIRE_SUPPORTED)
  #undef FLAG_MISFIRE_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_MISFIRE_OBSERVED)
  #undef FLAG_MISFIRE_OBSERVED
#endif
#if defined(_WIN32) && defined(FLAG_OIL_PRESSURE_SUPPORTED)
  #undef FLAG_OIL_PRESSURE_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_OIL_PRESSURE_BELOW_NOMINAL)
  #undef FLAG_OIL_PRESSURE_BELOW_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_OIL_PRESSURE_ABOVE_NOMINAL)
  #undef FLAG_OIL_PRESSURE_ABOVE_NOMINAL
#endif
#if defined(_WIN32) && defined(FLAG_DEBRIS_SUPPORTED)
  #undef FLAG_DEBRIS_SUPPORTED
#endif
#if defined(_WIN32) && defined(FLAG_DEBRIS_DETECTED)
  #undef FLAG_DEBRIS_DETECTED
#endif
#if defined(_WIN32) && defined(SPARK_PLUG_SINGLE)
  #undef SPARK_PLUG_SINGLE
#endif
#if defined(_WIN32) && defined(SPARK_PLUG_FIRST_ACTIVE)
  #undef SPARK_PLUG_FIRST_ACTIVE
#endif
#if defined(_WIN32) && defined(SPARK_PLUG_SECOND_ACTIVE)
  #undef SPARK_PLUG_SECOND_ACTIVE
#endif
#if defined(_WIN32) && defined(SPARK_PLUG_BOTH_ACTIVE)
  #undef SPARK_PLUG_BOTH_ACTIVE
#endif

  enum {
    STATE_STOPPED = 0u,
    STATE_STARTING = 1u,
    STATE_RUNNING = 2u,
    STATE_FAULT = 3u,
    FLAG_GENERAL_ERROR = 1u,
    FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED = 2u,
    FLAG_CRANKSHAFT_SENSOR_ERROR = 4u,
    FLAG_TEMPERATURE_SUPPORTED = 8u,
    FLAG_TEMPERATURE_BELOW_NOMINAL = 16u,
    FLAG_TEMPERATURE_ABOVE_NOMINAL = 32u,
    FLAG_TEMPERATURE_OVERHEATING = 64u,
    FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL = 128u,
    FLAG_FUEL_PRESSURE_SUPPORTED = 256u,
    FLAG_FUEL_PRESSURE_BELOW_NOMINAL = 512u,
    FLAG_FUEL_PRESSURE_ABOVE_NOMINAL = 1024u,
    FLAG_DETONATION_SUPPORTED = 2048u,
    FLAG_DETONATION_OBSERVED = 4096u,
    FLAG_MISFIRE_SUPPORTED = 8192u,
    FLAG_MISFIRE_OBSERVED = 16384u,
    FLAG_OIL_PRESSURE_SUPPORTED = 32768u,
    FLAG_OIL_PRESSURE_BELOW_NOMINAL = 65536u,
    FLAG_OIL_PRESSURE_ABOVE_NOMINAL = 131072u,
    FLAG_DEBRIS_SUPPORTED = 262144u,
    FLAG_DEBRIS_DETECTED = 524288u,
    SPARK_PLUG_SINGLE = 0u,
    SPARK_PLUG_FIRST_ACTIVE = 1u,
    SPARK_PLUG_SECOND_ACTIVE = 2u,
    SPARK_PLUG_BOTH_ACTIVE = 3u,
  };


  typedef boost::shared_ptr< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> const> ConstPtr;

}; // struct InternalCombustionEngineStatus_

typedef ::px4_msgs::InternalCombustionEngineStatus_<std::allocator<void> > InternalCombustionEngineStatus;

typedef boost::shared_ptr< ::px4_msgs::InternalCombustionEngineStatus > InternalCombustionEngineStatusPtr;
typedef boost::shared_ptr< ::px4_msgs::InternalCombustionEngineStatus const> InternalCombustionEngineStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator1> & lhs, const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.state == rhs.state &&
    lhs.flags == rhs.flags &&
    lhs.engine_load_percent == rhs.engine_load_percent &&
    lhs.engine_speed_rpm == rhs.engine_speed_rpm &&
    lhs.spark_dwell_time_ms == rhs.spark_dwell_time_ms &&
    lhs.atmospheric_pressure_kpa == rhs.atmospheric_pressure_kpa &&
    lhs.intake_manifold_pressure_kpa == rhs.intake_manifold_pressure_kpa &&
    lhs.intake_manifold_temperature == rhs.intake_manifold_temperature &&
    lhs.coolant_temperature == rhs.coolant_temperature &&
    lhs.oil_pressure == rhs.oil_pressure &&
    lhs.oil_temperature == rhs.oil_temperature &&
    lhs.fuel_pressure == rhs.fuel_pressure &&
    lhs.fuel_consumption_rate_cm3pm == rhs.fuel_consumption_rate_cm3pm &&
    lhs.estimated_consumed_fuel_volume_cm3 == rhs.estimated_consumed_fuel_volume_cm3 &&
    lhs.throttle_position_percent == rhs.throttle_position_percent &&
    lhs.ecu_index == rhs.ecu_index &&
    lhs.spark_plug_usage == rhs.spark_plug_usage &&
    lhs.ignition_timing_deg == rhs.ignition_timing_deg &&
    lhs.injection_time_ms == rhs.injection_time_ms &&
    lhs.cylinder_head_temperature == rhs.cylinder_head_temperature &&
    lhs.exhaust_gas_temperature == rhs.exhaust_gas_temperature &&
    lhs.lambda_coefficient == rhs.lambda_coefficient;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator1> & lhs, const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e481f1d52e0c26ea2e7f6f878ee83a0";
  }

  static const char* value(const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e481f1d52e0c26eULL;
  static const uint64_t static_value2 = 0xa2e7f6f878ee83a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/InternalCombustionEngineStatus";
  }

  static const char* value(const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp					# time since system start (microseconds)\n"
"\n"
"uint8 STATE_STOPPED = 0					# The engine is not running. This is the default state.\n"
"uint8 STATE_STARTING = 1				# The engine is starting. This is a transient state.\n"
"uint8 STATE_RUNNING = 2					# The engine is running normally.\n"
"uint8 STATE_FAULT = 3					# The engine can no longer function.\n"
"uint8 state\n"
"\n"
"uint32 FLAG_GENERAL_ERROR = 1				# General error.\n"
"\n"
"uint32 FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED = 2	# Error of the crankshaft sensor. This flag is optional.\n"
"uint32 FLAG_CRANKSHAFT_SENSOR_ERROR = 4\n"
"\n"
"uint32 FLAG_TEMPERATURE_SUPPORTED = 8			# Temperature levels. These flags are optional\n"
"uint32 FLAG_TEMPERATURE_BELOW_NOMINAL = 16      	# Under-temperature warning\n"
"uint32 FLAG_TEMPERATURE_ABOVE_NOMINAL = 32      	# Over-temperature warning\n"
"uint32 FLAG_TEMPERATURE_OVERHEATING = 64      		# Critical overheating\n"
"uint32 FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL = 128     	# Exhaust gas over-temperature warning\n"
"\n"
"uint32 FLAG_FUEL_PRESSURE_SUPPORTED = 256		# Fuel pressure. These flags are optional\n"
"uint32 FLAG_FUEL_PRESSURE_BELOW_NOMINAL  = 512     	# Under-pressure warning\n"
"uint32 FLAG_FUEL_PRESSURE_ABOVE_NOMINAL = 1024   	# Over-pressure warning\n"
"\n"
"uint32 FLAG_DETONATION_SUPPORTED = 2048			# Detonation warning. This flag is optional.\n"
"uint32 FLAG_DETONATION_OBSERVED = 4096    		# Detonation condition observed warning\n"
"\n"
"uint32 FLAG_MISFIRE_SUPPORTED = 8192			# Misfire warning. This flag is optional.\n"
"uint32 FLAG_MISFIRE_OBSERVED = 16384   			# Misfire condition observed warning\n"
"\n"
"uint32 FLAG_OIL_PRESSURE_SUPPORTED = 32768		# Oil pressure. These flags are optional\n"
"uint32 FLAG_OIL_PRESSURE_BELOW_NOMINAL = 65536   	# Under-pressure warning\n"
"uint32 FLAG_OIL_PRESSURE_ABOVE_NOMINAL = 131072  	# Over-pressure warning\n"
"\n"
"uint32 FLAG_DEBRIS_SUPPORTED = 262144			# Debris warning. This flag is optional\n"
"uint32 FLAG_DEBRIS_DETECTED = 524288  			# Detection of debris warning\n"
"uint32 flags\n"
"\n"
"uint8 engine_load_percent				# Engine load estimate, percent, [0, 127]\n"
"uint32 engine_speed_rpm					# Engine speed, revolutions per minute\n"
"float32 spark_dwell_time_ms 				# Spark dwell time, millisecond\n"
"float32 atmospheric_pressure_kpa			# Atmospheric (barometric) pressure, kilopascal\n"
"float32 intake_manifold_pressure_kpa			# Engine intake manifold pressure, kilopascal\n"
"float32 intake_manifold_temperature			# Engine intake manifold temperature, kelvin\n"
"float32 coolant_temperature				# Engine coolant temperature, kelvin\n"
"float32 oil_pressure					# Oil pressure, kilopascal\n"
"float32 oil_temperature					# Oil temperature, kelvin\n"
"float32 fuel_pressure					# Fuel pressure, kilopascal\n"
"float32 fuel_consumption_rate_cm3pm			# Instant fuel consumption estimate, (centimeter^3)/minute\n"
"float32 estimated_consumed_fuel_volume_cm3		# Estimate of the consumed fuel since the start of the engine, centimeter^3\n"
"uint8 throttle_position_percent				# Throttle position, percent\n"
"uint8 ecu_index						# The index of the publishing ECU\n"
"\n"
"\n"
"uint8 SPARK_PLUG_SINGLE         = 0\n"
"uint8 SPARK_PLUG_FIRST_ACTIVE   = 1\n"
"uint8 SPARK_PLUG_SECOND_ACTIVE  = 2\n"
"uint8 SPARK_PLUG_BOTH_ACTIVE    = 3\n"
"uint8 spark_plug_usage					# Spark plug activity report.\n"
"\n"
"float32 ignition_timing_deg				# Cylinder ignition timing, angular degrees of the crankshaft\n"
"float32 injection_time_ms				# Fuel injection time, millisecond\n"
"float32 cylinder_head_temperature			# Cylinder head temperature (CHT), kelvin\n"
"float32 exhaust_gas_temperature				# Exhaust gas temperature (EGT), kelvin\n"
"float32 lambda_coefficient				# Estimated lambda coefficient, dimensionless ratio\n"
;
  }

  static const char* value(const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.state);
      stream.next(m.flags);
      stream.next(m.engine_load_percent);
      stream.next(m.engine_speed_rpm);
      stream.next(m.spark_dwell_time_ms);
      stream.next(m.atmospheric_pressure_kpa);
      stream.next(m.intake_manifold_pressure_kpa);
      stream.next(m.intake_manifold_temperature);
      stream.next(m.coolant_temperature);
      stream.next(m.oil_pressure);
      stream.next(m.oil_temperature);
      stream.next(m.fuel_pressure);
      stream.next(m.fuel_consumption_rate_cm3pm);
      stream.next(m.estimated_consumed_fuel_volume_cm3);
      stream.next(m.throttle_position_percent);
      stream.next(m.ecu_index);
      stream.next(m.spark_plug_usage);
      stream.next(m.ignition_timing_deg);
      stream.next(m.injection_time_ms);
      stream.next(m.cylinder_head_temperature);
      stream.next(m.exhaust_gas_temperature);
      stream.next(m.lambda_coefficient);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InternalCombustionEngineStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::InternalCombustionEngineStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flags: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.flags);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engine_load_percent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engine_load_percent);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engine_speed_rpm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.engine_speed_rpm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "spark_dwell_time_ms: ";
    Printer<float>::stream(s, indent + "  ", v.spark_dwell_time_ms);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "atmospheric_pressure_kpa: ";
    Printer<float>::stream(s, indent + "  ", v.atmospheric_pressure_kpa);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "intake_manifold_pressure_kpa: ";
    Printer<float>::stream(s, indent + "  ", v.intake_manifold_pressure_kpa);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "intake_manifold_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.intake_manifold_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coolant_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.coolant_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "oil_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.oil_pressure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "oil_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.oil_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fuel_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.fuel_pressure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fuel_consumption_rate_cm3pm: ";
    Printer<float>::stream(s, indent + "  ", v.fuel_consumption_rate_cm3pm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "estimated_consumed_fuel_volume_cm3: ";
    Printer<float>::stream(s, indent + "  ", v.estimated_consumed_fuel_volume_cm3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "throttle_position_percent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.throttle_position_percent);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ecu_index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ecu_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "spark_plug_usage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.spark_plug_usage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ignition_timing_deg: ";
    Printer<float>::stream(s, indent + "  ", v.ignition_timing_deg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "injection_time_ms: ";
    Printer<float>::stream(s, indent + "  ", v.injection_time_ms);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cylinder_head_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.cylinder_head_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "exhaust_gas_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.exhaust_gas_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lambda_coefficient: ";
    Printer<float>::stream(s, indent + "  ", v.lambda_coefficient);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_INTERNALCOMBUSTIONENGINESTATUS_H
