// Generated by gencpp from file px4_msgs/IrlockReport.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_IRLOCKREPORT_H
#define PX4_MSGS_MESSAGE_IRLOCKREPORT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct IrlockReport_
{
  typedef IrlockReport_<ContainerAllocator> Type;

  IrlockReport_()
    : timestamp(0)
    , signature(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , size_x(0.0)
    , size_y(0.0)  {
    }
  IrlockReport_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , signature(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , size_x(0.0)
    , size_y(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint16_t _signature_type;
  _signature_type signature;

   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _size_x_type;
  _size_x_type size_x;

   typedef float _size_y_type;
  _size_y_type size_y;





  typedef boost::shared_ptr< ::px4_msgs::IrlockReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::IrlockReport_<ContainerAllocator> const> ConstPtr;

}; // struct IrlockReport_

typedef ::px4_msgs::IrlockReport_<std::allocator<void> > IrlockReport;

typedef boost::shared_ptr< ::px4_msgs::IrlockReport > IrlockReportPtr;
typedef boost::shared_ptr< ::px4_msgs::IrlockReport const> IrlockReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::IrlockReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::IrlockReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::IrlockReport_<ContainerAllocator1> & lhs, const ::px4_msgs::IrlockReport_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.signature == rhs.signature &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.size_x == rhs.size_x &&
    lhs.size_y == rhs.size_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::IrlockReport_<ContainerAllocator1> & lhs, const ::px4_msgs::IrlockReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::IrlockReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::IrlockReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::IrlockReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::IrlockReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::IrlockReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::IrlockReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::IrlockReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a8cd45f989bed3a2e11485359ede374";
  }

  static const char* value(const ::px4_msgs::IrlockReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a8cd45f989bed3aULL;
  static const uint64_t static_value2 = 0x2e11485359ede374ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::IrlockReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/IrlockReport";
  }

  static const char* value(const ::px4_msgs::IrlockReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::IrlockReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# IRLOCK_REPORT message data\n"
"\n"
"uint64 timestamp		# time since system start (microseconds)\n"
"\n"
"uint16 signature\n"
"\n"
"# When looking along the optical axis of the camera, x points right, y points down, and z points along the optical axis.\n"
"float32 pos_x # tan(theta), where theta is the angle between the target and the camera center of projection in camera x-axis\n"
"float32 pos_y # tan(theta), where theta is the angle between the target and the camera center of projection in camera y-axis\n"
"float32 size_x #/** size of target along camera x-axis in units of tan(theta) **/\n"
"float32 size_y #/** size of target along camera y-axis in units of tan(theta) **/\n"
;
  }

  static const char* value(const ::px4_msgs::IrlockReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::IrlockReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.signature);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.size_x);
      stream.next(m.size_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IrlockReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::IrlockReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::IrlockReport_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "signature: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.signature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size_x: ";
    Printer<float>::stream(s, indent + "  ", v.size_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size_y: ";
    Printer<float>::stream(s, indent + "  ", v.size_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_IRLOCKREPORT_H
