// Generated by gencpp from file px4_msgs/LandingTargetInnovations.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_LANDINGTARGETINNOVATIONS_H
#define PX4_MSGS_MESSAGE_LANDINGTARGETINNOVATIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct LandingTargetInnovations_
{
  typedef LandingTargetInnovations_<ContainerAllocator> Type;

  LandingTargetInnovations_()
    : timestamp(0)
    , innov_x(0.0)
    , innov_y(0.0)
    , innov_cov_x(0.0)
    , innov_cov_y(0.0)  {
    }
  LandingTargetInnovations_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , innov_x(0.0)
    , innov_y(0.0)
    , innov_cov_x(0.0)
    , innov_cov_y(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef float _innov_x_type;
  _innov_x_type innov_x;

   typedef float _innov_y_type;
  _innov_y_type innov_y;

   typedef float _innov_cov_x_type;
  _innov_cov_x_type innov_cov_x;

   typedef float _innov_cov_y_type;
  _innov_cov_y_type innov_cov_y;





  typedef boost::shared_ptr< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> const> ConstPtr;

}; // struct LandingTargetInnovations_

typedef ::px4_msgs::LandingTargetInnovations_<std::allocator<void> > LandingTargetInnovations;

typedef boost::shared_ptr< ::px4_msgs::LandingTargetInnovations > LandingTargetInnovationsPtr;
typedef boost::shared_ptr< ::px4_msgs::LandingTargetInnovations const> LandingTargetInnovationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator1> & lhs, const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.innov_x == rhs.innov_x &&
    lhs.innov_y == rhs.innov_y &&
    lhs.innov_cov_x == rhs.innov_cov_x &&
    lhs.innov_cov_y == rhs.innov_cov_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator1> & lhs, const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc247da618602e597cbf942f9f691bf5";
  }

  static const char* value(const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc247da618602e59ULL;
  static const uint64_t static_value2 = 0x7cbf942f9f691bf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/LandingTargetInnovations";
  }

  static const char* value(const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"# Innovation of landing target position estimator\n"
"float32 innov_x\n"
"float32 innov_y\n"
"\n"
"# Innovation covariance of landing target position estimator\n"
"float32 innov_cov_x\n"
"float32 innov_cov_y\n"
;
  }

  static const char* value(const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.innov_x);
      stream.next(m.innov_y);
      stream.next(m.innov_cov_x);
      stream.next(m.innov_cov_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandingTargetInnovations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::LandingTargetInnovations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::LandingTargetInnovations_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "innov_x: ";
    Printer<float>::stream(s, indent + "  ", v.innov_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "innov_y: ";
    Printer<float>::stream(s, indent + "  ", v.innov_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "innov_cov_x: ";
    Printer<float>::stream(s, indent + "  ", v.innov_cov_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "innov_cov_y: ";
    Printer<float>::stream(s, indent + "  ", v.innov_cov_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_LANDINGTARGETINNOVATIONS_H
