// Generated by gencpp from file px4_msgs/MultirotorMotorLimits.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_MULTIROTORMOTORLIMITS_H
#define PX4_MSGS_MESSAGE_MULTIROTORMOTORLIMITS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct MultirotorMotorLimits_
{
  typedef MultirotorMotorLimits_<ContainerAllocator> Type;

  MultirotorMotorLimits_()
    : timestamp(0)
    , saturation_status(0)  {
    }
  MultirotorMotorLimits_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , saturation_status(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint16_t _saturation_status_type;
  _saturation_status_type saturation_status;





  typedef boost::shared_ptr< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> const> ConstPtr;

}; // struct MultirotorMotorLimits_

typedef ::px4_msgs::MultirotorMotorLimits_<std::allocator<void> > MultirotorMotorLimits;

typedef boost::shared_ptr< ::px4_msgs::MultirotorMotorLimits > MultirotorMotorLimitsPtr;
typedef boost::shared_ptr< ::px4_msgs::MultirotorMotorLimits const> MultirotorMotorLimitsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator1> & lhs, const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.saturation_status == rhs.saturation_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator1> & lhs, const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c9bc5f0ee134140419c34814bb97e1d";
  }

  static const char* value(const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c9bc5f0ee134140ULL;
  static const uint64_t static_value2 = 0x419c34814bb97e1dULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/MultirotorMotorLimits";
  }

  static const char* value(const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"uint16 saturation_status	# Integer bit mask indicating which axes in the control mixer are saturated\n"
"\n"
"# 0 - True if the saturation status is valid\n"
"# 1 - True if any motor is saturated at the upper limit\n"
"# 2 - True if any motor is saturated at the lower limit\n"
"# 3 - True if a positive roll increment will increase motor saturation\n"
"# 4 - True if negative roll increment will increase motor saturation\n"
"# 5 - True if positive pitch increment will increase motor saturation\n"
"# 6 - True if negative pitch increment will increase motor saturation\n"
"# 7 - True if positive yaw increment will increase motor saturation\n"
"# 8 - True if negative yaw increment will increase motor saturation\n"
"# 9 - True if positive thrust increment will increase motor saturation\n"
"# 10 - True if negative thrust increment will increase motor saturation\n"
;
  }

  static const char* value(const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.saturation_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultirotorMotorLimits_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::MultirotorMotorLimits_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "saturation_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.saturation_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_MULTIROTORMOTORLIMITS_H
