// Generated by gencpp from file px4_msgs/OrbTestLarge.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_ORBTESTLARGE_H
#define PX4_MSGS_MESSAGE_ORBTESTLARGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct OrbTestLarge_
{
  typedef OrbTestLarge_<ContainerAllocator> Type;

  OrbTestLarge_()
    : timestamp(0)
    , val(0)
    , junk()  {
      junk.assign(0);
  }
  OrbTestLarge_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , val(0)
    , junk()  {
  (void)_alloc;
      junk.assign(0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _val_type;
  _val_type val;

   typedef boost::array<uint8_t, 512>  _junk_type;
  _junk_type junk;





  typedef boost::shared_ptr< ::px4_msgs::OrbTestLarge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::OrbTestLarge_<ContainerAllocator> const> ConstPtr;

}; // struct OrbTestLarge_

typedef ::px4_msgs::OrbTestLarge_<std::allocator<void> > OrbTestLarge;

typedef boost::shared_ptr< ::px4_msgs::OrbTestLarge > OrbTestLargePtr;
typedef boost::shared_ptr< ::px4_msgs::OrbTestLarge const> OrbTestLargeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::OrbTestLarge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::OrbTestLarge_<ContainerAllocator1> & lhs, const ::px4_msgs::OrbTestLarge_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.val == rhs.val &&
    lhs.junk == rhs.junk;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::OrbTestLarge_<ContainerAllocator1> & lhs, const ::px4_msgs::OrbTestLarge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::OrbTestLarge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::OrbTestLarge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::OrbTestLarge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a2c4e26530c81646525234ab8a7f037";
  }

  static const char* value(const ::px4_msgs::OrbTestLarge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a2c4e26530c8164ULL;
  static const uint64_t static_value2 = 0x6525234ab8a7f037ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/OrbTestLarge";
  }

  static const char* value(const ::px4_msgs::OrbTestLarge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"\n"
"int32 val\n"
"\n"
"uint8[512] junk\n"
;
  }

  static const char* value(const ::px4_msgs::OrbTestLarge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.val);
      stream.next(m.junk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrbTestLarge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::OrbTestLarge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::OrbTestLarge_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "junk: ";
    if (v.junk.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.junk.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.junk[i]);
    }
    if (v.junk.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_ORBTESTLARGE_H
