// Generated by gencpp from file px4_msgs/Ping.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_PING_H
#define PX4_MSGS_MESSAGE_PING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct Ping_
{
  typedef Ping_<ContainerAllocator> Type;

  Ping_()
    : timestamp(0)
    , ping_time(0)
    , ping_sequence(0)
    , dropped_packets(0)
    , rtt_ms(0.0)
    , system_id(0)
    , component_id(0)  {
    }
  Ping_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , ping_time(0)
    , ping_sequence(0)
    , dropped_packets(0)
    , rtt_ms(0.0)
    , system_id(0)
    , component_id(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _ping_time_type;
  _ping_time_type ping_time;

   typedef uint32_t _ping_sequence_type;
  _ping_sequence_type ping_sequence;

   typedef uint32_t _dropped_packets_type;
  _dropped_packets_type dropped_packets;

   typedef float _rtt_ms_type;
  _rtt_ms_type rtt_ms;

   typedef uint8_t _system_id_type;
  _system_id_type system_id;

   typedef uint8_t _component_id_type;
  _component_id_type component_id;





  typedef boost::shared_ptr< ::px4_msgs::Ping_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::Ping_<ContainerAllocator> const> ConstPtr;

}; // struct Ping_

typedef ::px4_msgs::Ping_<std::allocator<void> > Ping;

typedef boost::shared_ptr< ::px4_msgs::Ping > PingPtr;
typedef boost::shared_ptr< ::px4_msgs::Ping const> PingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::Ping_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::Ping_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::Ping_<ContainerAllocator1> & lhs, const ::px4_msgs::Ping_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.ping_time == rhs.ping_time &&
    lhs.ping_sequence == rhs.ping_sequence &&
    lhs.dropped_packets == rhs.dropped_packets &&
    lhs.rtt_ms == rhs.rtt_ms &&
    lhs.system_id == rhs.system_id &&
    lhs.component_id == rhs.component_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::Ping_<ContainerAllocator1> & lhs, const ::px4_msgs::Ping_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::Ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::Ping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::Ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::Ping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::Ping_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::Ping_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::Ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d59a9f977a01a27a10c3de3830e61e9";
  }

  static const char* value(const ::px4_msgs::Ping_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d59a9f977a01a27ULL;
  static const uint64_t static_value2 = 0xa10c3de3830e61e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::Ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/Ping";
  }

  static const char* value(const ::px4_msgs::Ping_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::Ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp			# time since system start (microseconds)\n"
"uint64 ping_time			# Timestamp of the ping packet\n"
"uint32 ping_sequence		# Sequence number of the ping packet\n"
"uint32 dropped_packets		# Number of dropped ping packets\n"
"float32 rtt_ms				# Round trip time (in ms)\n"
"uint8 system_id				# System ID of the remote system\n"
"uint8 component_id			# Component ID of the remote system\n"
;
  }

  static const char* value(const ::px4_msgs::Ping_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::Ping_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.ping_time);
      stream.next(m.ping_sequence);
      stream.next(m.dropped_packets);
      stream.next(m.rtt_ms);
      stream.next(m.system_id);
      stream.next(m.component_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ping_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::Ping_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::Ping_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ping_time: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.ping_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ping_sequence: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ping_sequence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dropped_packets: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dropped_packets);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rtt_ms: ";
    Printer<float>::stream(s, indent + "  ", v.rtt_ms);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "system_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.system_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "component_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.component_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_PING_H
