// Generated by gencpp from file px4_msgs/PwmInput.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_PWMINPUT_H
#define PX4_MSGS_MESSAGE_PWMINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct PwmInput_
{
  typedef PwmInput_<ContainerAllocator> Type;

  PwmInput_()
    : timestamp(0)
    , error_count(0)
    , pulse_width(0)
    , period(0)  {
    }
  PwmInput_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , error_count(0)
    , pulse_width(0)
    , period(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _error_count_type;
  _error_count_type error_count;

   typedef uint32_t _pulse_width_type;
  _pulse_width_type pulse_width;

   typedef uint32_t _period_type;
  _period_type period;





  typedef boost::shared_ptr< ::px4_msgs::PwmInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::PwmInput_<ContainerAllocator> const> ConstPtr;

}; // struct PwmInput_

typedef ::px4_msgs::PwmInput_<std::allocator<void> > PwmInput;

typedef boost::shared_ptr< ::px4_msgs::PwmInput > PwmInputPtr;
typedef boost::shared_ptr< ::px4_msgs::PwmInput const> PwmInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::PwmInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::PwmInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::PwmInput_<ContainerAllocator1> & lhs, const ::px4_msgs::PwmInput_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.error_count == rhs.error_count &&
    lhs.pulse_width == rhs.pulse_width &&
    lhs.period == rhs.period;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::PwmInput_<ContainerAllocator1> & lhs, const ::px4_msgs::PwmInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::PwmInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::PwmInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::PwmInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::PwmInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::PwmInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::PwmInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::PwmInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad9403b3764307385e74b875cb57afca";
  }

  static const char* value(const ::px4_msgs::PwmInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad9403b376430738ULL;
  static const uint64_t static_value2 = 0x5e74b875cb57afcaULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::PwmInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/PwmInput";
  }

  static const char* value(const ::px4_msgs::PwmInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::PwmInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp	# Time since system start (microseconds)\n"
"uint64 error_count	# Timer overcapture error flag (AUX5 or MAIN5)\n"
"uint32 pulse_width	# Pulse width, timer counts\n"
"uint32 period		# Period, timer counts\n"
;
  }

  static const char* value(const ::px4_msgs::PwmInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::PwmInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.error_count);
      stream.next(m.pulse_width);
      stream.next(m.period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PwmInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::PwmInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::PwmInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_count: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.error_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pulse_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pulse_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "period: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_PWMINPUT_H
