// Generated by gencpp from file px4_msgs/Rpm.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_RPM_H
#define PX4_MSGS_MESSAGE_RPM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct Rpm_
{
  typedef Rpm_<ContainerAllocator> Type;

  Rpm_()
    : timestamp(0)
    , indicated_frequency_rpm(0.0)
    , estimated_accurancy_rpm(0.0)  {
    }
  Rpm_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , indicated_frequency_rpm(0.0)
    , estimated_accurancy_rpm(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef float _indicated_frequency_rpm_type;
  _indicated_frequency_rpm_type indicated_frequency_rpm;

   typedef float _estimated_accurancy_rpm_type;
  _estimated_accurancy_rpm_type estimated_accurancy_rpm;





  typedef boost::shared_ptr< ::px4_msgs::Rpm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::Rpm_<ContainerAllocator> const> ConstPtr;

}; // struct Rpm_

typedef ::px4_msgs::Rpm_<std::allocator<void> > Rpm;

typedef boost::shared_ptr< ::px4_msgs::Rpm > RpmPtr;
typedef boost::shared_ptr< ::px4_msgs::Rpm const> RpmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::Rpm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::Rpm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::Rpm_<ContainerAllocator1> & lhs, const ::px4_msgs::Rpm_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.indicated_frequency_rpm == rhs.indicated_frequency_rpm &&
    lhs.estimated_accurancy_rpm == rhs.estimated_accurancy_rpm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::Rpm_<ContainerAllocator1> & lhs, const ::px4_msgs::Rpm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::Rpm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::Rpm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::Rpm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::Rpm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::Rpm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::Rpm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::Rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc175375a4735e967b5edf61a0cc51d7";
  }

  static const char* value(const ::px4_msgs::Rpm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc175375a4735e96ULL;
  static const uint64_t static_value2 = 0x7b5edf61a0cc51d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::Rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/Rpm";
  }

  static const char* value(const ::px4_msgs::Rpm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::Rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp                      # time since system start (microseconds)\n"
"\n"
"float32 indicated_frequency_rpm       # indicated rotor Frequency in Revolution per minute\n"
"float32 estimated_accurancy_rpm       # estimated accurancy in Revolution per minute\n"
;
  }

  static const char* value(const ::px4_msgs::Rpm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::Rpm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.indicated_frequency_rpm);
      stream.next(m.estimated_accurancy_rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rpm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::Rpm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::Rpm_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "indicated_frequency_rpm: ";
    Printer<float>::stream(s, indent + "  ", v.indicated_frequency_rpm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "estimated_accurancy_rpm: ";
    Printer<float>::stream(s, indent + "  ", v.estimated_accurancy_rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_RPM_H
