// Generated by gencpp from file px4_msgs/SatelliteInfo.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_SATELLITEINFO_H
#define PX4_MSGS_MESSAGE_SATELLITEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct SatelliteInfo_
{
  typedef SatelliteInfo_<ContainerAllocator> Type;

  SatelliteInfo_()
    : timestamp(0)
    , count(0)
    , svid()
    , used()
    , elevation()
    , azimuth()
    , snr()
    , prn()  {
      svid.assign(0);

      used.assign(0);

      elevation.assign(0);

      azimuth.assign(0);

      snr.assign(0);

      prn.assign(0);
  }
  SatelliteInfo_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , count(0)
    , svid()
    , used()
    , elevation()
    , azimuth()
    , snr()
    , prn()  {
  (void)_alloc;
      svid.assign(0);

      used.assign(0);

      elevation.assign(0);

      azimuth.assign(0);

      snr.assign(0);

      prn.assign(0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _count_type;
  _count_type count;

   typedef boost::array<uint8_t, 20>  _svid_type;
  _svid_type svid;

   typedef boost::array<uint8_t, 20>  _used_type;
  _used_type used;

   typedef boost::array<uint8_t, 20>  _elevation_type;
  _elevation_type elevation;

   typedef boost::array<uint8_t, 20>  _azimuth_type;
  _azimuth_type azimuth;

   typedef boost::array<uint8_t, 20>  _snr_type;
  _snr_type snr;

   typedef boost::array<uint8_t, 20>  _prn_type;
  _prn_type prn;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SAT_INFO_MAX_SATELLITES)
  #undef SAT_INFO_MAX_SATELLITES
#endif

  enum {
    SAT_INFO_MAX_SATELLITES = 20u,
  };


  typedef boost::shared_ptr< ::px4_msgs::SatelliteInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::SatelliteInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SatelliteInfo_

typedef ::px4_msgs::SatelliteInfo_<std::allocator<void> > SatelliteInfo;

typedef boost::shared_ptr< ::px4_msgs::SatelliteInfo > SatelliteInfoPtr;
typedef boost::shared_ptr< ::px4_msgs::SatelliteInfo const> SatelliteInfoConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::SatelliteInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::SatelliteInfo_<ContainerAllocator1> & lhs, const ::px4_msgs::SatelliteInfo_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.count == rhs.count &&
    lhs.svid == rhs.svid &&
    lhs.used == rhs.used &&
    lhs.elevation == rhs.elevation &&
    lhs.azimuth == rhs.azimuth &&
    lhs.snr == rhs.snr &&
    lhs.prn == rhs.prn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::SatelliteInfo_<ContainerAllocator1> & lhs, const ::px4_msgs::SatelliteInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SatelliteInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SatelliteInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SatelliteInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb9ed1c67f4f176adc5a2a3e441dc90";
  }

  static const char* value(const ::px4_msgs::SatelliteInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb9ed1c67f4f176ULL;
  static const uint64_t static_value2 = 0xadc5a2a3e441dc90ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/SatelliteInfo";
  }

  static const char* value(const ::px4_msgs::SatelliteInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"uint8 SAT_INFO_MAX_SATELLITES = 20\n"
"\n"
"uint8 count			# Number of satellites visible to the receiver\n"
"uint8[20] svid	 		# Space vehicle ID [1..255], see scheme below\n"
"uint8[20] used			# 0: Satellite not used, 1: used for navigation\n"
"uint8[20] elevation		# Elevation (0: right on top of receiver, 90: on the horizon) of satellite\n"
"uint8[20] azimuth		# Direction of satellite, 0: 0 deg, 255: 360 deg.\n"
"uint8[20] snr			# dBHz, Signal to noise ratio of satellite C/N0, range 0..99, zero when not tracking this satellite.\n"
"uint8[20] prn                   # Satellite PRN code assignment, (psuedorandom number SBAS, valid codes are 120-144)\n"
;
  }

  static const char* value(const ::px4_msgs::SatelliteInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.count);
      stream.next(m.svid);
      stream.next(m.used);
      stream.next(m.elevation);
      stream.next(m.azimuth);
      stream.next(m.snr);
      stream.next(m.prn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SatelliteInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::SatelliteInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::SatelliteInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "svid: ";
    if (v.svid.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.svid.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.svid[i]);
    }
    if (v.svid.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "used: ";
    if (v.used.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.used.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.used[i]);
    }
    if (v.used.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "elevation: ";
    if (v.elevation.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.elevation.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.elevation[i]);
    }
    if (v.elevation.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "azimuth: ";
    if (v.azimuth.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.azimuth.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.azimuth[i]);
    }
    if (v.azimuth.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "snr: ";
    if (v.snr.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.snr.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.snr[i]);
    }
    if (v.snr.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "prn: ";
    if (v.prn.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.prn.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.prn[i]);
    }
    if (v.prn.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_SATELLITEINFO_H
