// Generated by gencpp from file px4_msgs/SensorGyroFft.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_SENSORGYROFFT_H
#define PX4_MSGS_MESSAGE_SENSORGYROFFT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct SensorGyroFft_
{
  typedef SensorGyroFft_<ContainerAllocator> Type;

  SensorGyroFft_()
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , sensor_sample_rate_hz(0.0)
    , resolution_hz(0.0)
    , peak_frequencies_x()
    , peak_frequencies_y()
    , peak_frequencies_z()
    , peak_snr_x()
    , peak_snr_y()
    , peak_snr_z()  {
      peak_frequencies_x.assign(0.0);

      peak_frequencies_y.assign(0.0);

      peak_frequencies_z.assign(0.0);

      peak_snr_x.assign(0.0);

      peak_snr_y.assign(0.0);

      peak_snr_z.assign(0.0);
  }
  SensorGyroFft_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , sensor_sample_rate_hz(0.0)
    , resolution_hz(0.0)
    , peak_frequencies_x()
    , peak_frequencies_y()
    , peak_frequencies_z()
    , peak_snr_x()
    , peak_snr_y()
    , peak_snr_z()  {
  (void)_alloc;
      peak_frequencies_x.assign(0.0);

      peak_frequencies_y.assign(0.0);

      peak_frequencies_z.assign(0.0);

      peak_snr_x.assign(0.0);

      peak_snr_y.assign(0.0);

      peak_snr_z.assign(0.0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _timestamp_sample_type;
  _timestamp_sample_type timestamp_sample;

   typedef uint32_t _device_id_type;
  _device_id_type device_id;

   typedef float _sensor_sample_rate_hz_type;
  _sensor_sample_rate_hz_type sensor_sample_rate_hz;

   typedef float _resolution_hz_type;
  _resolution_hz_type resolution_hz;

   typedef boost::array<float, 3>  _peak_frequencies_x_type;
  _peak_frequencies_x_type peak_frequencies_x;

   typedef boost::array<float, 3>  _peak_frequencies_y_type;
  _peak_frequencies_y_type peak_frequencies_y;

   typedef boost::array<float, 3>  _peak_frequencies_z_type;
  _peak_frequencies_z_type peak_frequencies_z;

   typedef boost::array<float, 3>  _peak_snr_x_type;
  _peak_snr_x_type peak_snr_x;

   typedef boost::array<float, 3>  _peak_snr_y_type;
  _peak_snr_y_type peak_snr_y;

   typedef boost::array<float, 3>  _peak_snr_z_type;
  _peak_snr_z_type peak_snr_z;





  typedef boost::shared_ptr< ::px4_msgs::SensorGyroFft_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::SensorGyroFft_<ContainerAllocator> const> ConstPtr;

}; // struct SensorGyroFft_

typedef ::px4_msgs::SensorGyroFft_<std::allocator<void> > SensorGyroFft;

typedef boost::shared_ptr< ::px4_msgs::SensorGyroFft > SensorGyroFftPtr;
typedef boost::shared_ptr< ::px4_msgs::SensorGyroFft const> SensorGyroFftConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::SensorGyroFft_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::SensorGyroFft_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorGyroFft_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.timestamp_sample == rhs.timestamp_sample &&
    lhs.device_id == rhs.device_id &&
    lhs.sensor_sample_rate_hz == rhs.sensor_sample_rate_hz &&
    lhs.resolution_hz == rhs.resolution_hz &&
    lhs.peak_frequencies_x == rhs.peak_frequencies_x &&
    lhs.peak_frequencies_y == rhs.peak_frequencies_y &&
    lhs.peak_frequencies_z == rhs.peak_frequencies_z &&
    lhs.peak_snr_x == rhs.peak_snr_x &&
    lhs.peak_snr_y == rhs.peak_snr_y &&
    lhs.peak_snr_z == rhs.peak_snr_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::SensorGyroFft_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorGyroFft_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorGyroFft_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorGyroFft_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorGyroFft_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1d417a1ffd9136674a0dbe80a54a206";
  }

  static const char* value(const ::px4_msgs::SensorGyroFft_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1d417a1ffd91366ULL;
  static const uint64_t static_value2 = 0x74a0dbe80a54a206ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/SensorGyroFft";
  }

  static const char* value(const ::px4_msgs::SensorGyroFft_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp          # time since system start (microseconds)\n"
"uint64 timestamp_sample\n"
"\n"
"uint32 device_id          # unique device ID for the sensor that does not change between power cycles\n"
"\n"
"float32 sensor_sample_rate_hz\n"
"float32 resolution_hz\n"
"\n"
"float32[3] peak_frequencies_x # x axis peak frequencies\n"
"float32[3] peak_frequencies_y # y axis peak frequencies\n"
"float32[3] peak_frequencies_z # z axis peak frequencies\n"
"\n"
"float32[3] peak_snr_x # x axis peak SNR\n"
"float32[3] peak_snr_y # y axis peak SNR\n"
"float32[3] peak_snr_z # z axis peak SNR\n"
;
  }

  static const char* value(const ::px4_msgs::SensorGyroFft_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.timestamp_sample);
      stream.next(m.device_id);
      stream.next(m.sensor_sample_rate_hz);
      stream.next(m.resolution_hz);
      stream.next(m.peak_frequencies_x);
      stream.next(m.peak_frequencies_y);
      stream.next(m.peak_frequencies_z);
      stream.next(m.peak_snr_x);
      stream.next(m.peak_snr_y);
      stream.next(m.peak_snr_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorGyroFft_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::SensorGyroFft_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::SensorGyroFft_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sensor_sample_rate_hz: ";
    Printer<float>::stream(s, indent + "  ", v.sensor_sample_rate_hz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "resolution_hz: ";
    Printer<float>::stream(s, indent + "  ", v.resolution_hz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peak_frequencies_x: ";
    if (v.peak_frequencies_x.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.peak_frequencies_x.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.peak_frequencies_x[i]);
    }
    if (v.peak_frequencies_x.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peak_frequencies_y: ";
    if (v.peak_frequencies_y.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.peak_frequencies_y.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.peak_frequencies_y[i]);
    }
    if (v.peak_frequencies_y.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peak_frequencies_z: ";
    if (v.peak_frequencies_z.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.peak_frequencies_z.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.peak_frequencies_z[i]);
    }
    if (v.peak_frequencies_z.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peak_snr_x: ";
    if (v.peak_snr_x.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.peak_snr_x.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.peak_snr_x[i]);
    }
    if (v.peak_snr_x.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peak_snr_y: ";
    if (v.peak_snr_y.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.peak_snr_y.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.peak_snr_y[i]);
    }
    if (v.peak_snr_y.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "peak_snr_z: ";
    if (v.peak_snr_z.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.peak_snr_z.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.peak_snr_z[i]);
    }
    if (v.peak_snr_z.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_SENSORGYROFFT_H
