// Generated by gencpp from file px4_msgs/SensorGyroFifo.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_SENSORGYROFIFO_H
#define PX4_MSGS_MESSAGE_SENSORGYROFIFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct SensorGyroFifo_
{
  typedef SensorGyroFifo_<ContainerAllocator> Type;

  SensorGyroFifo_()
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , dt(0.0)
    , scale(0.0)
    , samples(0)
    , x()
    , y()
    , z()  {
      x.assign(0);

      y.assign(0);

      z.assign(0);
  }
  SensorGyroFifo_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , dt(0.0)
    , scale(0.0)
    , samples(0)
    , x()
    , y()
    , z()  {
  (void)_alloc;
      x.assign(0);

      y.assign(0);

      z.assign(0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _timestamp_sample_type;
  _timestamp_sample_type timestamp_sample;

   typedef uint32_t _device_id_type;
  _device_id_type device_id;

   typedef float _dt_type;
  _dt_type dt;

   typedef float _scale_type;
  _scale_type scale;

   typedef uint8_t _samples_type;
  _samples_type samples;

   typedef boost::array<int16_t, 32>  _x_type;
  _x_type x;

   typedef boost::array<int16_t, 32>  _y_type;
  _y_type y;

   typedef boost::array<int16_t, 32>  _z_type;
  _z_type z;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ORB_QUEUE_LENGTH)
  #undef ORB_QUEUE_LENGTH
#endif

  enum {
    ORB_QUEUE_LENGTH = 4u,
  };


  typedef boost::shared_ptr< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> const> ConstPtr;

}; // struct SensorGyroFifo_

typedef ::px4_msgs::SensorGyroFifo_<std::allocator<void> > SensorGyroFifo;

typedef boost::shared_ptr< ::px4_msgs::SensorGyroFifo > SensorGyroFifoPtr;
typedef boost::shared_ptr< ::px4_msgs::SensorGyroFifo const> SensorGyroFifoConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::SensorGyroFifo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::SensorGyroFifo_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorGyroFifo_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.timestamp_sample == rhs.timestamp_sample &&
    lhs.device_id == rhs.device_id &&
    lhs.dt == rhs.dt &&
    lhs.scale == rhs.scale &&
    lhs.samples == rhs.samples &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::SensorGyroFifo_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorGyroFifo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22c44e826df9573827d2e3b778e1849d";
  }

  static const char* value(const ::px4_msgs::SensorGyroFifo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22c44e826df95738ULL;
  static const uint64_t static_value2 = 0x27d2e3b778e1849dULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/SensorGyroFifo";
  }

  static const char* value(const ::px4_msgs::SensorGyroFifo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp          # time since system start (microseconds)\n"
"uint64 timestamp_sample\n"
"\n"
"uint32 device_id          # unique device ID for the sensor that does not change between power cycles\n"
"\n"
"float32 dt                # delta time between samples (microseconds)\n"
"float32 scale\n"
"\n"
"uint8 samples             # number of valid samples\n"
"\n"
"int16[32] x               # angular velocity in the FRD board frame X-axis in rad/s\n"
"int16[32] y               # angular velocity in the FRD board frame Y-axis in rad/s\n"
"int16[32] z               # angular velocity in the FRD board frame Z-axis in rad/s\n"
"\n"
"uint8 ORB_QUEUE_LENGTH = 4\n"
;
  }

  static const char* value(const ::px4_msgs::SensorGyroFifo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.timestamp_sample);
      stream.next(m.device_id);
      stream.next(m.dt);
      stream.next(m.scale);
      stream.next(m.samples);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorGyroFifo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::SensorGyroFifo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::SensorGyroFifo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dt: ";
    Printer<float>::stream(s, indent + "  ", v.dt);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "scale: ";
    Printer<float>::stream(s, indent + "  ", v.scale);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "samples: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.samples);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    if (v.x.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.x[i]);
    }
    if (v.x.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    if (v.y.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.y[i]);
    }
    if (v.y.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    if (v.z.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.z[i]);
    }
    if (v.z.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_SENSORGYROFIFO_H
