// Generated by gencpp from file px4_msgs/SensorMag.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_SENSORMAG_H
#define PX4_MSGS_MESSAGE_SENSORMAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct SensorMag_
{
  typedef SensorMag_<ContainerAllocator> Type;

  SensorMag_()
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , temperature(0.0)
    , error_count(0)
    , is_external(false)  {
    }
  SensorMag_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , temperature(0.0)
    , error_count(0)
    , is_external(false)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _timestamp_sample_type;
  _timestamp_sample_type timestamp_sample;

   typedef uint32_t _device_id_type;
  _device_id_type device_id;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef uint32_t _error_count_type;
  _error_count_type error_count;

   typedef uint8_t _is_external_type;
  _is_external_type is_external;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ORB_QUEUE_LENGTH)
  #undef ORB_QUEUE_LENGTH
#endif

  enum {
    ORB_QUEUE_LENGTH = 4u,
  };


  typedef boost::shared_ptr< ::px4_msgs::SensorMag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::SensorMag_<ContainerAllocator> const> ConstPtr;

}; // struct SensorMag_

typedef ::px4_msgs::SensorMag_<std::allocator<void> > SensorMag;

typedef boost::shared_ptr< ::px4_msgs::SensorMag > SensorMagPtr;
typedef boost::shared_ptr< ::px4_msgs::SensorMag const> SensorMagConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::SensorMag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::SensorMag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::SensorMag_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorMag_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.timestamp_sample == rhs.timestamp_sample &&
    lhs.device_id == rhs.device_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.temperature == rhs.temperature &&
    lhs.error_count == rhs.error_count &&
    lhs.is_external == rhs.is_external;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::SensorMag_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorMag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorMag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorMag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorMag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorMag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorMag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorMag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::SensorMag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b0ea1a16abcfe97b10eb8e1b94ea27a";
  }

  static const char* value(const ::px4_msgs::SensorMag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b0ea1a16abcfe97ULL;
  static const uint64_t static_value2 = 0xb10eb8e1b94ea27aULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::SensorMag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/SensorMag";
  }

  static const char* value(const ::px4_msgs::SensorMag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::SensorMag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp          # time since system start (microseconds)\n"
"uint64 timestamp_sample\n"
"\n"
"uint32 device_id          # unique device ID for the sensor that does not change between power cycles\n"
"\n"
"float32 x                 # magnetic field in the FRD board frame X-axis in Gauss\n"
"float32 y                 # magnetic field in the FRD board frame Y-axis in Gauss\n"
"float32 z                 # magnetic field in the FRD board frame Z-axis in Gauss\n"
"\n"
"float32 temperature       # temperature in degrees Celsius\n"
"\n"
"uint32 error_count\n"
"\n"
"bool is_external	# if true the mag is external (i.e. not built into the board)\n"
"\n"
"uint8 ORB_QUEUE_LENGTH = 4\n"
;
  }

  static const char* value(const ::px4_msgs::SensorMag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::SensorMag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.timestamp_sample);
      stream.next(m.device_id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.temperature);
      stream.next(m.error_count);
      stream.next(m.is_external);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorMag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::SensorMag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::SensorMag_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_external: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_external);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_SENSORMAG_H
