// Generated by gencpp from file px4_msgs/SensorBaro.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_SENSORBARO_H
#define PX4_MSGS_MESSAGE_SENSORBARO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct SensorBaro_
{
  typedef SensorBaro_<ContainerAllocator> Type;

  SensorBaro_()
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , error_count(0)
    , pressure(0.0)
    , temperature(0.0)  {
    }
  SensorBaro_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , timestamp_sample(0)
    , device_id(0)
    , error_count(0)
    , pressure(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _timestamp_sample_type;
  _timestamp_sample_type timestamp_sample;

   typedef uint32_t _device_id_type;
  _device_id_type device_id;

   typedef uint32_t _error_count_type;
  _error_count_type error_count;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::px4_msgs::SensorBaro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::SensorBaro_<ContainerAllocator> const> ConstPtr;

}; // struct SensorBaro_

typedef ::px4_msgs::SensorBaro_<std::allocator<void> > SensorBaro;

typedef boost::shared_ptr< ::px4_msgs::SensorBaro > SensorBaroPtr;
typedef boost::shared_ptr< ::px4_msgs::SensorBaro const> SensorBaroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::SensorBaro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::SensorBaro_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::SensorBaro_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorBaro_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.timestamp_sample == rhs.timestamp_sample &&
    lhs.device_id == rhs.device_id &&
    lhs.error_count == rhs.error_count &&
    lhs.pressure == rhs.pressure &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::SensorBaro_<ContainerAllocator1> & lhs, const ::px4_msgs::SensorBaro_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorBaro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::SensorBaro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorBaro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::SensorBaro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorBaro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::SensorBaro_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::SensorBaro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d7159e7d1cf8d1cfac5334926c608d2";
  }

  static const char* value(const ::px4_msgs::SensorBaro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d7159e7d1cf8d1cULL;
  static const uint64_t static_value2 = 0xfac5334926c608d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::SensorBaro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/SensorBaro";
  }

  static const char* value(const ::px4_msgs::SensorBaro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::SensorBaro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp          # time since system start (microseconds)\n"
"uint64 timestamp_sample\n"
"\n"
"uint32 device_id          # unique device ID for the sensor that does not change between power cycles\n"
"\n"
"uint32 error_count\n"
"\n"
"float32 pressure	# static pressure measurement in millibar\n"
"\n"
"float32 temperature	# static temperature measurement in deg Celsius\n"
;
  }

  static const char* value(const ::px4_msgs::SensorBaro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::SensorBaro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.timestamp_sample);
      stream.next(m.device_id);
      stream.next(m.error_count);
      stream.next(m.pressure);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorBaro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::SensorBaro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::SensorBaro_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_SENSORBARO_H
