// Generated by gencpp from file px4_msgs/UlogStreamAck.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_ULOGSTREAMACK_H
#define PX4_MSGS_MESSAGE_ULOGSTREAMACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct UlogStreamAck_
{
  typedef UlogStreamAck_<ContainerAllocator> Type;

  UlogStreamAck_()
    : timestamp(0)
    , msg_sequence(0)  {
    }
  UlogStreamAck_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , msg_sequence(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint16_t _msg_sequence_type;
  _msg_sequence_type msg_sequence;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ACK_TIMEOUT)
  #undef ACK_TIMEOUT
#endif
#if defined(_WIN32) && defined(ACK_MAX_TRIES)
  #undef ACK_MAX_TRIES
#endif

  enum {
    ACK_TIMEOUT = 50,
    ACK_MAX_TRIES = 50,
  };


  typedef boost::shared_ptr< ::px4_msgs::UlogStreamAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::UlogStreamAck_<ContainerAllocator> const> ConstPtr;

}; // struct UlogStreamAck_

typedef ::px4_msgs::UlogStreamAck_<std::allocator<void> > UlogStreamAck;

typedef boost::shared_ptr< ::px4_msgs::UlogStreamAck > UlogStreamAckPtr;
typedef boost::shared_ptr< ::px4_msgs::UlogStreamAck const> UlogStreamAckConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::UlogStreamAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::UlogStreamAck_<ContainerAllocator1> & lhs, const ::px4_msgs::UlogStreamAck_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.msg_sequence == rhs.msg_sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::UlogStreamAck_<ContainerAllocator1> & lhs, const ::px4_msgs::UlogStreamAck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::UlogStreamAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::UlogStreamAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::UlogStreamAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "638a3b2b21158f9ecea3bb79ff3004ed";
  }

  static const char* value(const ::px4_msgs::UlogStreamAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x638a3b2b21158f9eULL;
  static const uint64_t static_value2 = 0xcea3bb79ff3004edULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/UlogStreamAck";
  }

  static const char* value(const ::px4_msgs::UlogStreamAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ack a previously sent ulog_stream message that had\n"
"# the NEED_ACK flag set\n"
"\n"
"uint64 timestamp		# time since system start (microseconds)\n"
"int32 ACK_TIMEOUT = 50		# timeout waiting for an ack until we retry to send the message [ms]\n"
"int32 ACK_MAX_TRIES = 50	# maximum amount of tries to (re-)send a message, each time waiting ACK_TIMEOUT ms\n"
"\n"
"uint16 msg_sequence\n"
;
  }

  static const char* value(const ::px4_msgs::UlogStreamAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.msg_sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UlogStreamAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::UlogStreamAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::UlogStreamAck_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "msg_sequence: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.msg_sequence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_ULOGSTREAMACK_H
