// Generated by gencpp from file px4_msgs/VehicleActuatorSetpoint.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_VEHICLEACTUATORSETPOINT_H
#define PX4_MSGS_MESSAGE_VEHICLEACTUATORSETPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct VehicleActuatorSetpoint_
{
  typedef VehicleActuatorSetpoint_<ContainerAllocator> Type;

  VehicleActuatorSetpoint_()
    : timestamp(0)
    , timestamp_sample(0)
    , actuator()  {
      actuator.assign(0.0);
  }
  VehicleActuatorSetpoint_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , timestamp_sample(0)
    , actuator()  {
  (void)_alloc;
      actuator.assign(0.0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint64_t _timestamp_sample_type;
  _timestamp_sample_type timestamp_sample;

   typedef boost::array<float, 16>  _actuator_type;
  _actuator_type actuator;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NUM_ACTUATOR_SETPOINT)
  #undef NUM_ACTUATOR_SETPOINT
#endif

  enum {
    NUM_ACTUATOR_SETPOINT = 16u,
  };


  typedef boost::shared_ptr< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleActuatorSetpoint_

typedef ::px4_msgs::VehicleActuatorSetpoint_<std::allocator<void> > VehicleActuatorSetpoint;

typedef boost::shared_ptr< ::px4_msgs::VehicleActuatorSetpoint > VehicleActuatorSetpointPtr;
typedef boost::shared_ptr< ::px4_msgs::VehicleActuatorSetpoint const> VehicleActuatorSetpointConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator1> & lhs, const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.timestamp_sample == rhs.timestamp_sample &&
    lhs.actuator == rhs.actuator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator1> & lhs, const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ae352ddfa6e9b7d9643f614cb71aa00";
  }

  static const char* value(const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ae352ddfa6e9b7dULL;
  static const uint64_t static_value2 = 0x9643f614cb71aa00ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/VehicleActuatorSetpoint";
  }

  static const char* value(const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp                   # time since system start (microseconds)\n"
"uint64 timestamp_sample            # the timestamp the data this control response is based on was sampled\n"
"\n"
"uint8 NUM_ACTUATOR_SETPOINT = 16\n"
"\n"
"float32[16] actuator\n"
;
  }

  static const char* value(const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.timestamp_sample);
      stream.next(m.actuator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleActuatorSetpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::VehicleActuatorSetpoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actuator: ";
    if (v.actuator.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.actuator.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.actuator[i]);
    }
    if (v.actuator.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_VEHICLEACTUATORSETPOINT_H
