// Generated by gencpp from file px4_msgs/VehicleCommandAck.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_VEHICLECOMMANDACK_H
#define PX4_MSGS_MESSAGE_VEHICLECOMMANDACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct VehicleCommandAck_
{
  typedef VehicleCommandAck_<ContainerAllocator> Type;

  VehicleCommandAck_()
    : timestamp(0)
    , command(0)
    , result(0)
    , from_external(false)
    , result_param1(0)
    , result_param2(0)
    , target_system(0)
    , target_component(0)  {
    }
  VehicleCommandAck_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , command(0)
    , result(0)
    , from_external(false)
    , result_param1(0)
    , result_param2(0)
    , target_system(0)
    , target_component(0)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _command_type;
  _command_type command;

   typedef uint8_t _result_type;
  _result_type result;

   typedef uint8_t _from_external_type;
  _from_external_type from_external;

   typedef uint8_t _result_param1_type;
  _result_param1_type result_param1;

   typedef int32_t _result_param2_type;
  _result_param2_type result_param2;

   typedef uint8_t _target_system_type;
  _target_system_type target_system;

   typedef uint8_t _target_component_type;
  _target_component_type target_component;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(VEHICLE_RESULT_ACCEPTED)
  #undef VEHICLE_RESULT_ACCEPTED
#endif
#if defined(_WIN32) && defined(VEHICLE_RESULT_TEMPORARILY_REJECTED)
  #undef VEHICLE_RESULT_TEMPORARILY_REJECTED
#endif
#if defined(_WIN32) && defined(VEHICLE_RESULT_DENIED)
  #undef VEHICLE_RESULT_DENIED
#endif
#if defined(_WIN32) && defined(VEHICLE_RESULT_UNSUPPORTED)
  #undef VEHICLE_RESULT_UNSUPPORTED
#endif
#if defined(_WIN32) && defined(VEHICLE_RESULT_FAILED)
  #undef VEHICLE_RESULT_FAILED
#endif
#if defined(_WIN32) && defined(VEHICLE_RESULT_IN_PROGRESS)
  #undef VEHICLE_RESULT_IN_PROGRESS
#endif
#if defined(_WIN32) && defined(ARM_AUTH_DENIED_REASON_GENERIC)
  #undef ARM_AUTH_DENIED_REASON_GENERIC
#endif
#if defined(_WIN32) && defined(ARM_AUTH_DENIED_REASON_NONE)
  #undef ARM_AUTH_DENIED_REASON_NONE
#endif
#if defined(_WIN32) && defined(ARM_AUTH_DENIED_REASON_INVALID_WAYPOINT)
  #undef ARM_AUTH_DENIED_REASON_INVALID_WAYPOINT
#endif
#if defined(_WIN32) && defined(ARM_AUTH_DENIED_REASON_TIMEOUT)
  #undef ARM_AUTH_DENIED_REASON_TIMEOUT
#endif
#if defined(_WIN32) && defined(ARM_AUTH_DENIED_REASON_AIRSPACE_IN_USE)
  #undef ARM_AUTH_DENIED_REASON_AIRSPACE_IN_USE
#endif
#if defined(_WIN32) && defined(ARM_AUTH_DENIED_REASON_BAD_WEATHER)
  #undef ARM_AUTH_DENIED_REASON_BAD_WEATHER
#endif
#if defined(_WIN32) && defined(ORB_QUEUE_LENGTH)
  #undef ORB_QUEUE_LENGTH
#endif

  enum {
    VEHICLE_RESULT_ACCEPTED = 0u,
    VEHICLE_RESULT_TEMPORARILY_REJECTED = 1u,
    VEHICLE_RESULT_DENIED = 2u,
    VEHICLE_RESULT_UNSUPPORTED = 3u,
    VEHICLE_RESULT_FAILED = 4u,
    VEHICLE_RESULT_IN_PROGRESS = 5u,
    ARM_AUTH_DENIED_REASON_GENERIC = 0u,
    ARM_AUTH_DENIED_REASON_NONE = 1u,
    ARM_AUTH_DENIED_REASON_INVALID_WAYPOINT = 2u,
    ARM_AUTH_DENIED_REASON_TIMEOUT = 3u,
    ARM_AUTH_DENIED_REASON_AIRSPACE_IN_USE = 4u,
    ARM_AUTH_DENIED_REASON_BAD_WEATHER = 5u,
    ORB_QUEUE_LENGTH = 4u,
  };


  typedef boost::shared_ptr< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleCommandAck_

typedef ::px4_msgs::VehicleCommandAck_<std::allocator<void> > VehicleCommandAck;

typedef boost::shared_ptr< ::px4_msgs::VehicleCommandAck > VehicleCommandAckPtr;
typedef boost::shared_ptr< ::px4_msgs::VehicleCommandAck const> VehicleCommandAckConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::VehicleCommandAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::VehicleCommandAck_<ContainerAllocator1> & lhs, const ::px4_msgs::VehicleCommandAck_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.command == rhs.command &&
    lhs.result == rhs.result &&
    lhs.from_external == rhs.from_external &&
    lhs.result_param1 == rhs.result_param1 &&
    lhs.result_param2 == rhs.result_param2 &&
    lhs.target_system == rhs.target_system &&
    lhs.target_component == rhs.target_component;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::VehicleCommandAck_<ContainerAllocator1> & lhs, const ::px4_msgs::VehicleCommandAck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8b96295e2eed2b151c38d3a79a87de6";
  }

  static const char* value(const ::px4_msgs::VehicleCommandAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8b96295e2eed2b1ULL;
  static const uint64_t static_value2 = 0x51c38d3a79a87de6ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/VehicleCommandAck";
  }

  static const char* value(const ::px4_msgs::VehicleCommandAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 timestamp		# time since system start (microseconds)\n"
"uint8 VEHICLE_RESULT_ACCEPTED = 0\n"
"uint8 VEHICLE_RESULT_TEMPORARILY_REJECTED = 1\n"
"uint8 VEHICLE_RESULT_DENIED = 2\n"
"uint8 VEHICLE_RESULT_UNSUPPORTED = 3\n"
"uint8 VEHICLE_RESULT_FAILED = 4\n"
"uint8 VEHICLE_RESULT_IN_PROGRESS = 5\n"
"\n"
"uint16 ARM_AUTH_DENIED_REASON_GENERIC = 0\n"
"uint16 ARM_AUTH_DENIED_REASON_NONE = 1\n"
"uint16 ARM_AUTH_DENIED_REASON_INVALID_WAYPOINT = 2\n"
"uint16 ARM_AUTH_DENIED_REASON_TIMEOUT = 3\n"
"uint16 ARM_AUTH_DENIED_REASON_AIRSPACE_IN_USE = 4\n"
"uint16 ARM_AUTH_DENIED_REASON_BAD_WEATHER = 5\n"
"\n"
"uint8 ORB_QUEUE_LENGTH = 4\n"
"\n"
"uint32 command\n"
"uint8 result\n"
"bool from_external\n"
"uint8 result_param1\n"
"int32 result_param2\n"
"uint8 target_system\n"
"uint8 target_component\n"
;
  }

  static const char* value(const ::px4_msgs::VehicleCommandAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.command);
      stream.next(m.result);
      stream.next(m.from_external);
      stream.next(m.result_param1);
      stream.next(m.result_param2);
      stream.next(m.target_system);
      stream.next(m.target_component);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleCommandAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::VehicleCommandAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::VehicleCommandAck_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_external: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.from_external);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result_param1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result_param1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result_param2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result_param2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_system);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_component: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_component);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_VEHICLECOMMANDACK_H
