// Generated by gencpp from file mavros_msgs/EndpointAddResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_ENDPOINTADDRESPONSE_H
#define MAVROS_MSGS_MESSAGE_ENDPOINTADDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct EndpointAddResponse_
{
  typedef EndpointAddResponse_<ContainerAllocator> Type;

  EndpointAddResponse_()
    : successful(false)
    , reason()
    , id(0)  {
    }
  EndpointAddResponse_(const ContainerAllocator& _alloc)
    : successful(false)
    , reason(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _successful_type;
  _successful_type successful;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EndpointAddResponse_

typedef ::mavros_msgs::EndpointAddResponse_<std::allocator<void> > EndpointAddResponse;

typedef boost::shared_ptr< ::mavros_msgs::EndpointAddResponse > EndpointAddResponsePtr;
typedef boost::shared_ptr< ::mavros_msgs::EndpointAddResponse const> EndpointAddResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator1> & lhs, const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator2> & rhs)
{
  return lhs.successful == rhs.successful &&
    lhs.reason == rhs.reason &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator1> & lhs, const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a55091fadecc55e698b1923b42d2f691";
  }

  static const char* value(const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa55091fadecc55e6ULL;
  static const uint64_t static_value2 = 0x98b1923b42d2f691ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/EndpointAddResponse";
  }

  static const char* value(const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool successful     # true if endpoint added and opened\n"
"string reason       # returns error description if open fails\n"
"uint32 id           # ID of new endpoint, should be > 0 if endpoint created\n"
"\n"
;
  }

  static const char* value(const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.successful);
      stream.next(m.reason);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndpointAddResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::EndpointAddResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::EndpointAddResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "successful: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.successful);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_ENDPOINTADDRESPONSE_H
