// Generated by gencpp from file mavros_msgs/OpenDroneIDOperatorID.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_OPENDRONEIDOPERATORID_H
#define MAVROS_MSGS_MESSAGE_OPENDRONEIDOPERATORID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct OpenDroneIDOperatorID_
{
  typedef OpenDroneIDOperatorID_<ContainerAllocator> Type;

  OpenDroneIDOperatorID_()
    : header()
    , id_or_mac()
    , operator_id_type(0)
    , operator_id()  {
    }
  OpenDroneIDOperatorID_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id_or_mac(_alloc)
    , operator_id_type(0)
    , operator_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_or_mac_type;
  _id_or_mac_type id_or_mac;

   typedef uint8_t _operator_id_type_type;
  _operator_id_type_type operator_id_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _operator_id_type;
  _operator_id_type operator_id;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ID_TYPE_CAA)
  #undef ID_TYPE_CAA
#endif

  enum {
    ID_TYPE_CAA = 0u,
  };


  typedef boost::shared_ptr< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> const> ConstPtr;

}; // struct OpenDroneIDOperatorID_

typedef ::mavros_msgs::OpenDroneIDOperatorID_<std::allocator<void> > OpenDroneIDOperatorID;

typedef boost::shared_ptr< ::mavros_msgs::OpenDroneIDOperatorID > OpenDroneIDOperatorIDPtr;
typedef boost::shared_ptr< ::mavros_msgs::OpenDroneIDOperatorID const> OpenDroneIDOperatorIDConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator1> & lhs, const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id_or_mac == rhs.id_or_mac &&
    lhs.operator_id_type == rhs.operator_id_type &&
    lhs.operator_id == rhs.operator_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator1> & lhs, const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af2d364e0c491f51ff37e5cd87d9a2ff";
  }

  static const char* value(const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf2d364e0c491f51ULL;
  static const uint64_t static_value2 = 0xff37e5cd87d9a2ffULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/OpenDroneIDOperatorID";
  }

  static const char* value(const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Remote ID message - Operator ID\n"
"# https://mavlink.io/en/messages/common.html#OPEN_DRONE_ID_OPERATOR_ID\n"
"\n"
"# [[[cog:\n"
"# import mavros_cog\n"
"# mavros_cog.idl_decl_enum('MAV_ODID_OPERATOR_ID_TYPE', 'ID_TYPE_')\n"
"# ]]]\n"
"# MAV_ODID_OPERATOR_ID_TYPE\n"
"uint8 ID_TYPE_CAA = 0                    # CAA (Civil Aviation Authority) registered operator ID.\n"
"# [[[end]]] (sum: vhJAtj2LEB)\n"
"\n"
"std_msgs/Header header\n"
"string id_or_mac\n"
"uint8 operator_id_type\n"
"string operator_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id_or_mac);
      stream.next(m.operator_id_type);
      stream.next(m.operator_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenDroneIDOperatorID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::OpenDroneIDOperatorID_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id_or_mac: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id_or_mac);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "operator_id_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operator_id_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "operator_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.operator_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_OPENDRONEIDOPERATORID_H
