# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/ActuatorControls1.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ActuatorControls1(genpy.Message):
  _md5sum = "b2e727b373981b888a45a87c1771aca3"
  _type = "px4_msgs/ActuatorControls1"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp			# time since system start (microseconds)
uint8 NUM_ACTUATOR_CONTROLS = 8
uint8 NUM_ACTUATOR_CONTROL_GROUPS = 6
uint8 INDEX_ROLL = 0
uint8 INDEX_PITCH = 1
uint8 INDEX_YAW = 2
uint8 INDEX_THROTTLE = 3
uint8 INDEX_FLAPS = 4
uint8 INDEX_SPOILERS = 5
uint8 INDEX_AIRBRAKES = 6
uint8 INDEX_LANDING_GEAR = 7
uint8 INDEX_GIMBAL_SHUTTER = 3
uint8 INDEX_CAMERA_ZOOM = 4

uint8 GROUP_INDEX_ATTITUDE = 0
uint8 GROUP_INDEX_ATTITUDE_ALTERNATE = 1
uint8 GROUP_INDEX_GIMBAL = 2
uint8 GROUP_INDEX_MANUAL_PASSTHROUGH = 3
uint8 GROUP_INDEX_ALLOCATED_PART1 = 4
uint8 GROUP_INDEX_ALLOCATED_PART2 = 5
uint8 GROUP_INDEX_PAYLOAD = 6

uint64 timestamp_sample	    # the timestamp the data this control response is based on was sampled
float32[8] control

"""
  # Pseudo-constants
  NUM_ACTUATOR_CONTROLS = 8
  NUM_ACTUATOR_CONTROL_GROUPS = 6
  INDEX_ROLL = 0
  INDEX_PITCH = 1
  INDEX_YAW = 2
  INDEX_THROTTLE = 3
  INDEX_FLAPS = 4
  INDEX_SPOILERS = 5
  INDEX_AIRBRAKES = 6
  INDEX_LANDING_GEAR = 7
  INDEX_GIMBAL_SHUTTER = 3
  INDEX_CAMERA_ZOOM = 4
  GROUP_INDEX_ATTITUDE = 0
  GROUP_INDEX_ATTITUDE_ALTERNATE = 1
  GROUP_INDEX_GIMBAL = 2
  GROUP_INDEX_MANUAL_PASSTHROUGH = 3
  GROUP_INDEX_ALLOCATED_PART1 = 4
  GROUP_INDEX_ALLOCATED_PART2 = 5
  GROUP_INDEX_PAYLOAD = 6

  __slots__ = ['timestamp','timestamp_sample','control']
  _slot_types = ['uint64','uint64','float32[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,timestamp_sample,control

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActuatorControls1, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.timestamp_sample is None:
        self.timestamp_sample = 0
      if self.control is None:
        self.control = [0.] * 8
    else:
      self.timestamp = 0
      self.timestamp_sample = 0
      self.control = [0.] * 8

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Q().pack(_x.timestamp, _x.timestamp_sample))
      buff.write(_get_struct_8f().pack(*self.control))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.timestamp, _x.timestamp_sample,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 32
      self.control = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Q().pack(_x.timestamp, _x.timestamp_sample))
      buff.write(self.control.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.timestamp, _x.timestamp_sample,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 32
      self.control = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=8)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Q = None
def _get_struct_2Q():
    global _struct_2Q
    if _struct_2Q is None:
        _struct_2Q = struct.Struct("<2Q")
    return _struct_2Q
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
