# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/EscStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import px4_msgs.msg

class EscStatus(genpy.Message):
  _md5sum = "7f561cecb9e5a33416b95fb7a7114792"
  _type = "px4_msgs/EscStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp					# time since system start (microseconds)
uint8 CONNECTED_ESC_MAX = 8				# The number of ESCs supported. Current (Q2/2013) we support 8 ESCs

uint8 ESC_CONNECTION_TYPE_PPM = 0			# Traditional PPM ESC
uint8 ESC_CONNECTION_TYPE_SERIAL = 1			# Serial Bus connected ESC
uint8 ESC_CONNECTION_TYPE_ONESHOT = 2			# One Shot PPM
uint8 ESC_CONNECTION_TYPE_I2C = 3			# I2C
uint8 ESC_CONNECTION_TYPE_CAN = 4			# CAN-Bus
uint8 ESC_CONNECTION_TYPE_DSHOT = 5			# DShot

uint16 counter  					# incremented by the writing thread everytime new data is stored

uint8 esc_count						# number of connected ESCs
uint8 esc_connectiontype				# how ESCs connected to the system

uint8 esc_online_flags					# Bitmask indicating which ESC is online/offline
# esc_online_flags bit 0 : Set to 1 if ESC0 is online
# esc_online_flags bit 1 : Set to 1 if ESC1 is online
# esc_online_flags bit 2 : Set to 1 if ESC2 is online
# esc_online_flags bit 3 : Set to 1 if ESC3 is online
# esc_online_flags bit 4 : Set to 1 if ESC4 is online
# esc_online_flags bit 5 : Set to 1 if ESC5 is online
# esc_online_flags bit 6 : Set to 1 if ESC6 is online
# esc_online_flags bit 7 : Set to 1 if ESC7 is online

uint8 esc_armed_flags					# Bitmask indicating which ESC is armed. For ESC's where the arming state is not known (returned by the ESC), the arming bits should always be set.

EscReport[8] esc

================================================================================
MSG: px4_msgs/EscReport
uint64 timestamp					# time since system start (microseconds)
uint32 esc_errorcount					# Number of reported errors by ESC - if supported
int32 esc_rpm						# Motor RPM, negative for reverse rotation [RPM] - if supported
float32 esc_voltage					# Voltage measured from current ESC [V] - if supported
float32 esc_current					# Current measured from current ESC [A] - if supported
uint8 esc_temperature					# Temperature measured from current ESC [degC] - if supported
uint8 esc_address					# Address of current ESC (in most cases 1-8 / must be set by driver)

uint8 esc_state					# State of ESC - depend on Vendor

uint8 failures					# Bitmask to indicate the internal ESC faults

uint8 FAILURE_NONE = 0
uint8 FAILURE_OVER_CURRENT_MASK = 1 		# (1 << 0)
uint8 FAILURE_OVER_VOLTAGE_MASK = 2 		# (1 << 1)
uint8 FAILURE_OVER_TEMPERATURE_MASK = 4 	# (1 << 2)
uint8 FAILURE_OVER_RPM_MASK = 8			# (1 << 3)
uint8 FAILURE_INCONSISTENT_CMD_MASK = 16 	# (1 << 4)  Set if ESC received an inconsistent command (i.e out of boundaries)
uint8 FAILURE_MOTOR_STUCK_MASK = 32		# (1 << 5)
uint8 FAILURE_GENERIC_MASK = 64			# (1 << 6)
"""
  # Pseudo-constants
  CONNECTED_ESC_MAX = 8
  ESC_CONNECTION_TYPE_PPM = 0
  ESC_CONNECTION_TYPE_SERIAL = 1
  ESC_CONNECTION_TYPE_ONESHOT = 2
  ESC_CONNECTION_TYPE_I2C = 3
  ESC_CONNECTION_TYPE_CAN = 4
  ESC_CONNECTION_TYPE_DSHOT = 5

  __slots__ = ['timestamp','counter','esc_count','esc_connectiontype','esc_online_flags','esc_armed_flags','esc']
  _slot_types = ['uint64','uint16','uint8','uint8','uint8','uint8','px4_msgs/EscReport[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,counter,esc_count,esc_connectiontype,esc_online_flags,esc_armed_flags,esc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EscStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.counter is None:
        self.counter = 0
      if self.esc_count is None:
        self.esc_count = 0
      if self.esc_connectiontype is None:
        self.esc_connectiontype = 0
      if self.esc_online_flags is None:
        self.esc_online_flags = 0
      if self.esc_armed_flags is None:
        self.esc_armed_flags = 0
      if self.esc is None:
        self.esc = [px4_msgs.msg.EscReport() for _ in range(8)]
    else:
      self.timestamp = 0
      self.counter = 0
      self.esc_count = 0
      self.esc_connectiontype = 0
      self.esc_online_flags = 0
      self.esc_armed_flags = 0
      self.esc = [px4_msgs.msg.EscReport() for _ in range(8)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_QH4B().pack(_x.timestamp, _x.counter, _x.esc_count, _x.esc_connectiontype, _x.esc_online_flags, _x.esc_armed_flags))
      if len(self.esc) != 8:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (8, len(self.esc), 'self.esc')))
      for val1 in self.esc:
        _x = val1
        buff.write(_get_struct_QIi2f4B().pack(_x.timestamp, _x.esc_errorcount, _x.esc_rpm, _x.esc_voltage, _x.esc_current, _x.esc_temperature, _x.esc_address, _x.esc_state, _x.failures))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.esc is None:
        self.esc = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.timestamp, _x.counter, _x.esc_count, _x.esc_connectiontype, _x.esc_online_flags, _x.esc_armed_flags,) = _get_struct_QH4B().unpack(str[start:end])
      self.esc = []
      for i in range(0, 8):
        val1 = px4_msgs.msg.EscReport()
        _x = val1
        start = end
        end += 28
        (_x.timestamp, _x.esc_errorcount, _x.esc_rpm, _x.esc_voltage, _x.esc_current, _x.esc_temperature, _x.esc_address, _x.esc_state, _x.failures,) = _get_struct_QIi2f4B().unpack(str[start:end])
        self.esc.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_QH4B().pack(_x.timestamp, _x.counter, _x.esc_count, _x.esc_connectiontype, _x.esc_online_flags, _x.esc_armed_flags))
      if len(self.esc) != 8:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (8, len(self.esc), 'self.esc')))
      for val1 in self.esc:
        _x = val1
        buff.write(_get_struct_QIi2f4B().pack(_x.timestamp, _x.esc_errorcount, _x.esc_rpm, _x.esc_voltage, _x.esc_current, _x.esc_temperature, _x.esc_address, _x.esc_state, _x.failures))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.esc is None:
        self.esc = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.timestamp, _x.counter, _x.esc_count, _x.esc_connectiontype, _x.esc_online_flags, _x.esc_armed_flags,) = _get_struct_QH4B().unpack(str[start:end])
      self.esc = []
      for i in range(0, 8):
        val1 = px4_msgs.msg.EscReport()
        _x = val1
        start = end
        end += 28
        (_x.timestamp, _x.esc_errorcount, _x.esc_rpm, _x.esc_voltage, _x.esc_current, _x.esc_temperature, _x.esc_address, _x.esc_state, _x.failures,) = _get_struct_QIi2f4B().unpack(str[start:end])
        self.esc.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_QH4B = None
def _get_struct_QH4B():
    global _struct_QH4B
    if _struct_QH4B is None:
        _struct_QH4B = struct.Struct("<QH4B")
    return _struct_QH4B
_struct_QIi2f4B = None
def _get_struct_QIi2f4B():
    global _struct_QIi2f4B
    if _struct_QIi2f4B is None:
        _struct_QIi2f4B = struct.Struct("<QIi2f4B")
    return _struct_QIi2f4B
