# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/EstimatorOpticalFlowVel.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EstimatorOpticalFlowVel(genpy.Message):
  _md5sum = "4c7f9960b0d868c33dc171f077b5f738"
  _type = "px4_msgs/EstimatorOpticalFlowVel"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp			# time since system start (microseconds)
uint64 timestamp_sample			# the timestamp of the raw data (microseconds)

float32[2] vel_body			# velocity obtained from gyro-compensated and distance-scaled optical flow raw measurements in body frame(m/s)
float32[2] vel_ne			# same as vel_body but in local frame (m/s)
float32[2] flow_uncompensated_integral	# integrated optical flow measurement (rad)
float32[2] flow_compensated_integral	# integrated optical flow measurement compensated for angular motion (rad)
float32[3] gyro_rate_integral		# gyro measurement integrated to flow rate and synchronized with flow measurements (rad)
"""
  __slots__ = ['timestamp','timestamp_sample','vel_body','vel_ne','flow_uncompensated_integral','flow_compensated_integral','gyro_rate_integral']
  _slot_types = ['uint64','uint64','float32[2]','float32[2]','float32[2]','float32[2]','float32[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,timestamp_sample,vel_body,vel_ne,flow_uncompensated_integral,flow_compensated_integral,gyro_rate_integral

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EstimatorOpticalFlowVel, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.timestamp_sample is None:
        self.timestamp_sample = 0
      if self.vel_body is None:
        self.vel_body = [0.] * 2
      if self.vel_ne is None:
        self.vel_ne = [0.] * 2
      if self.flow_uncompensated_integral is None:
        self.flow_uncompensated_integral = [0.] * 2
      if self.flow_compensated_integral is None:
        self.flow_compensated_integral = [0.] * 2
      if self.gyro_rate_integral is None:
        self.gyro_rate_integral = [0.] * 3
    else:
      self.timestamp = 0
      self.timestamp_sample = 0
      self.vel_body = [0.] * 2
      self.vel_ne = [0.] * 2
      self.flow_uncompensated_integral = [0.] * 2
      self.flow_compensated_integral = [0.] * 2
      self.gyro_rate_integral = [0.] * 3

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Q().pack(_x.timestamp, _x.timestamp_sample))
      buff.write(_get_struct_2f().pack(*self.vel_body))
      buff.write(_get_struct_2f().pack(*self.vel_ne))
      buff.write(_get_struct_2f().pack(*self.flow_uncompensated_integral))
      buff.write(_get_struct_2f().pack(*self.flow_compensated_integral))
      buff.write(_get_struct_3f().pack(*self.gyro_rate_integral))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.timestamp, _x.timestamp_sample,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 8
      self.vel_body = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 8
      self.vel_ne = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 8
      self.flow_uncompensated_integral = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 8
      self.flow_compensated_integral = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 12
      self.gyro_rate_integral = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Q().pack(_x.timestamp, _x.timestamp_sample))
      buff.write(self.vel_body.tostring())
      buff.write(self.vel_ne.tostring())
      buff.write(self.flow_uncompensated_integral.tostring())
      buff.write(self.flow_compensated_integral.tostring())
      buff.write(self.gyro_rate_integral.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.timestamp, _x.timestamp_sample,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 8
      self.vel_body = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 8
      self.vel_ne = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 8
      self.flow_uncompensated_integral = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 8
      self.flow_compensated_integral = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 12
      self.gyro_rate_integral = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Q = None
def _get_struct_2Q():
    global _struct_2Q
    if _struct_2Q is None:
        _struct_2Q = struct.Struct("<2Q")
    return _struct_2Q
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
