# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/GimbalDeviceInformation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GimbalDeviceInformation(genpy.Message):
  _md5sum = "06c66f1ae4d6b7f9a66015ce51b3a8bf"
  _type = "px4_msgs/GimbalDeviceInformation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp						# time since system start (microseconds)

uint8[32] vendor_name
uint8[32] model_name
uint8[32] custom_name
uint32 firmware_version
uint32 hardware_version
uint64 uid

uint16 cap_flags

uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_RETRACT = 1
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_NEUTRAL = 2
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_ROLL_AXIS = 4
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_ROLL_FOLLOW = 8
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_ROLL_LOCK = 16
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_PITCH_AXIS = 32
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_PITCH_FOLLOW = 64
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_PITCH_LOCK = 128
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_YAW_AXIS = 256
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_YAW_FOLLOW = 512
uint32 GIMBAL_DEVICE_CAP_FLAGS_HAS_YAW_LOCK = 1024
uint32 GIMBAL_DEVICE_CAP_FLAGS_SUPPORTS_INFINITE_YAW = 2048

uint16 custom_cap_flags

float32 roll_min # [rad]
float32 roll_max # [rad]

float32 pitch_min # [rad]
float32 pitch_max # [rad]

float32 yaw_min # [rad]
float32 yaw_max # [rad]

uint8 gimbal_device_compid
"""
  # Pseudo-constants
  GIMBAL_DEVICE_CAP_FLAGS_HAS_RETRACT = 1
  GIMBAL_DEVICE_CAP_FLAGS_HAS_NEUTRAL = 2
  GIMBAL_DEVICE_CAP_FLAGS_HAS_ROLL_AXIS = 4
  GIMBAL_DEVICE_CAP_FLAGS_HAS_ROLL_FOLLOW = 8
  GIMBAL_DEVICE_CAP_FLAGS_HAS_ROLL_LOCK = 16
  GIMBAL_DEVICE_CAP_FLAGS_HAS_PITCH_AXIS = 32
  GIMBAL_DEVICE_CAP_FLAGS_HAS_PITCH_FOLLOW = 64
  GIMBAL_DEVICE_CAP_FLAGS_HAS_PITCH_LOCK = 128
  GIMBAL_DEVICE_CAP_FLAGS_HAS_YAW_AXIS = 256
  GIMBAL_DEVICE_CAP_FLAGS_HAS_YAW_FOLLOW = 512
  GIMBAL_DEVICE_CAP_FLAGS_HAS_YAW_LOCK = 1024
  GIMBAL_DEVICE_CAP_FLAGS_SUPPORTS_INFINITE_YAW = 2048

  __slots__ = ['timestamp','vendor_name','model_name','custom_name','firmware_version','hardware_version','uid','cap_flags','custom_cap_flags','roll_min','roll_max','pitch_min','pitch_max','yaw_min','yaw_max','gimbal_device_compid']
  _slot_types = ['uint64','uint8[32]','uint8[32]','uint8[32]','uint32','uint32','uint64','uint16','uint16','float32','float32','float32','float32','float32','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,vendor_name,model_name,custom_name,firmware_version,hardware_version,uid,cap_flags,custom_cap_flags,roll_min,roll_max,pitch_min,pitch_max,yaw_min,yaw_max,gimbal_device_compid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GimbalDeviceInformation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.vendor_name is None:
        self.vendor_name = b'\0'*32
      if self.model_name is None:
        self.model_name = b'\0'*32
      if self.custom_name is None:
        self.custom_name = b'\0'*32
      if self.firmware_version is None:
        self.firmware_version = 0
      if self.hardware_version is None:
        self.hardware_version = 0
      if self.uid is None:
        self.uid = 0
      if self.cap_flags is None:
        self.cap_flags = 0
      if self.custom_cap_flags is None:
        self.custom_cap_flags = 0
      if self.roll_min is None:
        self.roll_min = 0.
      if self.roll_max is None:
        self.roll_max = 0.
      if self.pitch_min is None:
        self.pitch_min = 0.
      if self.pitch_max is None:
        self.pitch_max = 0.
      if self.yaw_min is None:
        self.yaw_min = 0.
      if self.yaw_max is None:
        self.yaw_max = 0.
      if self.gimbal_device_compid is None:
        self.gimbal_device_compid = 0
    else:
      self.timestamp = 0
      self.vendor_name = b'\0'*32
      self.model_name = b'\0'*32
      self.custom_name = b'\0'*32
      self.firmware_version = 0
      self.hardware_version = 0
      self.uid = 0
      self.cap_flags = 0
      self.custom_cap_flags = 0
      self.roll_min = 0.
      self.roll_max = 0.
      self.pitch_min = 0.
      self.pitch_max = 0.
      self.yaw_min = 0.
      self.yaw_max = 0.
      self.gimbal_device_compid = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.timestamp
      buff.write(_get_struct_Q().pack(_x))
      _x = self.vendor_name
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_32B().pack(*_x))
      else:
        buff.write(_get_struct_32s().pack(_x))
      _x = self.model_name
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_32B().pack(*_x))
      else:
        buff.write(_get_struct_32s().pack(_x))
      _x = self.custom_name
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_32B().pack(*_x))
      else:
        buff.write(_get_struct_32s().pack(_x))
      _x = self
      buff.write(_get_struct_2IQ2H6fB().pack(_x.firmware_version, _x.hardware_version, _x.uid, _x.cap_flags, _x.custom_cap_flags, _x.roll_min, _x.roll_max, _x.pitch_min, _x.pitch_max, _x.yaw_min, _x.yaw_max, _x.gimbal_device_compid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 32
      self.vendor_name = str[start:end]
      start = end
      end += 32
      self.model_name = str[start:end]
      start = end
      end += 32
      self.custom_name = str[start:end]
      _x = self
      start = end
      end += 45
      (_x.firmware_version, _x.hardware_version, _x.uid, _x.cap_flags, _x.custom_cap_flags, _x.roll_min, _x.roll_max, _x.pitch_min, _x.pitch_max, _x.yaw_min, _x.yaw_max, _x.gimbal_device_compid,) = _get_struct_2IQ2H6fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.timestamp
      buff.write(_get_struct_Q().pack(_x))
      _x = self.vendor_name
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_32B().pack(*_x))
      else:
        buff.write(_get_struct_32s().pack(_x))
      _x = self.model_name
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_32B().pack(*_x))
      else:
        buff.write(_get_struct_32s().pack(_x))
      _x = self.custom_name
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_32B().pack(*_x))
      else:
        buff.write(_get_struct_32s().pack(_x))
      _x = self
      buff.write(_get_struct_2IQ2H6fB().pack(_x.firmware_version, _x.hardware_version, _x.uid, _x.cap_flags, _x.custom_cap_flags, _x.roll_min, _x.roll_max, _x.pitch_min, _x.pitch_max, _x.yaw_min, _x.yaw_max, _x.gimbal_device_compid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 32
      self.vendor_name = str[start:end]
      start = end
      end += 32
      self.model_name = str[start:end]
      start = end
      end += 32
      self.custom_name = str[start:end]
      _x = self
      start = end
      end += 45
      (_x.firmware_version, _x.hardware_version, _x.uid, _x.cap_flags, _x.custom_cap_flags, _x.roll_min, _x.roll_max, _x.pitch_min, _x.pitch_max, _x.yaw_min, _x.yaw_max, _x.gimbal_device_compid,) = _get_struct_2IQ2H6fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IQ2H6fB = None
def _get_struct_2IQ2H6fB():
    global _struct_2IQ2H6fB
    if _struct_2IQ2H6fB is None:
        _struct_2IQ2H6fB = struct.Struct("<2IQ2H6fB")
    return _struct_2IQ2H6fB
_struct_32B = None
def _get_struct_32B():
    global _struct_32B
    if _struct_32B is None:
        _struct_32B = struct.Struct("<32B")
    return _struct_32B
_struct_32s = None
def _get_struct_32s():
    global _struct_32s
    if _struct_32s is None:
        _struct_32s = struct.Struct("<32s")
    return _struct_32s
_struct_Q = None
def _get_struct_Q():
    global _struct_Q
    if _struct_Q is None:
        _struct_Q = struct.Struct("<Q")
    return _struct_Q
