# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/GpsInjectData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GpsInjectData(genpy.Message):
  _md5sum = "6e30b94213a1a8192ae98147ac355fce"
  _type = "px4_msgs/GpsInjectData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp		# time since system start (microseconds)
uint8 len			# length of data
uint8 flags         		# LSB: 1=fragmented
uint8[182] data		# data to write to GPS device (RTCM message)

uint8 ORB_QUEUE_LENGTH = 8
"""
  # Pseudo-constants
  ORB_QUEUE_LENGTH = 8

  __slots__ = ['timestamp','len','flags','data']
  _slot_types = ['uint64','uint8','uint8','uint8[182]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,len,flags,data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GpsInjectData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.len is None:
        self.len = 0
      if self.flags is None:
        self.flags = 0
      if self.data is None:
        self.data = b'\0'*182
    else:
      self.timestamp = 0
      self.len = 0
      self.flags = 0
      self.data = b'\0'*182

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q2B().pack(_x.timestamp, _x.len, _x.flags))
      _x = self.data
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_182B().pack(*_x))
      else:
        buff.write(_get_struct_182s().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.timestamp, _x.len, _x.flags,) = _get_struct_Q2B().unpack(str[start:end])
      start = end
      end += 182
      self.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q2B().pack(_x.timestamp, _x.len, _x.flags))
      _x = self.data
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_182B().pack(*_x))
      else:
        buff.write(_get_struct_182s().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.timestamp, _x.len, _x.flags,) = _get_struct_Q2B().unpack(str[start:end])
      start = end
      end += 182
      self.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_182B = None
def _get_struct_182B():
    global _struct_182B
    if _struct_182B is None:
        _struct_182B = struct.Struct("<182B")
    return _struct_182B
_struct_182s = None
def _get_struct_182s():
    global _struct_182s
    if _struct_182s is None:
        _struct_182s = struct.Struct("<182s")
    return _struct_182s
_struct_Q2B = None
def _get_struct_Q2B():
    global _struct_Q2B
    if _struct_Q2B is None:
        _struct_Q2B = struct.Struct("<Q2B")
    return _struct_Q2B
