# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/InputRc.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class InputRc(genpy.Message):
  _md5sum = "6203c1aed7a8d588c57cc2519a3b4cf7"
  _type = "px4_msgs/InputRc"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp			# time since system start (microseconds)

uint8 RC_INPUT_SOURCE_UNKNOWN = 0
uint8 RC_INPUT_SOURCE_PX4FMU_PPM = 1
uint8 RC_INPUT_SOURCE_PX4IO_PPM = 2
uint8 RC_INPUT_SOURCE_PX4IO_SPEKTRUM = 3
uint8 RC_INPUT_SOURCE_PX4IO_SBUS = 4
uint8 RC_INPUT_SOURCE_PX4IO_ST24 = 5
uint8 RC_INPUT_SOURCE_MAVLINK = 6
uint8 RC_INPUT_SOURCE_QURT = 7
uint8 RC_INPUT_SOURCE_PX4FMU_SPEKTRUM = 8
uint8 RC_INPUT_SOURCE_PX4FMU_SBUS = 9
uint8 RC_INPUT_SOURCE_PX4FMU_ST24 = 10
uint8 RC_INPUT_SOURCE_PX4FMU_SUMD = 11
uint8 RC_INPUT_SOURCE_PX4FMU_DSM = 12
uint8 RC_INPUT_SOURCE_PX4IO_SUMD = 13
uint8 RC_INPUT_SOURCE_PX4FMU_CRSF = 14
uint8 RC_INPUT_SOURCE_PX4FMU_GHST = 15

uint8 RC_INPUT_MAX_CHANNELS = 18 	# Maximum number of R/C input channels in the system. S.Bus has up to 18 channels.

uint64 timestamp_last_signal		# last valid reception time

uint8 channel_count			# number of channels actually being seen

int32 rssi				# receive signal strength indicator (RSSI): < 0: Undefined, 0: no signal, 100: full reception

bool rc_failsafe			# explicit failsafe flag: true on TX failure or TX out of range , false otherwise. Only the true state is reliable, as there are some (PPM) receivers on the market going into failsafe without telling us explicitly.
bool rc_lost				# RC receiver connection status: True,if no frame has arrived in the expected time, false otherwise. True usually means that the receiver has been disconnected, but can also indicate a radio link loss on "stupid" systems. Will remain false, if a RX with failsafe option continues to transmit frames after a link loss.

uint16 rc_lost_frame_count		# Number of lost RC frames. Note: intended purpose: observe the radio link quality if RSSI is not available. This value must not be used to trigger any failsafe-alike funtionality.
uint16 rc_total_frame_count		# Number of total RC frames. Note: intended purpose: observe the radio link quality if RSSI is not available. This value must not be used to trigger any failsafe-alike funtionality.
uint16 rc_ppm_frame_length		# Length of a single PPM frame. Zero for non-PPM systems

uint8 input_source			# Input source
uint16[18] values			# measured pulse widths for each of the supported channels
"""
  # Pseudo-constants
  RC_INPUT_SOURCE_UNKNOWN = 0
  RC_INPUT_SOURCE_PX4FMU_PPM = 1
  RC_INPUT_SOURCE_PX4IO_PPM = 2
  RC_INPUT_SOURCE_PX4IO_SPEKTRUM = 3
  RC_INPUT_SOURCE_PX4IO_SBUS = 4
  RC_INPUT_SOURCE_PX4IO_ST24 = 5
  RC_INPUT_SOURCE_MAVLINK = 6
  RC_INPUT_SOURCE_QURT = 7
  RC_INPUT_SOURCE_PX4FMU_SPEKTRUM = 8
  RC_INPUT_SOURCE_PX4FMU_SBUS = 9
  RC_INPUT_SOURCE_PX4FMU_ST24 = 10
  RC_INPUT_SOURCE_PX4FMU_SUMD = 11
  RC_INPUT_SOURCE_PX4FMU_DSM = 12
  RC_INPUT_SOURCE_PX4IO_SUMD = 13
  RC_INPUT_SOURCE_PX4FMU_CRSF = 14
  RC_INPUT_SOURCE_PX4FMU_GHST = 15
  RC_INPUT_MAX_CHANNELS = 18

  __slots__ = ['timestamp','timestamp_last_signal','channel_count','rssi','rc_failsafe','rc_lost','rc_lost_frame_count','rc_total_frame_count','rc_ppm_frame_length','input_source','values']
  _slot_types = ['uint64','uint64','uint8','int32','bool','bool','uint16','uint16','uint16','uint8','uint16[18]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,timestamp_last_signal,channel_count,rssi,rc_failsafe,rc_lost,rc_lost_frame_count,rc_total_frame_count,rc_ppm_frame_length,input_source,values

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InputRc, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.timestamp_last_signal is None:
        self.timestamp_last_signal = 0
      if self.channel_count is None:
        self.channel_count = 0
      if self.rssi is None:
        self.rssi = 0
      if self.rc_failsafe is None:
        self.rc_failsafe = False
      if self.rc_lost is None:
        self.rc_lost = False
      if self.rc_lost_frame_count is None:
        self.rc_lost_frame_count = 0
      if self.rc_total_frame_count is None:
        self.rc_total_frame_count = 0
      if self.rc_ppm_frame_length is None:
        self.rc_ppm_frame_length = 0
      if self.input_source is None:
        self.input_source = 0
      if self.values is None:
        self.values = [0] * 18
    else:
      self.timestamp = 0
      self.timestamp_last_signal = 0
      self.channel_count = 0
      self.rssi = 0
      self.rc_failsafe = False
      self.rc_lost = False
      self.rc_lost_frame_count = 0
      self.rc_total_frame_count = 0
      self.rc_ppm_frame_length = 0
      self.input_source = 0
      self.values = [0] * 18

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2QBi2B3HB().pack(_x.timestamp, _x.timestamp_last_signal, _x.channel_count, _x.rssi, _x.rc_failsafe, _x.rc_lost, _x.rc_lost_frame_count, _x.rc_total_frame_count, _x.rc_ppm_frame_length, _x.input_source))
      buff.write(_get_struct_18H().pack(*self.values))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.timestamp, _x.timestamp_last_signal, _x.channel_count, _x.rssi, _x.rc_failsafe, _x.rc_lost, _x.rc_lost_frame_count, _x.rc_total_frame_count, _x.rc_ppm_frame_length, _x.input_source,) = _get_struct_2QBi2B3HB().unpack(str[start:end])
      self.rc_failsafe = bool(self.rc_failsafe)
      self.rc_lost = bool(self.rc_lost)
      start = end
      end += 36
      self.values = _get_struct_18H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2QBi2B3HB().pack(_x.timestamp, _x.timestamp_last_signal, _x.channel_count, _x.rssi, _x.rc_failsafe, _x.rc_lost, _x.rc_lost_frame_count, _x.rc_total_frame_count, _x.rc_ppm_frame_length, _x.input_source))
      buff.write(self.values.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.timestamp, _x.timestamp_last_signal, _x.channel_count, _x.rssi, _x.rc_failsafe, _x.rc_lost, _x.rc_lost_frame_count, _x.rc_total_frame_count, _x.rc_ppm_frame_length, _x.input_source,) = _get_struct_2QBi2B3HB().unpack(str[start:end])
      self.rc_failsafe = bool(self.rc_failsafe)
      self.rc_lost = bool(self.rc_lost)
      start = end
      end += 36
      self.values = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=18)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18H = None
def _get_struct_18H():
    global _struct_18H
    if _struct_18H is None:
        _struct_18H = struct.Struct("<18H")
    return _struct_18H
_struct_2QBi2B3HB = None
def _get_struct_2QBi2B3HB():
    global _struct_2QBi2B3HB
    if _struct_2QBi2B3HB is None:
        _struct_2QBi2B3HB = struct.Struct("<2QBi2B3HB")
    return _struct_2QBi2B3HB
