# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/PositionControllerLandingStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PositionControllerLandingStatus(genpy.Message):
  _md5sum = "8ee4812fa6738d9a1053594006a944a6"
  _type = "px4_msgs/PositionControllerLandingStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp		# time since system start (microseconds)

float32 horizontal_slope_displacement

float32 slope_angle_rad

float32 flare_length

bool abort_landing				# true if landing should be aborted
"""
  __slots__ = ['timestamp','horizontal_slope_displacement','slope_angle_rad','flare_length','abort_landing']
  _slot_types = ['uint64','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,horizontal_slope_displacement,slope_angle_rad,flare_length,abort_landing

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PositionControllerLandingStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.horizontal_slope_displacement is None:
        self.horizontal_slope_displacement = 0.
      if self.slope_angle_rad is None:
        self.slope_angle_rad = 0.
      if self.flare_length is None:
        self.flare_length = 0.
      if self.abort_landing is None:
        self.abort_landing = False
    else:
      self.timestamp = 0
      self.horizontal_slope_displacement = 0.
      self.slope_angle_rad = 0.
      self.flare_length = 0.
      self.abort_landing = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q3fB().pack(_x.timestamp, _x.horizontal_slope_displacement, _x.slope_angle_rad, _x.flare_length, _x.abort_landing))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.timestamp, _x.horizontal_slope_displacement, _x.slope_angle_rad, _x.flare_length, _x.abort_landing,) = _get_struct_Q3fB().unpack(str[start:end])
      self.abort_landing = bool(self.abort_landing)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q3fB().pack(_x.timestamp, _x.horizontal_slope_displacement, _x.slope_angle_rad, _x.flare_length, _x.abort_landing))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.timestamp, _x.horizontal_slope_displacement, _x.slope_angle_rad, _x.flare_length, _x.abort_landing,) = _get_struct_Q3fB().unpack(str[start:end])
      self.abort_landing = bool(self.abort_landing)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q3fB = None
def _get_struct_Q3fB():
    global _struct_Q3fB
    if _struct_Q3fB is None:
        _struct_Q3fB = struct.Struct("<Q3fB")
    return _struct_Q3fB
