# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/RateCtrlStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RateCtrlStatus(genpy.Message):
  _md5sum = "759ae42f70d9d613cb08c3223cba4d73"
  _type = "px4_msgs/RateCtrlStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp		# time since system start (microseconds)

# rate controller integrator status
float32 rollspeed_integ
float32 pitchspeed_integ
float32 yawspeed_integ
float32 additional_integ1	# FW: wheel rate integrator (optional)
"""
  __slots__ = ['timestamp','rollspeed_integ','pitchspeed_integ','yawspeed_integ','additional_integ1']
  _slot_types = ['uint64','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,rollspeed_integ,pitchspeed_integ,yawspeed_integ,additional_integ1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RateCtrlStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.rollspeed_integ is None:
        self.rollspeed_integ = 0.
      if self.pitchspeed_integ is None:
        self.pitchspeed_integ = 0.
      if self.yawspeed_integ is None:
        self.yawspeed_integ = 0.
      if self.additional_integ1 is None:
        self.additional_integ1 = 0.
    else:
      self.timestamp = 0
      self.rollspeed_integ = 0.
      self.pitchspeed_integ = 0.
      self.yawspeed_integ = 0.
      self.additional_integ1 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q4f().pack(_x.timestamp, _x.rollspeed_integ, _x.pitchspeed_integ, _x.yawspeed_integ, _x.additional_integ1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.timestamp, _x.rollspeed_integ, _x.pitchspeed_integ, _x.yawspeed_integ, _x.additional_integ1,) = _get_struct_Q4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q4f().pack(_x.timestamp, _x.rollspeed_integ, _x.pitchspeed_integ, _x.yawspeed_integ, _x.additional_integ1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.timestamp, _x.rollspeed_integ, _x.pitchspeed_integ, _x.yawspeed_integ, _x.additional_integ1,) = _get_struct_Q4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q4f = None
def _get_struct_Q4f():
    global _struct_Q4f
    if _struct_Q4f is None:
        _struct_Q4f = struct.Struct("<Q4f")
    return _struct_Q4f
