# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/TecsStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TecsStatus(genpy.Message):
  _md5sum = "efb0866e8757d8a3219ec4000df66f05"
  _type = "px4_msgs/TecsStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp		# time since system start (microseconds)
uint8 TECS_MODE_NORMAL = 0
uint8 TECS_MODE_UNDERSPEED = 1
uint8 TECS_MODE_TAKEOFF = 2
uint8 TECS_MODE_LAND = 3
uint8 TECS_MODE_LAND_THROTTLELIM = 4
uint8 TECS_MODE_BAD_DESCENT = 5
uint8 TECS_MODE_CLIMBOUT = 6


float32 altitude_sp
float32 altitude_filtered
float32 height_rate_setpoint
float32 height_rate
float32 equivalent_airspeed_sp
float32 true_airspeed_sp
float32 true_airspeed_filtered
float32 true_airspeed_derivative_sp
float32 true_airspeed_derivative
float32 true_airspeed_derivative_raw
float32 true_airspeed_innovation

float32 total_energy_error
float32 energy_distribution_error
float32 total_energy_rate_error
float32 energy_distribution_rate_error

float32 total_energy
float32 total_energy_rate
float32 total_energy_balance
float32 total_energy_balance_rate

float32 total_energy_sp
float32 total_energy_rate_sp
float32 total_energy_balance_sp
float32 total_energy_balance_rate_sp

float32 throttle_integ
float32 pitch_integ

float32 throttle_sp
float32 pitch_sp_rad

uint8 mode
"""
  # Pseudo-constants
  TECS_MODE_NORMAL = 0
  TECS_MODE_UNDERSPEED = 1
  TECS_MODE_TAKEOFF = 2
  TECS_MODE_LAND = 3
  TECS_MODE_LAND_THROTTLELIM = 4
  TECS_MODE_BAD_DESCENT = 5
  TECS_MODE_CLIMBOUT = 6

  __slots__ = ['timestamp','altitude_sp','altitude_filtered','height_rate_setpoint','height_rate','equivalent_airspeed_sp','true_airspeed_sp','true_airspeed_filtered','true_airspeed_derivative_sp','true_airspeed_derivative','true_airspeed_derivative_raw','true_airspeed_innovation','total_energy_error','energy_distribution_error','total_energy_rate_error','energy_distribution_rate_error','total_energy','total_energy_rate','total_energy_balance','total_energy_balance_rate','total_energy_sp','total_energy_rate_sp','total_energy_balance_sp','total_energy_balance_rate_sp','throttle_integ','pitch_integ','throttle_sp','pitch_sp_rad','mode']
  _slot_types = ['uint64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,altitude_sp,altitude_filtered,height_rate_setpoint,height_rate,equivalent_airspeed_sp,true_airspeed_sp,true_airspeed_filtered,true_airspeed_derivative_sp,true_airspeed_derivative,true_airspeed_derivative_raw,true_airspeed_innovation,total_energy_error,energy_distribution_error,total_energy_rate_error,energy_distribution_rate_error,total_energy,total_energy_rate,total_energy_balance,total_energy_balance_rate,total_energy_sp,total_energy_rate_sp,total_energy_balance_sp,total_energy_balance_rate_sp,throttle_integ,pitch_integ,throttle_sp,pitch_sp_rad,mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TecsStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.altitude_sp is None:
        self.altitude_sp = 0.
      if self.altitude_filtered is None:
        self.altitude_filtered = 0.
      if self.height_rate_setpoint is None:
        self.height_rate_setpoint = 0.
      if self.height_rate is None:
        self.height_rate = 0.
      if self.equivalent_airspeed_sp is None:
        self.equivalent_airspeed_sp = 0.
      if self.true_airspeed_sp is None:
        self.true_airspeed_sp = 0.
      if self.true_airspeed_filtered is None:
        self.true_airspeed_filtered = 0.
      if self.true_airspeed_derivative_sp is None:
        self.true_airspeed_derivative_sp = 0.
      if self.true_airspeed_derivative is None:
        self.true_airspeed_derivative = 0.
      if self.true_airspeed_derivative_raw is None:
        self.true_airspeed_derivative_raw = 0.
      if self.true_airspeed_innovation is None:
        self.true_airspeed_innovation = 0.
      if self.total_energy_error is None:
        self.total_energy_error = 0.
      if self.energy_distribution_error is None:
        self.energy_distribution_error = 0.
      if self.total_energy_rate_error is None:
        self.total_energy_rate_error = 0.
      if self.energy_distribution_rate_error is None:
        self.energy_distribution_rate_error = 0.
      if self.total_energy is None:
        self.total_energy = 0.
      if self.total_energy_rate is None:
        self.total_energy_rate = 0.
      if self.total_energy_balance is None:
        self.total_energy_balance = 0.
      if self.total_energy_balance_rate is None:
        self.total_energy_balance_rate = 0.
      if self.total_energy_sp is None:
        self.total_energy_sp = 0.
      if self.total_energy_rate_sp is None:
        self.total_energy_rate_sp = 0.
      if self.total_energy_balance_sp is None:
        self.total_energy_balance_sp = 0.
      if self.total_energy_balance_rate_sp is None:
        self.total_energy_balance_rate_sp = 0.
      if self.throttle_integ is None:
        self.throttle_integ = 0.
      if self.pitch_integ is None:
        self.pitch_integ = 0.
      if self.throttle_sp is None:
        self.throttle_sp = 0.
      if self.pitch_sp_rad is None:
        self.pitch_sp_rad = 0.
      if self.mode is None:
        self.mode = 0
    else:
      self.timestamp = 0
      self.altitude_sp = 0.
      self.altitude_filtered = 0.
      self.height_rate_setpoint = 0.
      self.height_rate = 0.
      self.equivalent_airspeed_sp = 0.
      self.true_airspeed_sp = 0.
      self.true_airspeed_filtered = 0.
      self.true_airspeed_derivative_sp = 0.
      self.true_airspeed_derivative = 0.
      self.true_airspeed_derivative_raw = 0.
      self.true_airspeed_innovation = 0.
      self.total_energy_error = 0.
      self.energy_distribution_error = 0.
      self.total_energy_rate_error = 0.
      self.energy_distribution_rate_error = 0.
      self.total_energy = 0.
      self.total_energy_rate = 0.
      self.total_energy_balance = 0.
      self.total_energy_balance_rate = 0.
      self.total_energy_sp = 0.
      self.total_energy_rate_sp = 0.
      self.total_energy_balance_sp = 0.
      self.total_energy_balance_rate_sp = 0.
      self.throttle_integ = 0.
      self.pitch_integ = 0.
      self.throttle_sp = 0.
      self.pitch_sp_rad = 0.
      self.mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q27fB().pack(_x.timestamp, _x.altitude_sp, _x.altitude_filtered, _x.height_rate_setpoint, _x.height_rate, _x.equivalent_airspeed_sp, _x.true_airspeed_sp, _x.true_airspeed_filtered, _x.true_airspeed_derivative_sp, _x.true_airspeed_derivative, _x.true_airspeed_derivative_raw, _x.true_airspeed_innovation, _x.total_energy_error, _x.energy_distribution_error, _x.total_energy_rate_error, _x.energy_distribution_rate_error, _x.total_energy, _x.total_energy_rate, _x.total_energy_balance, _x.total_energy_balance_rate, _x.total_energy_sp, _x.total_energy_rate_sp, _x.total_energy_balance_sp, _x.total_energy_balance_rate_sp, _x.throttle_integ, _x.pitch_integ, _x.throttle_sp, _x.pitch_sp_rad, _x.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 117
      (_x.timestamp, _x.altitude_sp, _x.altitude_filtered, _x.height_rate_setpoint, _x.height_rate, _x.equivalent_airspeed_sp, _x.true_airspeed_sp, _x.true_airspeed_filtered, _x.true_airspeed_derivative_sp, _x.true_airspeed_derivative, _x.true_airspeed_derivative_raw, _x.true_airspeed_innovation, _x.total_energy_error, _x.energy_distribution_error, _x.total_energy_rate_error, _x.energy_distribution_rate_error, _x.total_energy, _x.total_energy_rate, _x.total_energy_balance, _x.total_energy_balance_rate, _x.total_energy_sp, _x.total_energy_rate_sp, _x.total_energy_balance_sp, _x.total_energy_balance_rate_sp, _x.throttle_integ, _x.pitch_integ, _x.throttle_sp, _x.pitch_sp_rad, _x.mode,) = _get_struct_Q27fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q27fB().pack(_x.timestamp, _x.altitude_sp, _x.altitude_filtered, _x.height_rate_setpoint, _x.height_rate, _x.equivalent_airspeed_sp, _x.true_airspeed_sp, _x.true_airspeed_filtered, _x.true_airspeed_derivative_sp, _x.true_airspeed_derivative, _x.true_airspeed_derivative_raw, _x.true_airspeed_innovation, _x.total_energy_error, _x.energy_distribution_error, _x.total_energy_rate_error, _x.energy_distribution_rate_error, _x.total_energy, _x.total_energy_rate, _x.total_energy_balance, _x.total_energy_balance_rate, _x.total_energy_sp, _x.total_energy_rate_sp, _x.total_energy_balance_sp, _x.total_energy_balance_rate_sp, _x.throttle_integ, _x.pitch_integ, _x.throttle_sp, _x.pitch_sp_rad, _x.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 117
      (_x.timestamp, _x.altitude_sp, _x.altitude_filtered, _x.height_rate_setpoint, _x.height_rate, _x.equivalent_airspeed_sp, _x.true_airspeed_sp, _x.true_airspeed_filtered, _x.true_airspeed_derivative_sp, _x.true_airspeed_derivative, _x.true_airspeed_derivative_raw, _x.true_airspeed_innovation, _x.total_energy_error, _x.energy_distribution_error, _x.total_energy_rate_error, _x.energy_distribution_rate_error, _x.total_energy, _x.total_energy_rate, _x.total_energy_balance, _x.total_energy_balance_rate, _x.total_energy_sp, _x.total_energy_rate_sp, _x.total_energy_balance_sp, _x.total_energy_balance_rate_sp, _x.throttle_integ, _x.pitch_integ, _x.throttle_sp, _x.pitch_sp_rad, _x.mode,) = _get_struct_Q27fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q27fB = None
def _get_struct_Q27fB():
    global _struct_Q27fB
    if _struct_Q27fB is None:
        _struct_Q27fB = struct.Struct("<Q27fB")
    return _struct_Q27fB
