# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/VehicleAirData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehicleAirData(genpy.Message):
  _md5sum = "6adf20b0219ea5ac1893d62c1f459ea8"
  _type = "px4_msgs/VehicleAirData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint64 timestamp            # time since system start (microseconds)

uint64 timestamp_sample     # the timestamp of the raw data (microseconds)

uint32 baro_device_id       # unique device ID for the selected barometer

float32 baro_alt_meter			# Altitude above MSL calculated from temperature compensated baro sensor data using an ISA corrected for sea level pressure SENS_BARO_QNH.
float32 baro_temp_celcius		# Temperature in degrees Celsius
float32 baro_pressure_pa		# Absolute pressure in Pascals

float32 rho				# air density
"""
  __slots__ = ['timestamp','timestamp_sample','baro_device_id','baro_alt_meter','baro_temp_celcius','baro_pressure_pa','rho']
  _slot_types = ['uint64','uint64','uint32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,timestamp_sample,baro_device_id,baro_alt_meter,baro_temp_celcius,baro_pressure_pa,rho

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleAirData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.timestamp_sample is None:
        self.timestamp_sample = 0
      if self.baro_device_id is None:
        self.baro_device_id = 0
      if self.baro_alt_meter is None:
        self.baro_alt_meter = 0.
      if self.baro_temp_celcius is None:
        self.baro_temp_celcius = 0.
      if self.baro_pressure_pa is None:
        self.baro_pressure_pa = 0.
      if self.rho is None:
        self.rho = 0.
    else:
      self.timestamp = 0
      self.timestamp_sample = 0
      self.baro_device_id = 0
      self.baro_alt_meter = 0.
      self.baro_temp_celcius = 0.
      self.baro_pressure_pa = 0.
      self.rho = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2QI4f().pack(_x.timestamp, _x.timestamp_sample, _x.baro_device_id, _x.baro_alt_meter, _x.baro_temp_celcius, _x.baro_pressure_pa, _x.rho))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.timestamp, _x.timestamp_sample, _x.baro_device_id, _x.baro_alt_meter, _x.baro_temp_celcius, _x.baro_pressure_pa, _x.rho,) = _get_struct_2QI4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2QI4f().pack(_x.timestamp, _x.timestamp_sample, _x.baro_device_id, _x.baro_alt_meter, _x.baro_temp_celcius, _x.baro_pressure_pa, _x.rho))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.timestamp, _x.timestamp_sample, _x.baro_device_id, _x.baro_alt_meter, _x.baro_temp_celcius, _x.baro_pressure_pa, _x.rho,) = _get_struct_2QI4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2QI4f = None
def _get_struct_2QI4f():
    global _struct_2QI4f
    if _struct_2QI4f is None:
        _struct_2QI4f = struct.Struct("<2QI4f")
    return _struct_2QI4f
