# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/YawEstimatorStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class YawEstimatorStatus(genpy.Message):
  _md5sum = "283df0bd2b912ddf8ed94f6c29833748"
  _type = "px4_msgs/YawEstimatorStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 timestamp		# time since system start (microseconds)
uint64 timestamp_sample         # the timestamp of the raw data (microseconds)

float32 yaw_composite	# composite yaw from GSF (rad)
float32 yaw_variance	# composite yaw variance from GSF (rad^2)

float32[5] yaw		# yaw estimate for each model in the filter bank (rad)
float32[5] innov_vn	# North velocity innovation for each model in the filter bank (m/s)
float32[5] innov_ve	# East velocity innovation for each model in the filter bank (m/s)
float32[5] weight	# weighting for each model in the filter bank
"""
  __slots__ = ['timestamp','timestamp_sample','yaw_composite','yaw_variance','yaw','innov_vn','innov_ve','weight']
  _slot_types = ['uint64','uint64','float32','float32','float32[5]','float32[5]','float32[5]','float32[5]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,timestamp_sample,yaw_composite,yaw_variance,yaw,innov_vn,innov_ve,weight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YawEstimatorStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.timestamp_sample is None:
        self.timestamp_sample = 0
      if self.yaw_composite is None:
        self.yaw_composite = 0.
      if self.yaw_variance is None:
        self.yaw_variance = 0.
      if self.yaw is None:
        self.yaw = [0.] * 5
      if self.innov_vn is None:
        self.innov_vn = [0.] * 5
      if self.innov_ve is None:
        self.innov_ve = [0.] * 5
      if self.weight is None:
        self.weight = [0.] * 5
    else:
      self.timestamp = 0
      self.timestamp_sample = 0
      self.yaw_composite = 0.
      self.yaw_variance = 0.
      self.yaw = [0.] * 5
      self.innov_vn = [0.] * 5
      self.innov_ve = [0.] * 5
      self.weight = [0.] * 5

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Q2f().pack(_x.timestamp, _x.timestamp_sample, _x.yaw_composite, _x.yaw_variance))
      buff.write(_get_struct_5f().pack(*self.yaw))
      buff.write(_get_struct_5f().pack(*self.innov_vn))
      buff.write(_get_struct_5f().pack(*self.innov_ve))
      buff.write(_get_struct_5f().pack(*self.weight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.timestamp, _x.timestamp_sample, _x.yaw_composite, _x.yaw_variance,) = _get_struct_2Q2f().unpack(str[start:end])
      start = end
      end += 20
      self.yaw = _get_struct_5f().unpack(str[start:end])
      start = end
      end += 20
      self.innov_vn = _get_struct_5f().unpack(str[start:end])
      start = end
      end += 20
      self.innov_ve = _get_struct_5f().unpack(str[start:end])
      start = end
      end += 20
      self.weight = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Q2f().pack(_x.timestamp, _x.timestamp_sample, _x.yaw_composite, _x.yaw_variance))
      buff.write(self.yaw.tostring())
      buff.write(self.innov_vn.tostring())
      buff.write(self.innov_ve.tostring())
      buff.write(self.weight.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.timestamp, _x.timestamp_sample, _x.yaw_composite, _x.yaw_variance,) = _get_struct_2Q2f().unpack(str[start:end])
      start = end
      end += 20
      self.yaw = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      start = end
      end += 20
      self.innov_vn = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      start = end
      end += 20
      self.innov_ve = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      start = end
      end += 20
      self.weight = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Q2f = None
def _get_struct_2Q2f():
    global _struct_2Q2f
    if _struct_2Q2f is None:
        _struct_2Q2f = struct.Struct("<2Q2f")
    return _struct_2Q2f
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
